### ISSUE TITLE
[Question] onSaveInstanceState() vs onSaveViewState()

### ISSUE THREAD

**Issue by mheras** [bluelinelabs/Conductor#100]
Hi!

I'd like to know the difference between `Controller.onSaveInstanceState()` and `Controller.onSaveViewState()`.

When are they called? Are they executed conditionally? What would I put in each method?

From what I can see in the source code, both methods are called at the same time (I mean, when the `Activity.onSaveInstanceState()` is called).

Thanks!

**Comment by EricKuck** [comment]
From a high level, `onSaveViewState()` is meant to save anything you need to about your `View` before it's destroyed. This is where you'd save things related to your view (maybe a `TextView`'s visibility, for instance). `onSaveInstanceState()` is meant to save anything you need to be able to recreate the controller if Android decides to kill your process. Here you might save a model that relates to your controller.

While in many scenarios your controller instance and view will be saved at the same time (ex: you hit the home button and Android could kill your process at any time), they often won't be. Unless you've set your controller's view retain mode to hold on to its view when it's detached from the window, the view will be destroyed and deallocated when it's no longer needed. In this case, `onSaveViewState()` will be called without calling `onSaveInstanceState()`, as the controller instance will stick around until it's destroyed.

**Comment by mheras** [comment]
The behavior you describe is what I suspected, but in this method I can see that both `Controller.saveViewState()` (which ends up calling `Controller.onSaveViewState()`) and `Controller.onSaveInstanceState()` are called one after the other, without performing any check before. So I cannot see how `Controller.onSaveViewState()` can be called and `Controller.onSaveInstanceState()` not.

Am I missing something?

Thanks!

**Comment by EricKuck** [comment]
Both methods are called there (if the view is present at the time). The view is also saved separately when it's dealloc'd. If you're looking for that in the source, it's at

**Comment by mheras** [comment]
Perfect, thanks for quick response!!
