### ISSUE TITLE
The same backstack is saved for different routers

### ISSUE THREAD

**Issue by shchurov** [bluelinelabs/Conductor#108]
We need to display 2 different controllers each in its own container, so I attached 2 routers to the same activity. It works good, however, if I kill and restore the activity, it shows the same controllers in both containers. I debugged it for a while and it seems that the problem is here:

https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/Router.java#L448
It saves both `backstackState` bundles to the same `outState` object using `KEY_BACKSTACK` key.
Not sure if it's important but one of those controllers contains `ViewPager` that displays a few child controllers.

**Comment by hannesstruss** [comment]
To me that rather sounds like a use case for one parent router and [multiple child routers](https://github.com/bluelinelabs/Conductor/blob/develop/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/MultipleChildRouterController.java).

**Comment by shchurov** [comment]
@hannesstruss Do you mean that I need to wrap everything in an extra top router?

**Comment by hannesstruss** [comment]
@shchurov yeah, that's what I meant. I thought they weren't, but it looks like multiple top-level routers per activity should actually be supported: https://github.com/bluelinelabs/Conductor/issues/24#issuecomment-210246139

**Comment by shchurov** [comment]
@hannesstruss I think that should work but it adds some overhead to the code. Would be nice if multiple parent routers worked as well (and they mostly do except restoring).

**Comment by EricKuck** [comment]
Multiple top-level routers were the preferred way to go in Conductor v1, but nested child controllers became preferred in v2. That being said, breaking multiple top-level routers should not have happened and will be fixed shortly.
