### ISSUE TITLE
Communication between controllers

### ISSUE THREAD

**Issue by MFlisar** [bluelinelabs/Conductor#115]
Is there a preferred way for this? Should this happen the way activities and fragments do it? (Parent integrates an interface and child casts the parent to that interface?)

Or is there another preferred method?

**Comment by sockeqwe** [comment]
You can use Controller.setTargetController() which is similar to
Fragment.setTargetFragment() to communicate between fragments

MFlisar <notifications@github.com> schrieb am Mo., 12. Sep. 2016, 09:33:

**Comment by MFlisar** [comment]
Thanks. I'll check that and try it out

**Comment by MFlisar** [comment]
*One short question:* 

Using this the way like here 
https://github.com/bluelinelabs/Conductor/blob/8a70c09fea06765b6e17a9ded4b9a87edc3e1741/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/TargetTitleEntryController.java
 will this take care of setting the target controller again when the empty constructor is called by the conducator framework? Or do I have to do this again? Then I need a setter without an exception though...

**Comment by sockeqwe** [comment]
you don't have to do this in constructor or do that again. Internally every
conductor controller has a unique id. setTargetController() is basically
just reading internally the id of the target controller and save it in a
bundle, that will be used in case that the activity has been destroyed.
Whenever you call getTargetController() conductor internally searches for
the target controller instance by looking for the id of the controller

MFlisar <notifications@github.com> schrieb am Mo., 12. Sep. 2016, 10:33:

**Comment by MFlisar** [comment]
Good to know. Thanks for explanation.
