### ISSUE TITLE
onCreateView - why was the savedInstanceState bundle removed

### ISSUE THREAD

**Issue by MFlisar** [bluelinelabs/Conductor#116]
The title says it all. Quite a lot of libraries allow to automatically restore it's state with a bundle and they can then easily be used like following (example on Mike Penz's drawer):

     DrawerBuilder builder= new DrawerBuilder()
          .withSavedInstance(savedInstanceState);

This means, if I want to use that and I'm depending on views being created already, I have to store the bundle from `onRestoreInstanceState` of the controller?

**Comment by EricKuck** [comment]
It wasn't removed. It was never there. I recently ran into a similar issue with Google's MapView class as well, where they're expecting you to call `onCreate` with a saved state bundle. IMO, this is poor design, but it does seem like something that's common enough that there should be a way around it. 

Perhaps we'll need to add a `onCreateView(Bundle)` method that would handle both creation and restoration of state. I hate adding more callbacks, but I can't think of any other good ways to handle this.

**Comment by MFlisar** [comment]
You're right, it is not there in views only in the activity...

Actually saving the bundle in the `onRestoreInstanceState`, using the saved bundle in the `onCreateView` and setting it back to null afterwards should work as well, shouldn't it?

**Comment by MFlisar** [comment]
I have another use case for it:

When you first show a view, you may want to animate some parts of it (like sliding in toolbar or FAB), if you rotate the device, you don't want to do this animations. Normally you check if the `savedInstanceState` is `null` or not.

Is there another way to do this than saving the bundle for this use case?

**Comment by gregpearce** [comment]
It seems like it would also be useful for `onDestroyView` to have an equivalent `Bundle` argument, which can be used to preserve state across the configuration changes, but also while the view is on the backstack.
In the default `setRetainViewMode(RELEASE_DETACH)` mode, a view is destroyed when it goes on to the backstack and there is no opportunity to call `onSaveInstanceState` and put the state in a `Bundle`.

**Comment by EricKuck** [comment]
@gregpearce There's already a `onSaveViewState` method that does exactly what you want it to do. View state and instance state are 2 different things.

**Comment by EricKuck** [comment]
960b9317449f8b5507e05774d4ab7828b1bcee1c adds a view state bundle getter, which can be used to obtain the saved view state. The next major revision of Conductor will likely include this bundle in the `onCreateView` method.

**Comment by EricKuck** [comment]
Just a heads up that 39ab4723ffd261651e1aa8d78d8992743b54b8ea changes the way this works. The getter has been removed, as this is a non-standard way to retrieve view state. Instead, a simple `Controller` subclass, named `RestoreViewOnCreateController` has been added with a different `onCreateView` signature, which now includes a saved view state. This will be released shortly.
