### ISSUE TITLE
Master Detail bug - master controller stays visible when detail controller is active (single pane) after rotation

### ISSUE THREAD

**Issue by ZakTaccardi** [bluelinelabs/Conductor#117]
This happens in the demo, which you can't see because the detail controller's background is opaque. Set the master and controller backgrounds to be 2x 50% opacity colors and you'll see them blend together if you do enough rotation fun.

will upload a video of this happening shortly

EDIT: sorry, this doesn't seem to be happening in the demo. But it is in my app, could have something to do with an `EditText` being focused in the `masterController` when a `RouterTransaction` occurs to hide the `masterController` and push the `detailController` to the top.

**Comment by EricKuck** [comment]
I took a few stabs at trying to reproduce this issue and haven't made any progress with it. Any chance you've figured anything else out with this issue? I'd like to jump on a fix if possible.

**Comment by EricKuck** [comment]
Can you try with the latest snapshot? I still haven't able to reproduce your exact issue, but I fixed one that sounds like it might have been the root cause with 812d1f89115a52cc6d00fe4eb3b720aeeace3d23.

**Comment by ZakTaccardi** [comment]
I'll take it for a spin and let you know - thanks!

**Comment by ZakTaccardi** [comment]
I haven't been able to trigger this issue after upgrading from 2.0.1 to 2.0.3

If it re-appears, I will re-open. Thanks!
