### ISSUE TITLE
Is there any mechanism for getting the result of a controller?

### ISSUE THREAD

**Issue by gregpearce** [bluelinelabs/Conductor#119]
Is there any mechanism like Activity.setResult and onActivityResult for Controllers?

Essentially, I want a Controller to be able to post a result Bundle that the Controller that is popped to can choose to receive and act upon. 

I can think of a few ways of wiring this behaviour up (using Singletons / Dagger, possibly even an event bus etc.) but that wouldn't be as elegant as having a parallel to the mechanism used by Activities.

**Comment by sockeqwe** [comment]
See `controller.setTargetController()` and `controller.getTargetController()`

**Comment by gregpearce** [comment]
Very cool. Cheers!
