### ISSUE TITLE
Question about state persistence.

### ISSUE THREAD

**Issue by pozerupo** [bluelinelabs/Conductor#120]
First of all, amazing library, thanks a lot for creating it and sorry for the incoming wall of text, but I really need to contextualize.

I have a very simple App that basically generates images for the users. Whenever the image is loaded, it's displayed to the them and a button appears. 
The main screen was composed of an Activity that hosted a retained Fragment (retained because I wanted to preserve my Presenter across orientation changes), and whenever the user rotated the screen, I simply reloaded the image that was saved in a variable inside my Presenter.

Recently I decided to refactor my App by changing from Fragments to Conductor's Controllers, added a custom Controller Scope for Dagger 2 (so my Presenter would exists as long as my Controller exists) and thought about using a Loader (explained in [this article](https://medium.com/@czyrux/presenter-surviving-orientation-changes-with-loaders-6da6d86ffbbf#.43xcokc66)) to preserve my Presenter across orientation changes. 

But reading Conductor's README, it's noted that states are persisted, so I wonder: Do I need to bother with the Loader pattern to preserve my presenter across orientation changes?

**Comment by sockeqwe** [comment]
You can think of a  `Controller` as a retaining Fragment. So Controller survive screen orientation changes per default. Therefore you don't need a retaining Fragment or Loader or Dagger scope just to keep your Presenter alive.

**Comment by pozerupo** [comment]
Thanks for the quick reply, I appreciate it.
