### ISSUE TITLE
Bug: Activity leak when more than 1 Controller is on the back stack

### ISSUE THREAD

**Issue by gregpearce** [bluelinelabs/Conductor#121]
I noticed this bug in the demo app today thanks to Leak Canary.
If I go to a Controller demo where I can navigate deeper than 1 controller then when I trigger a configuration change the Activity is leaked.

Some examples:
Home -> Transition Demos -> Click fab -> Rotate screen
Home -> Navigation Demos -> Next Controller -> Rotate screen
Home -> Multiple Child Routers -> Next Controller -> Rotate screen

**Comment by gregpearce** [comment]
I had a quick investigation into this and I'm starting to think it might not be a bug with Conductor, and perhaps it's just Leak Canary being too eager. The "leak" happens on my genymotion emulators (Nexus 6 API 22 and Nexus 5X API 23) and real device (OnePlus 3 API 23) but not on my Android studio virtual device (Nexus 5X API 24). 
However, it doesn't happen when I put breakpoints in the code and step through.

**Comment by shvelo** [comment]
Leak happens on my Nexus 5 too:

```
ContentObserver$Transport.mContentObserver
references PhoneWindow$SettingsObserver.this$0
references PhoneWindow.mLayoutInflater
references PhoneLayoutInflater.mPrivateFactory
leaks MainActivity instance
```

**Comment by EricKuck** [comment]
Is there any chance 112089643811afb72048a8b06e684b04f2495772 fixes this for you? It hasn't made it to the master branch yet, but this fixed all the Leak Canary false-positives I'd seen.

**Comment by gregpearce** [comment]
Just tested and it's still happening for me

**Comment by EricKuck** [comment]
This should definitely be fixed now after b8bd64e07816c65c277aafed5a008c5a1d8e649c and e4f7e9e175bc061b4f5351f915e43bba4f9bf06b. Can someone confirm?

**Comment by gregpearce** [comment]
Just pulled the latest code and tested it - it's fixed for me

**Comment by EricKuck** [comment]
Woo, finally. Thanks!

**Comment by hannesstruss** [comment]
@EricKuck quite some fixes on develop – maybe time for a minor release? :)

**Comment by EricKuck** [comment]
Just pushed 2.0.2!
