### ISSUE TITLE
Replacing a controller which uses removesViewOnPush

### ISSUE THREAD

**Issue by gabrielittner** [bluelinelabs/Conductor#124]
Let's say we have 3 controllers A, B and C. A is the root, B always has `removesViewOnPush = false` and C always has `removesViewOnPush = true`.
When your current backstack A, B and you call `setBackstack()` with A and C, the view of A is not removed. Same thing happens when you use `replaceTopController()` instead of `setBackstack()` to replace B with C.

**Comment by EricKuck** [comment]
I'm seeing this when I use `replaceTopController()`, but not when I use `setBackstack()`. Happen to have a demo project I could use to check it out from `setBackstack()`?
