### ISSUE TITLE
ControllerPagerAdapter shows blank screen on reattach

### ISSUE THREAD

**Issue by Serpentos** [bluelinelabs/Conductor#125]
Hi, first time submitting in GitHub so excuse my formalities. I'd like to first say this is a wonderful library that I'll be reusing in the future so thanks for making it.

With that said, my issue is that ControllerPagerAdapter shows up blank upon refresh.

I have the boolean saveControllerState set to true. I also extended my adapter so that it would store a list of data models used by each controller. I logged the list of data models upon refresh and they maintain their state just fine so it seems to be a redrawing issue (?).

**Comment by EricKuck** [comment]
I set `saveControllerState` to true in the demo app and wasn't able to reproduce your issue. Do you know any other steps I should follow to get this to happen?

**Comment by Serpentos** [comment]
Oops, it seems to be a mistake on my part. Sorry about that.

I had the container controller unbind via Butterknife during onDestroyView() which would unbind ViewPager, thus requiring me to set adapter again on refresh. Fixed it and now ControllerPagerAdapter works fine.

**Comment by EricKuck** [comment]
Great, thanks for the update!
