### ISSUE TITLE
Trouble with onActivityResult

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bluelinelabs/Conductor#13]
I am having trouble with the `onActivityResult` callback in my controller. Before 1.1.0 it was running fine, but after it, when it gets called back, my views' references are null. 

I've noticed my `onDestroyView` gets called before the callback gets called. A workaround is to make my Controller `RETAIN_DETACH`, but not sure this is what I wanted in the first place. 

I am using the speech to text API through intents. So, I guess that to reproduce the issue you can simply:

```java
final Intent intent = new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);
intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE, "en");
startActivityForResult(intent, REQ_CODE_SPEECH_INPUT); // any constant value you want
```

My callback is like:

```java
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {

    if (requestCode == REQ_CODE_SPEECH_INPUT
            && resultCode == Activity.RESULT_OK
            && data != null) {

        final ArrayList<String> result = data
                .getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);

        // Just displaying the results
        spokenText.setText(spokenText.getText().toString() + " " + result.get(0));
    }
}
```

Any help is appreciated :)

**Comment by EricKuck** [comment]
Indeed, this is an issue with the latest version (same issue with #12). I'm looking into it now and should have a fix tomorrow morning. Sorry about that!

**Comment by cs-victor-nascimento** [comment]
Don't worry about that! It is a really nice library :) I will close this one then since it was already reported.
