### ISSUE TITLE
getRootController()

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#130]
I find myself over and over repeating these lines of code

```java
summaryRouter.getBackstack()
            .get(0)
            .controller();
```

It would be great to have a method `getRootController`in analogy to `hasRootController`.

**Comment by sirvon** [comment]
I'm still in early days in this awesome library...
Can you tell me what that snippet does?
and why you use it so often...

**Comment by PaulWoitaschek** [comment]
Well hasRootController returns if there is a root controller. 
So my suggestion is to add a method to return the root controller.

**Comment by EricKuck** [comment]
`hasRootController` exists to inform the developer whether or not any controllers exist in a given router. What's the use case for needing to directly access the root controller in this way?

**Comment by PaulWoitaschek** [comment]
I habe controller which displays a scrollview in which is a list of multiple cardviews. There is a (child) controller for each if these Cards which each container fairly complicated logic. 
The base controller acts as the coordinating element which shows a global loading state based on the different child controllers.
Therefore a reference to the root controller of each route r had to be obtained.

**Comment by EricKuck** [comment]
If you're doing controller->controller communication, would the `setTargetController()` and `getTargetController()` methods perhaps be a better fit? That way if you ever decide to refactor your app you don't have such tight coupling between controllers and their positions on the backstack.

If there's a parent/child relationship to these controllers, calling `getParentController()` could also fit your needs.

**Comment by PaulWoitaschek** [comment]
As my child controllers expose various `rx.Observable` its more a parent->communication.

I don't know how other people use conductor but getting the root controller of a router is something I need to do quite often.

**Comment by EricKuck** [comment]
If it's parent->child communication, then wouldn't using `setTargetController()` be exactly what you're looking for? 

Being able to inspect a router's backstack is only there for synthesizing backstacks (for the purposes of deep linking and such), not to create a way for controllers to talk to other arbitrary controllers. Assuming that the controller in a certain position of a router is the one you want to send a message to seems awfully fragile to me.

**Comment by PaulWoitaschek** [comment]
If I understand correctly targetController is only for a single controller. As I have multiple child controllers that won't work. 

However what I'm doing now is to use tags to find the controllers. So this is not really necessary.

**Comment by EricKuck** [comment]
It would still work with multiple child controllers. The parent creates the children, then calls `setTargetController` on each one. When the child needs to communicate back to the parent, it calls `getTargetController`.

**Comment by 1gravity** [comment]
I wouldn't communicate directly between parent and child controllers but use reactive patterns (you already seem to use rx anyway). E.g. child controller 1 state changes -> update a view model / model -> emits an event, parent controller listens to event flow from the view model and does whatever it needs to do. That way the controllers are decoupled from each other.

**Comment by pro100svitlo** [comment]
@EricKuck  thanks for this (https://github.com/bluelinelabs/Conductor/issues/130#issuecomment-253011228)

but how it can be provided within **RouterPagerAdapter** ?
I mean it is easy to set targetController when you create pages manualy, but how to do it when the state rectreates and **configureRouter** not called?
