### ISSUE TITLE
Lint warning on mandatory constructor?

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#134]
Currently I'm suppressing every single lint warning for constructor that takes a Bundle and calls super(bundle).

That is because Lint does not understand that conductor uses reflection to find the constructor.
Is it possible to use annotation processing so conductor can find the constructors at compile time?
That would also eliminate reflection (which is generally a good idea) and as a sideffect would stop lint from tripping because it could now see the generated code.

**Comment by EricKuck** [comment]
I'm not sure I understand. Is lint reporting false-positives? Or do you not have either `MyController()` or `MyController(Bundle)` constructors in your controllers? If there are false positives, can you provide a bit more detail?

I believe that adding an annotation processor for this small purpose is overkill. The reflection is a non-issue, as it's only used to re-create your controllers when Android kills your process. At the same time Conductor is using reflection to create a small handful of controllers, Android itself is using reflection to create a ton of views.

**Comment by PaulWoitaschek** [comment]
I didn't measure. It's there any performance impact?

About the lint warning: is suggests to make my bundle constructor private.

**Comment by nomisRev** [comment]
I don't think reflection is a problem here. Annotation processing would be useful if you could make it so to use constructor injection with dagger. But that's impossible as far as I know. Because on recreation of the controllers Conductor won't be able to resolve the dependencies.

Is this still a problem btw? Because I don't have any lint warnings anywhere.

**Comment by PaulWoitaschek** [comment]
It's not so important
