### ISSUE TITLE
java.util.ConcurrentModificationException after remove listener in any callback of LifecycleListener

### ISSUE THREAD

**Issue by fedoretskn** [bluelinelabs/Conductor#137]
If remove lifecycleListener from any of callbacks of LifecycleListener, app crashes with ConcurrentModificationException because in loops for invoking callbacks you are using lifecycleListeners member variable.
Example 
`for (LifecycleListener lifecycleListener : lifecycleListeners) {
       lifecycleListener.postDestroyView(this);
}`
https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/Controller.java#L798

Maybe you should create copy of listeners before loop and use this copy of listeners list..

**Comment by EricKuck** [comment]
Excellent catch! This is now fixed in cf6837a41a756f1997075f0998c1eb7a54d46b1c. Thanks.
