### ISSUE TITLE
bindToLifecycleSingle() & bindToLifecycleCompletable

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#139]
It would be great to have lifecycle transformers for rx.Single and rx.Completable too.

**Comment by yshrsmz** [comment]
[`LifecycleTransformer`](https://github.com/trello/RxLifecycle/blob/6d86c593ea42b567bdd642d3eb8dfc2a93c5f549/rxlifecycle/src/main/java/com/trello/rxlifecycle/LifecycleTransformer.java) has `forSingle()` and `forCompletable()`. 
So you can do `bindToLifecycle().forSingle()` or `bindToLifecycle().forCompletable()`

**Comment by PaulWoitaschek** [comment]
Yes, saw that like 5 seconds ago and came back here to close the issue ;-)
