### ISSUE TITLE
CircularRevealChangeHandler for below API levels than 21

### ISSUE THREAD

**Issue by adnbsr** [bluelinelabs/Conductor#14]
Is that nice to implement `ViewAnimationUtils` for lower APIs as [here](https://github.com/ozodrukh/CircularReveal/blob/master/circualreveal/src/main/java/io/codetail/animation/ViewAnimationUtils.java)?

**Comment by EricKuck** [comment]
Looking back I probably shouldn't have even included CircularRevealChangeHandler in the core project, as it's ancillary to what Conductor is made to do. I'll probably be removing this one in the next version. 

ControllerChangeHandlers are meant to be easy to create, so it shouldn't be too hard to copy the CircularRevealChangeHandler code and use a compatibility library like the one you linked. I updated the demo app to use the circular reveal animation on API >= 21 and a simple fade on API < 21, as I didn't want to add any 3rd party dependencies.

**Comment by EricKuck** [comment]
Quick update: The CircularRevealChangeController class has indeed been pulled out of the core project. The source is still available in the demo app for anyone who wants to use it.
