### ISSUE TITLE
Illegal State Exception

### ISSUE THREAD

**Issue by prashermanas** [bluelinelabs/Conductor#140]
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4212)
       at android.view.ViewGroup.addView(ViewGroup.java:4065)
       at android.view.ViewGroup.addView(ViewGroup.java:4010)
       at android.view.ViewGroup.addView(ViewGroup.java:3986)
       at com.bluelinelabs.conductor.changehandler.TransitionChangeHandler.getTransition(SourceFile:75)
       at com.bluelinelabs.conductor.ControllerChangeHandler.performChange(SourceFile:165)
       at com.bluelinelabs.conductor.Router.getActivity(SourceFile:632)
       at com.bluelinelabs.conductor.Router.getActivity(SourceFile:572)
       at com.bluelinelabs.conductor.Router.getActivity(SourceFile:214)
       at com.bluelinelabs.conductor.Router.popToRoot(SourceFile:203)

**Comment by leonardo2204** [comment]
Post your code snippet where this is happening, please.

**Comment by prashermanas** [comment]
This is happening on Activity onBackPressedMethod

@Override
    public void onBackPressed() {
        if (!mainPresenter.onBackPressed() && !router.handleBack()) {
            super.onBackPressed();
        }
    }

where
public boolean onBackPressed(){
    router.popToRoot();
}

**Comment by leonardo2204** [comment]
Where do you set your root controller ?
You should have something like this:

```java
if(!parentRouter.hasRootController())
            parentRouter.setRoot(RouterTransaction.with(new LoginController()));
```

**Comment by prashermanas** [comment]
yeah i do that i set the root controller in the Activity

`router = Conductor.attachRouter(this, view,bundle );`

`        if (!router.hasRootController()) {`

           RouterTransaction routerTransaction = RouterTransaction.with(new XYZController());
           routerTransaction.tag("XYZ");
            router.setRoot(routerTransaction);
        }`

**Comment by EricKuck** [comment]
There's obviously a lot of important code you're not posting. In what you've shown, you never set a `ControllerChangeHandler`, but in the stacktrace you're using a `TransitionChangeHandler`, which is not the default. Please post more details. There's nothing to go on here.

**Comment by prashermanas** [comment]
Well this is the only way i set my XYZ controller as a root controller there is no transition handler i am using and while calling router.popToRoot() and by looking into the conductor code when i call pop to root it is supplied by null change handler.

**Comment by EricKuck** [comment]
You have to be setting that change handler somewhere. It is never the default, since it only works on Android 5.0 and above.

**Comment by prashermanas** [comment]
Okay so there is one controller like ABC COntroller

RouterTransaction routerTransaction = RouterTransaction.with(new AbcController())
                    .popChangeHandler(new AutoTransitionChangeHandler())
                    .pushChangeHandler(new AutoTransitionChangeHandler())
                    .tag("ABC");

So i think when i popToRoot()  to XYZController on backpressed it will automatically have AutoTransitionChangeHandler() right ??

**Comment by EricKuck** [comment]
Yep, that's right. I'm guessing your root controller is somehow left attached to the window no matter what?
