### ISSUE TITLE
if addFlags(WindowManager.LayoutParams.FLAG_SECURE) before setContentView

### ISSUE THREAD

**Issue by huangwenyan1225** [bluelinelabs/Conductor#143]
how do I clear the flags？finish the Activity？

**Comment by EricKuck** [comment]
This seems like a general Android question, not a Conductor issue. Am I missing something?

**Comment by PaulWoitaschek** [comment]
@huangwenyan1225 A good place for such questions is [Stackoverflow](http://stackoverflow.com/)
