### ISSUE TITLE
Shared Elements Animations

### ISSUE THREAD

**Issue by sirvon** [bluelinelabs/Conductor#144]
is it possible to do shared element animations between controllers?

**Comment by PaulWoitaschek** [comment]
Yes, you can use the transition framework.

See [here](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/develop/audiobook/src/main/java/de/ph1b/audiobook/uitools/BookTransition.kt), I'm animating the cover and FAB from book shelf to play screen.

**Comment by Pedramrn** [comment]
@PaulWoitaschek Your link has broken.

**Comment by PaulWoitaschek** [comment]
@Pedramrn link fixed

**Comment by hannesstruss** [comment]
@Pedramrn there's also an example for a shared element transition in the [demo app](https://github.com/bluelinelabs/Conductor/tree/develop/demo).
