### ISSUE TITLE
ViewPager-to-RecyclerView Shared Element Transition weird behaviors

### ISSUE THREAD

**Issue by Serpentos** [bluelinelabs/Conductor#146]
**Context:**
- I have a ListController containing a ViewPager which contains Controllers. Each Controller has a CardView (shared element).
- I also have a DetailController containing a RecyclerView which contains a HeaderViewHolder.
- Upon clicking the **CardView**, it should move and resize**from the Controller onto the HeaderViewHolder.** Note: The click also passes a Model object which the HeaderViewHolder binds.
- I'm using the Demo's ArcFadeMoveChangeHandler.

I'm been trying to learn transitions. The problem is I'm getting some weird behaviour from ViewPager. It's hard to articulate without visuals but I'll try anyway...

**Weird Occurrence A:**

In the ChangeHandler's code below, when I put addTarget(R.id.cardView) onto the **Move transition (2nd transition) to move the shared element, it is ignored and instead just runs the Fade Out transition (1st) & the Fade In transition (3rd) for the entire View hierarchy.** If I setTransitionName for each Controller & for the HeaderViewHolder while using addTarget(transitionName) instead, it is still not detected.

```
protected Transition getTransition(@NonNull ViewGroup container, View from, View to, boolean isPush) {
        TransitionSet transition = new TransitionSet()
                .setOrdering(TransitionSet.ORDERING_SEQUENTIAL)
                .addTransition(new Fade(Fade.OUT))
                .addTransition(new TransitionSet()
                        .addTarget(R.id.cardView) // or addTarget(transitionName) -- Does not move shared element. Just fades the entire View hierarchy instead.
                        .addTransition(new ChangeBounds())
                        .addTransition(new ChangeClipBounds())
                        .addTransition(new ChangeTransform()))
                .addTransition(new Fade(Fade.IN));

        transition.setPathMotion(new ArcMotion());

        return transition;
    }
```

**Weird Occurrence B:**

Just for testing's sake, I put addTarget(R.id.cardView) onto the outer TransitionSet, **it moves the shared element, but the move occurs immediately while ignoring the fading transitions for the rest of the hierarchy.** This looks ugly. Also, since each ViewPager Controller's CardView id is the same, the CardView moves only from the 1st Controller's location. This means **if I click the one of the other Controllers in the ViewPager, the CardView comes out from the left instead of from its expected spot.**

```
protected Transition getTransition(@NonNull ViewGroup container, View from, View to, boolean isPush) {
        TransitionSet transition = new TransitionSet()
                .setOrdering(TransitionSet.ORDERING_SEQUENTIAL)
                .addTransition(new Fade(Fade.OUT))
                .addTransition(new TransitionSet()
                        .addTransition(new ChangeBounds())
                        .addTransition(new ChangeClipBounds())
                        .addTransition(new ChangeTransform()))
                .addTransition(new Fade(Fade.IN));

        transition.addTarget(R.id.cardView) // Does move shared element, but ignores fading transitions. Moves from the first Controller's spot even if you click other Controllers

        transition.setPathMotion(new ArcMotion());

        return transition;
    }
```

Using addTarget(transitionName) instead of id just makes it weirder as it only **detects the fading transitions but applies this only for the CardView while ignoring the rest of the View hierarchy.**

**Normal Occurrence (For Testing):**

To test if this weird behaviour is specific to the ViewPager, I created a dummy CardView inside of ListController instead of ViewPager so the transition would be ListController-to-RecyclerView. I put addTarget(R.id.cardView) onto the move transition just like I did on Weird Occurrence A, and what do you know, it works properly. It fades out the view hierarchy, moves the shared element, and fades in.

**Question:**

So it seems the problem is specific to the ViewPager. Is there anyway I can fix this issue so that the shared element can move properly from the ViewPager-to-RecyclerView while also fading out and in the rest of the view hierarchy?

Edit:
If it's of any help, the ViewPager Controllers are not full screen and [look like this.](https://rubensousa.github.io/2016/08/viewpagercards) Also the DetailController is pushed on the same Router as the ListController (rather than in a ChildRouter of a ViewPager Controller).

**Comment by Serpentos** [comment]
** New Information: **

So it seems I did not properly setTransformationName() uniquely for each Controller's CardView and for the RecyclerView's HeaderViewHolder. I'm now set that up and it's now detecting the target I added on move[2nd] transition (Refer to Weird Occurrence A).

But the thing is it only blinks rather that moves. I've debugged this and it appears that the ChangeHandler's performChange() method is being called before the RecyclerView's onBindViewHolder() method.

**Currently, trying to figure out how to postpone performChange() until RecyclerView's HeaderViewHolder is binded. Any help?**

**Comment by MFlisar** [comment]
I do it like following:

* sub class the recycler view
* add a listener like an `IOnDataReadyListener` to this subclass
* make sure your adapter notifies this listener whenever it binds a view
* your change handler creates a listener and can add this listener to the view (your custom recycler view) and starts the animation depending on this listener

**Comment by Serpentos** [comment]
Okay so from what I understand, inside performChange(), I add the toView to the container via container.addView(to). Then I set the listener to the toView and create an anonymous inner class. Now I'm stuck. 

**What methods do you use to achieve the transition effect?**

I tried TransitionManager.beginDelayedTransition() just like the TransitionChangeHandler except instead of adding the toView, I changed its visibility from INVISIBLE to VISIBLE. Then I removed the fromView. It doesn't seem to work as the shared element isn't moving.

**Comment by Serpentos** [comment]
**Begin Transition Solution:**

To listen to the RecyclerView load its data, I had to call `container.addView(to)` then set a listener to the 'to' view's RecyclerView. The problem with this is that I can't immediately call `addView(to)` again during `TransitionManager.beginDelayedTransition()`.

I solved the problem above by calling `((ViewGroup) to.getParent()).removeView(to)` before beginning the Transition, so that I can call `addView(to)` again as shown below. _Note:_ You could probably just call`container.removeView(to)` instead (I didn't because I wanted to distinguish the line of code). _Another Note:_ `container.removeAllViews()` doesn't work for whatever reason.

        ...

        if (to != null) {
            ((ViewGroup) to.getParent()).removeView(to); // Called before beginning transition
        }
        TransitionManager.beginDelayedTransition(container, transition);
        if (from != null) {
            container.removeView(from);
        }
        if (to != null) {
            container.addView(to);
        }

 Now the above creates a new problem because calling removeView(to) does not retain the view when you add it again. You can simply solve this by calling `setRetainViewMode(RetainViewMode.RETAIN_ATTACH)` in that view's controller.

---

**Fade Transition Conflict Solution:**

In the Weird Occurences, I explained how the Fade transition seems to conflict with the Move transition. I solved this by **explicitly calling addTarget()** to the all the other Views that I wanted to Fade. It seems you have to do this when complex views like the ViewPager are involved. I also changed the order to `ORDERING_TOGETHER` as it seemed to look ugly when sequential.
