### ISSUE TITLE
[Suggestion/Idea] DataBinding and animations

### ISSUE THREAD

**Issue by MFlisar** [bluelinelabs/Conductor#147]
The operator `findViewById` is quite slow so I think following should be considered:

A possibility to pass a `DataBinding` to the `ChangeHandler` (instead or additionally to the `View`), probably to the `performChange` function. Any odeas on that?

This would allow to get rid of unecessary `findViewById` calls in the animations and would speed them up a little bit (in case of complex animations this probably is noticeable)

**Comment by PaulWoitaschek** [comment]
As it gets restored you cannot simply keep a reference to the binding.
However you should be able to just manually call `MyBinding binding = MyBinding.bind(view)` and just use it.

**Comment by MFlisar** [comment]
Whenever you have to recreate a `DataBinding` you have to recreate the view as well, so whatever view you pass to the `ChangeHandler` the corresponding `DataBinding` is existing already as well.

As a fast solution, I can always add the `DataBinding` via `view.setTag(...)` and retrieve it in the `ChangeHandler` but I think the controller that passes in the view could be adjusted to pass the binding as well...

Creating the binding in the `ChangeHandler` again has no real benefit I think...

**Comment by EricKuck** [comment]
I think your solution of adding the `DataBinding` as the view's tag is a good one. I don't want to add a dependency on data binding to the core of this library, as I know a lot of people don't, and never will, use it.
