### ISSUE TITLE
RxJava 2 support

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#148]
It would be great to have RxJava2 support.

**Comment by EricKuck** [comment]
Agreed! I probably won't be getting too much exposure to RxJava 2 myself anytime soon, so PRs would be appreciated. If no one can get to it I'll probably try to knock it out over one of the upcoming weekends.

**Comment by PaulWoitaschek** [comment]
How should this be handled? Should there be a new package name for rx2 like Rx handles it itself?

**Comment by hannesstruss** [comment]
> Should there be a new package name for rx2 like Rx handles it itself?

I think something like this makes sense. Transition to RxJava 2 in the community will take time, and RxJava 1 support should not be dropped for now.

**Comment by EricKuck** [comment]
Yeah, I'd say there should be another package too. Personally I have a few small/unimportant projects that I'll likely leave at RxJava 1, but will be using RxJava 2 on all new projects going forward, so I'd like to see both versions available indefinitely.

**Comment by PaulWoitaschek** [comment]
I don't think a .1 branch should be maintained for a longer time.

I am currently using conductor with RxJava 2 which is quite easy due to the [interop library](https://github.com/akarnokd/RxJava2Interop). So I think everyone who wants to use conductor with an outdated version of RxJava should just use the interop library so this project can move forward.

[Here](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/commit/88e018491d9724429ba2e1958254180b5ef9f318#diff-70db71ac97734bfc316d9d4109babc60R20) I just use a base class that exposes a transformer.

**Comment by EricKuck** [comment]
While it's true the interop library is probably a better way to handle this than maintaining both, we can't force developers to update such a large dependency in a point release of this library. You're right - we probably should just have RxJava 2 support, but I don't think we could do that until the next major release of Conductor.

**Comment by EricKuck** [comment]
Tried to take a look at this today and saw the RxLifecycle hasn't been updated with RxJava2 support yet. Looks like it'll be dropping in about a week, so we'll add support for it when that happens.
