### ISSUE TITLE
getCurrentController() possibility?

### ISSUE THREAD

**Issue by zwarm** [bluelinelabs/Conductor#15]
Any chance you can expose a method for getting the current controller?  Or maybe one already exists and I've missed it?

I’m using conductor for a ‘wizard type’ flow and want to simplify things by doing something like:  getCurrentController().onNext() OR getCurrentController().onPrevious, etc.   I noticed that I can peek at the backstack, but it’s a private package so I can’t get a reference to it.

Thoughts or possibilities? 
Thanks for the awesome work.

**Comment by sockeqwe** [comment]
Do you mean something like target controller?
https://github.com/bluelinelabs/Conductor/blob/develop/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/TargetTitleEntryController.java#L42

**Comment by zwarm** [comment]
Not exactly because I want to access to the current controller from an Activity not a controller.  What I have done is set a changeListener on the router & capture the "Controller to" instanceId and hold onto that value.  I then use that instanceId in router.getControllerByInstanceId() and grab the current controller.  It works for my needs, just thought it would be handy to have that method right off of the router instead of managing the current controller manually.  Thanks for the quick response.

**Comment by sockeqwe** [comment]
I would expect to have one controller for the whole "wizard" screen which has child controllers for each "page" ...

**Comment by EricKuck** [comment]
I'm not exactly sure how this wizard is being used, but I'd tend to agree with Hannes that I'd expect there to be a wizard controller that would have child controllers for the pages (possibly in a non-swipeable viewpager?). That way your activity implementation stays pretty light, as all it really has to do is setup the router.

If for whatever reason this doesn't work for your use case, your method of listening for controller changes and accessing them that way is probably the way to go. It wouldn't be hard to make the router's backstack accessor public, I just worry that this would end up getting abused. There may be some legitimate uses for accessing the backstack, but I feel like the vast majority of reasons people would want to do this would be pretty hacky.

**Comment by zwarm** [comment]
The wizard is dynamic - I only know the first controller upfront; everything else is based on user action & dynamic business rules.  I actually switched from a using non-swipeable viewpager with fragments to Conductor because of the hassle of "truly" removing fragments on the fly. Conductor works beautifully for my needs; even provides a nice way to get back into the pipeline when moving backwards.  I didn't explore using a single controller with child controllers, but I suppose it would work the same way & perhaps that is the better way approach this.  I agree with Eric though, I don't think exposing the backstack would be appropriate; hence the suggestion for just a single method to grab the current controller.  No biggie, I have a solution now & possibly a refactor in the future. Thanks for the input.
