### ISSUE TITLE
Reattach view after rotation (if removesFromViewOnPush = false) not working

### ISSUE THREAD

**Issue by MFlisar** [bluelinelabs/Conductor#152]
If I show two controllers in the same container and add the first one like following:

    if (!mRouter.hasRootController())
	{
		mRouter.setRoot(RouterTransaction
				.with(new MainController())
				.pushChangeHandler(new SimpleSwapChangeHandler(false))
				.popChangeHandler(new SimpleSwapChangeHandler(false))));
	}

And then I add the second controller like following:

     mRouter
		.pushController(RouterTransaction
				.with(viewerController);

I would expect, that after rotating, both controllers get attached. Am I understanding this wrong?

**Comment by EricKuck** [comment]
In your example, you're setting `removesFromViewOnPush` to false in the wrong change handler. It needs to be added to the `RouterTransaction` that's used to push your `viewerController`. That parameter determines whether or not the _previous_ view will be removed, not whether its own view can ever be removed.

**Comment by MFlisar** [comment]
Thanks. Now it's working as expected.
