### ISSUE TITLE
[QUESTION] How to "emulate ViewFlipper" with conductor?

### ISSUE THREAD

**Issue by StephanSchuster** [bluelinelabs/Conductor#156]
I have a scenario much like your master/detail sample in landscape mode:

I have a "MainController" whose view has a group of 5 radio buttons and a child container into which the according child controller should be rendered upon button click. But in this special case I want neighter the child controllers nor their views to be destroyed when I change the active child controller (like ViewFlipper). How can I achieve this with conductor? Or is this something that should just not be done???

My current solution:
As far as I understand, a controller which is not in the backstack of a router always gets destroyed on pop - regardless of  "setRetainViewMode()". Right? So first I need to get all of the 5 child controllers to the router attached to the child container of my "MainController". Currently I do this by initially calling getChildRouter(...).pushController(...) for each of my 5 child controllers. Upon button click I call getChildRouter(...).getBackstack(), change the result list to have the new active controller on the end, and call getChildRouter(...).setBackstack(<modified list>). Furthermore I need to ensure that none of my 5 child controllers is popped when clicking the native back button. So I override MainController.handleBack() and delegate this to <active child controller>.handleBack(). As a last step I set RetainViewMode.RETAIN_DETACH for each of my 5 child controllers. Now on button click there is only attach/detach called for each child controller. So it seems to work. But is there a better way to achieve this behaviour???

By the way: when I initialize the MainController with getChildRouter(...).setBackstack(5 x child controller) instead of getChildRouter(...).pushController(...) for each of my 5 child controllers, the internal "childBackstack" variable in Controller.java seems to be wrong. It just contains the last entry of the backstack list, not the full list. This seems like a bug to me. However, this is not really relevant for my use case because I override handleBack() anyway.

**Comment by stephanschuster** [comment]
I wrapped my current solution into an abstract base class:

```
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.text.TextUtils;

import com.annimon.stream.Stream;
import com.bluelinelabs.conductor.Controller;
import com.bluelinelabs.conductor.ControllerChangeHandler;
import com.bluelinelabs.conductor.Router;
import com.bluelinelabs.conductor.RouterTransaction;

import java.util.List;

public abstract class SwitchController extends BaseController {

    private Router mChildRouter;

    protected SwitchController() {
    }

    protected SwitchController(Bundle args) {
        super(args);
    }

    protected void init(@NonNull Router childRouter, @NonNull Controller... childControllers) {
        init(childRouter, Stream.of(childControllers).map(RouterTransaction::with).toArray(RouterTransaction[]::new));
    }

    protected void init(@NonNull Router childRouter, @NonNull RouterTransaction... routerTransactions) {
        if (mChildRouter != null) {
            throw new RuntimeException(getClass().getSimpleName() + " has already been initialized");
        }
        mChildRouter = childRouter;
        for (RouterTransaction routerTransaction : routerTransactions) {
            mChildRouter.pushController(routerTransaction);
        }
    }

    protected Controller getActiveController() {
        if (mChildRouter == null) {
            return null;
        }

        List<RouterTransaction> backstack = mChildRouter.getBackstack();
        if (backstack.isEmpty()) {
            return null;
        }

        return backstack.get(backstack.size() - 1).controller();
    }

    protected boolean setActiveController(Class<? extends Controller> childControllerType) {
        return setActiveController(childControllerType, null, null);
    }

    protected boolean setActiveController(Class<? extends Controller> childControllerType, ControllerChangeHandler changeHandler) {
        return setActiveController(childControllerType, null, changeHandler);
    }

    protected boolean setActiveController(String routerTransactionTag) {
        return setActiveController(null, routerTransactionTag, null);
    }

    protected boolean setActiveController(String routerTransactionTag, ControllerChangeHandler changeHandler) {
        return setActiveController(null, routerTransactionTag, changeHandler);
    }

    protected boolean setActiveController(Class<? extends Controller> childControllerType, String routerTransactionTag) {
        return setActiveController(childControllerType, routerTransactionTag, null);
    }

    protected boolean setActiveController(Class<? extends Controller> childControllerType, String routerTransactionTag, ControllerChangeHandler changeHandler) {
        if (mChildRouter == null || (childControllerType == null && routerTransactionTag == null)) {
            return false;
        }

        List<RouterTransaction> backstack = mChildRouter.getBackstack();

        int newActiveIndex = -1;
        int oldActiveIndex = backstack.size() - 1;
        for (int i = oldActiveIndex; i >= 0; --i) {
            RouterTransaction routerTransaction = backstack.get(i);
            if (childControllerType != null && !childControllerType.isInstance(routerTransaction.controller())) {
                continue;
            }
            if (routerTransactionTag != null && !TextUtils.equals(routerTransactionTag, routerTransaction.tag())) {
                continue;
            }
            if (i != oldActiveIndex) {
                newActiveIndex = i;
            }
            break;
        }

        if (newActiveIndex != -1) {
            backstack.add(backstack.remove(newActiveIndex));
            mChildRouter.setBackstack(backstack, changeHandler);
            onActiveControllerChanged();
            return true;
        }

        return false;
    }

    protected void onActiveControllerChanged() {
    }

    @Override
    public boolean handleBack() {
        Controller activeController = getActiveController();
        return activeController != null && activeController.handleBack();
    }

}
```

Any comments from the experts?

**Comment by EricKuck** [comment]
If I was building this, I think I'd do it a different way for simplicity's sake. What I'd recommend is that you have 5 overlapping container views that you simply set the visibility on when switching. All container views would be `View.GONE` except for the one you're interested in. Each of these container views would have their own routers and backstacks.

Would that meet your needs? Is there a downside to this approach?

**Comment by EricKuck** [comment]
BTW, the issue you mentioned towards the bottom of your post was just fixed by 96e068d34895690427ad3e904ab1fc72bfd0d777. Thanks for letting me know about that one!

**Comment by stephanschuster** [comment]
Initially I had the same idea (View.Gone). But I didn't want to implement it like this because of the following reasons:

1. I would loose the ChangeHandler animations/transitions on switching (slide, fade, ...). Right?
2. In case I do not know the number of items beforehand, I would have to generate the containers dynamically.
3. All together it just doesn't feel like "the conductor way"

**Comment by stephanschuster** [comment]
Do you see any issues with my approach ("SwitchController")?

**Comment by stephanschuster** [comment]
BTW: Thanks for fixing this so quickly. Perfect! I'll try it.

**Comment by hannesstruss** [comment]
> I would loose the ChangeHandler animations/transitions on switching (slide, fade, ...). Right?

@stephanschuster You could roll your own animations – in the simplest case, `TransitionManager.beginDelayedTransition(containerOfTheOverlayingViews);` before changing the visibility would do the trick (or look into [TransitionsEverywhere](https://github.com/andkulikov/Transitions-Everywhere) if you're targeting older Android versions).
