### ISSUE TITLE
Restore state after rotation

### ISSUE THREAD

**Issue by MFlisar** [bluelinelabs/Conductor#162]
I know, the controller may be retained and that's fine but after screen rotation it will rebind it's views in on `onCreateView`. So `onRestoreInstanceState` is not called, which makes sense and is fine as well.

But how or where can I detect that a screen rotation has taken place? I'm doing a few things in my custom `ChangeHandler` and this not called after screen rotation, so I need to restore my view state after screen orientation manually.

**Comment by PaulWoitaschek** [comment]
It's called `onRestoreViewState`

**Comment by MFlisar** [comment]
Thanks

**Comment by PaulWoitaschek** [comment]
Also check [this thread](https://github.com/bluelinelabs/Conductor/issues/10#issuecomment-252174643). I tried to start a discussion about the too simplified lifecycle diagram. There you'll find a better diagram that should get rid of the confusion.

![diagram](https://cloud.githubusercontent.com/assets/2039026/14220653/16a8685e-f827-11e5-8ffb-7e847144d164.jpg)
