### ISSUE TITLE
@NonNull missing in Controller.onDestroyView(View view)

### ISSUE THREAD

**Issue by stephanschuster** [bluelinelabs/Conductor#164]
According to
```
protected void onAttach(@NonNull View view) { }
protected void onDetach(@NonNull View view) { }
...
```
we should also have
```
protected void onDestroyView(@NonNull View view) { }
```

The null check is already done in `removeViewReference()`

**Comment by EricKuck** [comment]
This was actually fixed in 104d96e6e2c370b1b037d373f9888b777d1dd46d and should be pushed as a main release shortly. Thanks!
