### ISSUE TITLE
No way to retrieve an existing controller from ControllerPagerAdapter

### ISSUE THREAD

**Issue by hzsweers** [bluelinelabs/Conductor#166]
I've got a situation where I'm looking to get a reference to one of the existing controllers in the pager adapter (during `onTabReselected()`, but currently the only means to get a controller is to call `getItem()`, which actually creates a new one in most implementations. Would it be reasonable to add an API to `ControllerPagerAdapter` to allow for getting an item and letting it decide to call through to `getItem()` or error if it doesn't exist yet?

**Comment by AranHase** [comment]
You could try overriding the `intantiateItem(...)` method. Here is what I'm using and seems to work fine.

```
class MyAdapter(host: Controller) : ControllerPagerAdapter(host, false) {

    val controllersCache = SparseArray<Controller>() // get the controllers from here

    override fun instantiateItem(container: ViewGroup?, position: Int): Any {
        val controller = super.instantiateItem(container, position)
        controllersCache.put(position, controller)
        return controller
    }

    override fun destroyItem(container: ViewGroup?, position: Int, obj: Any?) {
        controllersCache.remove(position)
        super.destroyItem(container, position, obj)
    }
}
```

**Comment by hzsweers** [comment]
While that works, we're now maintaining a separate cache that mirrors the internal one

**Comment by EricKuck** [comment]
What would you expect the API of this to look like? Would there just be some kind of `getExistingControllerOrNull(page: Int)` method?

**Comment by PaulWoitaschek** [comment]
Yes, just a `fun getController(position: Int) : Controller`

**Comment by PaulWoitaschek** [comment]
Works great; thank you!

**Comment by hzsweers** [comment]
Thanks!
