### ISSUE TITLE
[QUESTION] How to implement multi-level deep linking

### ISSUE THREAD

**Issue by tmtron** [bluelinelabs/Conductor#169]
I'm trying to add multi-level deep linking to the demo app.

for example the url `"http://bluelinelabs.com/demo/MULTIPLE_CHILD_ROUTERS/1/4"` should navigate first to the MULTIPLE_CHILD_ROUTERS controller, then to it's 2nd child-controller (index=1) and finally to the 5th subcontroller (index 4).

I've got a working solution, but I guess, the way I handle the navigation is not correct (I'm just getting started with Conductor).

Here is a branch in my fork of Conductor where you can see the current state of my tests:
[tmtron/Conductor/deep_links_2ndLevel](https://github.com/tmtron/Conductor/tree/deep_links_2ndLevel)

some explanation:

- the [MainActivity](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/MainActivity.java#L72) will handle the incoming `Intents` and create a [DeepLinkHandler](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/util/DeepLinkHandler.java)
- the [DeepLinkHandler](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/util/DeepLinkHandler.java) is just a small utility class that splits the dataURI of the Intent into parts
- each controller can override [BaseController.handleDeepLinks(DeepLinkHandler)](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/base/BaseController.java#L43) and handle the next dataURI part.

In our example the **first part** `MULTIPLE_CHILD_ROUTERS` will be handled by the [HomeController](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/HomeController.java#L140) :
- interpret it as a string which must match any of the [HomeDemoModel enums](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/HomeController.java#L44)
- navigate tot the corresponding controller
- and finally pass the `deepLinkHandler`

the code for the navigation is currently [like this](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/HomeController.java#L195):
```java
case MULTIPLE_CHILD_ROUTERS:
                BaseController nextController = new MultipleChildRouterController();
                getRouter().pushController(RouterTransaction.with(nextController)
                        .pushChangeHandler(new FadeChangeHandler())
                        .popChangeHandler(new FadeChangeHandler()));
                nextController.handleDeepLinks(deepLinkHandler);
```
The last line of the code above feels wrong: maybe there's a better way to do this?

The **second part** `1` will be interpreted by the [MultipleChildRouterController](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/MultipleChildRouterController.java#L39):
```java
        Integer childContainerIdOrNull = deepLinkHandler.getNextPathItemAsIntegerOrNull();
        ViewGroup childContainerOrNull = getChildContainerOrNull(childContainerIdOrNull);
        if (childContainerOrNull != null) {
            Router childRouter = getChildRouter(childContainerOrNull);
            getRootController(childRouter).handleDeepLinks(deepLinkHandler);
        }
```
since the `MultipleChildRouterController` always shows the 3 child-controllers at the same time, it just has to find the correct `childContainer` and then pass the `deepLinkHandler` to it.

The **third part*** `4` will be handled by the [NavigationDemoController](https://github.com/tmtron/Conductor/blob/deep_links_2ndLevel/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/NavigationDemoController.java#L133):
```java
    @Override
    public void handleDeepLinks(@NonNull final DeepLinkHandler deepLinkHandler) {
        Integer demoControllerIndexOrNull = deepLinkHandler.getNextPathItemAsIntegerOrNull();
        if (demoControllerIndexOrNull == null) return;

        while (true) {
            NavigationDemoController highestNavigationDemoController = getHighestNavigationDemoController();
            if (highestNavigationDemoController.index >= demoControllerIndexOrNull) {
                break;
            }
            highestNavigationDemoController.onNextClicked();
        }
    }
    @OnClick(R.id.btn_next) void onNextClicked() {
        getRouter().pushController(RouterTransaction.with(new NavigationDemoController(index + 1, displayUpMode.getDisplayUpModeForChild()))
                .pushChangeHandler(new HorizontalChangeHandler())
                .popChangeHandler(new HorizontalChangeHandler()));
    }
```
In this case we will push a new controller until we reach the desired index `4`.

Another thing that makes it feel wrong, is that all the views in-between already get created and inflated - maybe that's the ways it should be anyway - or am I doing it wrong?

**Comment by leonardo2204** [comment]
I've given some thought when I first saw your deeplink post, about having synthetic backstack, like [TaskStackBuilder](https://developer.android.com/reference/android/support/v4/app/TaskStackBuilder.html). Actually the Airbnb's [DeepLinkDispatch library](https://github.com/airbnb/DeepLinkDispatch) is an excellent library to handle deeplink, I was analysing their code to see if we could fork and fit it into Conductor's Controllers.
Any thoughts on that also w

**Comment by PaulWoitaschek** [comment]
Router.setBackstack is the way to go (and the way I'm handling deep links).
