### ISSUE TITLE
Facebook integration

### ISSUE THREAD

**Issue by leonardo2204** [bluelinelabs/Conductor#17]
I'm implementing a Facebook login implementation on top of the demo app, but I can't find a way to bind the onActivitityResult from Facebook to my Controller. 
What I have:
```
/**
 * Created by leonardo on 4/11/16.
 */
public class FacebookController extends BaseController {

    @Bind(R.id.login_button)
    LoginButton loginButton;

    private CallbackManager callbackManager;

    @Override
    protected View inflateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
        return inflater.inflate(R.layout.controller_facebook, container, false);
    }

    @Override
    protected void onViewBound(@NonNull View view) {
        super.onViewBound(view);

        callbackManager = CallbackManager.Factory.create();
        loginButton.registerCallback(callbackManager, new FacebookCallback<LoginResult>() {
            @Override
            public void onSuccess(LoginResult loginResult) {
                Toast.makeText(getActivity(), "Logged in !", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onCancel() {
                Toast.makeText(getActivity(), "Canceled by the user!", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onError(FacebookException error) {
                Toast.makeText(getActivity(), "Error:"+ error.getMessage(), Toast.LENGTH_SHORT).show();
            }
        });
        loginButton.setOnClickListener(null);
    }

    @OnClick(R.id.login_button)
    public void onClick(View v){
        LoginManager.getInstance().logInWithReadPermissions(getActivity(), null);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        callbackManager.onActivityResult(requestCode, resultCode, data);
    }

    @Override
    protected String getTitle() {
        return "Facebook SDK Login";
    }
}
```
I realized that in order to get the Activity's lifecycle callbacks I must call the Controller startActivityForResult for instance, but as I'm using Facebook SDK I don't have the control over this.
How should I proceed in that case ?

Thanks

**Comment by EricKuck** [comment]
Ugh, I hate Facebook's SDK. This is a good catch though. We haven't done an app that uses FB login with Conductor yet, so we hadn't come across this. I can't think of a way to make this work off the top of my head, outside of making an external Facebook callback class that both the Activity and Controller can interface with (good use of DI). I don't like this solution very much though and wouldn't want to force people to do things this way.

I'm thinking maybe adding a `registerForActivityResult(int requestCode)` method to the Controller class could address this, but I'll have to give this some thought. Any suggestions?

**Comment by leonardo2204** [comment]
I had this very same idea, to use a `register`, because that way would be easier to keep track of what is getting called outside the `Controller` lifecycle.
The idea of making an external callback for facebook won't scale well, so if you log with Google, Twitter or any other API you'd have to code new wrappers. I think the register solution would be a generic yet an excellent one. 
I'll see if I can come up with something later... If so I'll drop a pull request !!

Thank you very much again !

**Comment by leonardo2204** [comment]
Just passing by again to ask you for a help/review.
I forked the project and came up with some [ugly and quick] code to show my idea of the register.
I didn't have time to test it, I'll do it in the morning.
Please, [check out my fork implementation](https://github.com/leonardo2204/Conductor/commits/develop) !

Thanks again !

**Comment by EricKuck** [comment]
Ah, I just saw this response. Sorry about that. I actually implemented this feature last night too. I haven't pushed the change yet, as I haven't tested it very well. Your Facebook base controller will be useful for seeing how well it works. Thanks!

**Comment by leonardo2204** [comment]
Ohh that's nice ! I'll wait for it then and compare to what I've done and learn :)
If you may, push to another branch and I'll do some testing here ;)

**Comment by EricKuck** [comment]
Your facebook controller was really helpful. I just pushed this update as 1.1.3. There's now a new `registerForActivityResult` method that you can use (probably call it in the constructor). As Facebook's `onActivityResult` method is attached to the host `Activity`, you'll have to add something like this to your activity to ensure the callback reaches your controller:

```
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        router.onActivityResult(requestCode, resultCode, data);
    }
```

**Comment by leonardo2204** [comment]
Nice !
I was thinking about creating a BaseConductor class to handle the onActivityResult but honestly not a big fan to "force" the user to inherit a Base Class  just because of 1 method. Anyway, I think it's better to just document the need of calling the onActivityResult in the Activity lifecycle.

**Comment by EricKuck** [comment]
The 1.1.3 update added a new `onActivityResult` method that does not take the instanceId field. The old method actually wasn't meant to be used externally.

**Comment by leonardo2204** [comment]
Yeah, just realized that !
Thank you, closing !

**Comment by adi1133** [comment]
`LoginClient.getLoginRequestCode()` is private, facebook only lets us use `FacebookSdk.isFacebookRequestCode()` to check if a req code is generated by facebook

`Controller.registerForActivityResult()` takes in a single value, currently the facebook sdk implementation may generate up to 100 different request codes. (100 is implementation dependent, I got this from decompiled code)

Also the facebook sdk launches the intent internally on a fragment or activity
* If launched from the activity, the result is not propagated back to conductor because LifecycleHandler is a fragment and the result is not propagated by AppCompatActivity
* I can not launch it from a fragment because conductor doesn't expose LifecycleHandler

Seems like the facebook sdk for android has some bad api design .... 
How did you guys implement this ?

**Comment by EricKuck** [comment]
Which version of the SDK are you using? `LoginClient.getLoginRequestCode()` isn't private for me. It's right here: https://github.com/facebook/facebook-android-sdk/blob/master/facebook/src/main/java/com/facebook/login/LoginClient.java. 

If it's now private in some version, that's going to really suck to work around. Bad api design is right.

**Comment by adi1133** [comment]
The containing class `LoginClient` is package private, sorry for the misunderstanding. Also nice to see that the fb sdk is open source.
