### ISSUE TITLE
lifecycle

### ISSUE THREAD

**Issue by gerc99** [bluelinelabs/Conductor#175]
When pushing second controller, i have lifecycle:
Controller2 - onViewBound
Controller2 - onAttach
Controller1 - onDetach
Controller1 - onDestroyView
it's wrong and i have problems when unsubscribe/unregister listeners/broadcasts/subscriptions

**Comment by EricKuck** [comment]
And what's the problem you're having?

**Comment by gerc99** [comment]
when open second controller, in the first controller continues to operate and create a subscription bugs

**Comment by EricKuck** [comment]
This is how it's supposed to work. Both are active while the transition
between controllers is occurring.

**Comment by gerc99** [comment]
it's bad, a notice from the first screen go in the second screen, until call a method onDetach/onDestroyView

**Comment by EricKuck** [comment]
What makes it bad? This is how Activities and Fragments work too. I don't
understand what your use case is that makes this undesirable. If your
concern is rx subscriptions, check out the RxLifecycle dependency to handle
unsubscribing for you.

**Comment by gerc99** [comment]
realm listener in the first controller on which depends the title toolbar, when open second controller, I can see the title of the first screen, because it still lives subscribe

**Comment by EricKuck** [comment]
This is an application logic issue, not a library issue. It sounds like you expected it to work a way that it doesn't. Now that you know, why not simply update how it works? Maybe use the `onChangeStarted` callback instead of relying on attached and detached state, since multiple routers can be attached at the same time?

**Comment by gerc99** [comment]
Controller2 - onCreateView
Controller2 - onChangeStarted
Controller1 - onChangeStarted
Controller2 - onAttach
Controller1 - onDetach

my solution is
`@Override
  protected void onAttach(@NonNull View view) {
        super.onAttach(view);
        if (getRouter().getBackstack().size() > 1) {
            ((BaseController) getRouter().getBackstack().get(getRouter().getBackstack().size() - 2).controller()).onPause();
        }
}`

**Comment by EricKuck** [comment]
The framework already does what you need it to do. Hacks like this are just
asking for trouble.

**Comment by gerc99** [comment]
What is the alternative solution to my hack? 
onChangeStarted is invoked twice and may cause NPE

**Comment by EricKuck** [comment]
`onChangeStarted` is invoked one time as the controller is being pushed and one time as it's being popped. There's no reason it would cause an NPE.

**Comment by gerc99** [comment]
When pushed and realm.removeChangeListener(), will be realm==null. Or do a lot of checks

**Comment by EricKuck** [comment]
That's still an application logic issue, not something related to the library. There's no reason you couldn't do what I've been saying. What you have might work, it's just going to be potentially rough to maintain.

**Comment by gerc99** [comment]
This logic is entirely dependent on the Conductor

**Comment by EricKuck** [comment]
Conductor isn't controlling when you initialize realm or the whole idea of
having a database control the app's title. There's 0 reason you can't do
what you want to do without hacks. Initialize realm in the constructor,
then do what I've been saying. It will work.

**Comment by gerc99** [comment]
Unsubscribe from the changes to the database where then?

**Comment by EricKuck** [comment]
onChangeStarted
