### ISSUE TITLE
getTargetController returns null

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#177]
In which cases can `getTargetController` return `null`?

My current setup is like this:
I have a `ControllerPagerAdapter` which has a reference to its host controller.
Inside this PagerAdapter I create new controllers in `getItem` and call `setTargetController` with the host controller as argument.

Now I'm receiving crashes because `getTargetController` returns sometimes `null` when called from `onAttach`. How is that possible? Is this a conductor bug?

**Comment by hannesstruss** [comment]
Does this happen when restoring after config changes?

I noticed a similar thing with controller relation information being partly lost after config changes. Given this setup:

```
// Pseudo-init:
setRoot(new A())
push(new B())
c = new C()
push(c)

cr = c.getChildRouter(...)
cr.push(C1())
cr.push(C2())
cr.push(C3())

              C1 --- C2 --- C3
             /
A --- B --- C
```

Now, before a config change `{c1, c2, c3}.getParentController()` will all return `C`. After a config change, only `c3.getParentController()` will return `C`, the others will return `null`. Now this is about _parent_ controllers, but could be a related issue. I hope I'll find some time to whip up a sample app later.

**Comment by hannesstruss** [comment]
I tried ☝️ but can't reproduce my issue anymore, sorry for the noise. (https://github.com/hannesstruss/Conductor/tree/hs/null-parent-controller)

**Comment by EricKuck** [comment]
I spent a few hours trying to reproduce either of the issues you guys have brought up and haven't gotten anywhere. I've tried everything from orientation changes to killing the host Activity and restoring to killing the entire app process and restoring. So far all of these cases have still resulted in controllers having non-null targets and parents.

I'm not sure if it's a conductor issue or an issue in your app, but if you make any progress with reproducing, please update this thread with whatever you find!

**Comment by PaulWoitaschek** [comment]
Okay it seems I have fixed the problem.

I made sure all routers use a ChangeHandlerFrameLayout (or my versions of `CardViewFrameLayout`, `CoordinatorFrameLayout`, ...). Now all these life cycle problems are gone.

I'm not 100% sure this was the issue but like 99.

If my assumptions are right the only reasonable thing for the library is to enforce that behavior by expecting `T extends ViewGroup & ControllerChangeListener` or at least log a warning.

**Comment by EricKuck** [comment]
All `ChangeHandlerFrameLayout` does is prevent touches during `ChangeHandler` execution. I'm not sure how this could be related to the issue you reported?

**Comment by PaulWoitaschek** [comment]
I found such a similar issue in my open source project.

[Here](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/v2.9.3.1/audiobook/src/main/java/de/ph1b/audiobook/features/bookOverview/EditBookBottomSheet.kt#L55) I'm receiving a null pointer exception because `getController(instanceId)` returned null upon a user clicking a dialog.

How is this possible?

```
Exception java.lang.NullPointerException: Attempt to invoke interface method 'void de.ph1b.audiobook.features.bookOverview.EditBookBottomSheet$Callback.onInternetCoverRequested(de.ph1b.audiobook.Book)' on a null object reference
de.ph1b.audiobook.features.bookOverview.EditBookBottomSheet$onCreateDialog$3.onClick (EditBookBottomSheet.kt:55)
android.view.View.performClick (View.java:5264)
android.view.View$PerformClick.run (View.java:21297)
android.os.Handler.handleCallback (Handler.java:743)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:150)
android.app.ActivityThread.main (ActivityThread.java:5546)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:792)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:682)
```

**Comment by PaulWoitaschek** [comment]
It's not fixed throug the change handler I posted above. Here is a complete stack-trace which ends with a NullPointerException becaue getActivity() returns null: https://gist.github.com/PaulWoitaschek/521c4a8231e990352d8c30e6fd2249f9

Now comes the interesting part: 
My log reveals that right before the crash a call to `router.getBackstack()` returns an empty list.

So if I understand correctly this is the clue to the error.

**Comment by EricKuck** [comment]
I just realized I never revisited this. I believe it was fixed a while back. Are you still seeing the issue or should I close?

**Comment by PaulWoitaschek** [comment]
Yes, still happening. I receive an `onAttach` while `isDestroyed` returns `true`.

**Comment by EricKuck** [comment]
Any chance you've tried on the latest snapshot? ec8ac2a371089121942efc3828de2085ea564696 should have fixed this issue for sure.

**Comment by PaulWoitaschek** [comment]
I've never seen this myself and see it only in crash reports. I'll release it for a fraction of the user with my next release. 

I am quite sure I am not explicitly setting the backstack manually. Will this fix it anyways?

Do you have any plans for the next conducot release?

**Comment by EricKuck** [comment]
I'll be releasing it as soon as the new shared element transition API (#307) is fully tested and stable. Hopefully soon!

**Comment by PaulWoitaschek** [comment]
@EricKuck 
That's the thing with soon ;)
Any news on an upcoming release?
