### ISSUE TITLE
Controller is not responding to touches

### ISSUE THREAD

**Issue by palaima** [bluelinelabs/Conductor#179]
Hey,

I'm having weird behaviour with `2.0.4` and `2.0.5-SNAPHOT` versions. (`2.0.3` works fine)

So, there is `LandingController` which has login button and `LoginController` with input fields.

Issue:

We starting at `LandingController` and clicking login button which opens `LoginController` and then I'm pressing back button which returns to `LandingController` and now this controller is not receiving any touch events (login button is not responding). After pressing `Home` button and opening app again everything starts to work, but fails again when going to `LoginController` and back.

I believe that there is some issues with library itself cause version `2.0.3` works fine in this case

**Comment by EricKuck** [comment]
I haven't seen any issues like this. Do you think maybe you could throw a quick demo together? I have no idea how else I could reproduce it. One quick question - are you using a custom ChangeHandler?

**Comment by palaima** [comment]
I'm using `FadeChangeHandler` for pushing and popping `LoginController`.
I'll try to make a demo

**Comment by palaima** [comment]
I have figured out. 

This is causing the problem. When you pass same ChangeHandler for push and pop `LandingController` is not responding.
```kotlin
router.pushController(
      val handler = FadeChangeHandler()
      RouterTransaction.with(LoginController())
        .pushChangeHandler(handler)
        .popChangeHandler(handler)
    )
```

If I pass different ChangeHandlers everything starts to work fine. (`2.0.4`, `2.0.5-SNAPSHOT`)
```kotlin
router.pushController(
      RouterTransaction.with(LoginController())
        .pushChangeHandler(FadeChangeHandler())
        .popChangeHandler(FadeChangeHandler())
    )
```

Do you have any ideas why this behaviour is different with `2.0.3` and `2.0.4` versions?

**Comment by EricKuck** [comment]
Ah, that makes sense. Newer versions of Conductor added a little more internal checking to `AnimatorChangeHandler` to make canceling work better than it used to. A side-effect of this is that they're more obviously not reusable (although they were never truly reusable). I believe a good solution to this issue would be to do either some checks to ensure that `ControllerChangeHandler`s aren't reused or to copy them before they're used.
