### ISSUE TITLE
Controller navigation issue

### ISSUE THREAD

**Issue by ar3s3ru** [bluelinelabs/Conductor#180]
Hello!
I'm trying to implement navigation on the same level between 2 controllers.
My situation is this:
* I have a `ChangeHandlerFrameLayout` container in my **MainActivity**
* *MainActivity* set **ControllerA** as root
* *ControllerA* has a `FloatingActionButton` that, when pressed, lets me navigate to a **ControllerB**

I basically want **ControllerA** to go into the backstack whenever I press the `FloatingActionButton`, and display **ControllerB** into the `ChangeHandlerFrameLayout`.

When back is pressed, I'd like to *navigate back* to **ControllerA**.

```
     _____________                  _____________                  _____________
    |             |                |             |                |             |
    | ControllerA |                | ControllerB |                | ControllerA |
    |             |  FAB pressed   |             |  Back pressed  |             |
    |             |  ===========>  |             |  ===========>  |             |
    |         fab |                |             |                |         fab |
    |_____________|                |_____________|                |_____________|
```

So I have 2 RouterTransactions: 

```kotlin
    val transactionA = RouterTransaction.with(ControllerA())
    val transactionB =  RouterTransaction.with(ControllerB())
                            .popChangeHandler(FadeChangeHandler())
                            .pushChangeHandler(FadeChangeHandler())
```

In my **MainActivity** `onCreate()` I do:

```kotlin
    if (!router.hasRootController()) router.setRoot(transactionA)
```

In my **ControllerA** `onClick()` method for the `FloatingActionButton` I do:

```kotlin
    router.pushController(transactionB)
```

but doing so, **ControllerB** is drawn on top of **ControllerA**, and I can still interact with **ControllerA**.

Using `router.setRoot(transactionB)` seems to do the trick (I read in other issues that it actually clears the container view), but when doing back navigation it throws:

```
java.lang.IllegalStateException: Trying to pop the current controller when there are none on the backstack.
```

where **MainActivity** `onBackPressed()` is the one shown in the README.

I saw that, when calling `ControllerA.getRouter().getBackstack()`, what I actually end up with is a copy of the backstack, not the actual list itself, so I cannot push the `transactionA` value onto the backstack when navigating to **ControllerB**.

Is there a way to achieve this?
Thanks!

**Comment by EricKuck** [comment]
This is really just the standard use case for the library. It's exactly how every app typically works. I've never seen any issues with it like what you're describing. The only thing I can see that you're doing that could cause problems is reusing transactions. Can you try using a new transaction each time?

**Comment by ar3s3ru** [comment]
Actually I tried both ways, still same result.

Maybe it's relevant to know that **ControllerA** and **ControllerB** instances are provided by a `MainActivityComponent` Dagger component, within an `@PerActivity` Scope

**Comment by EricKuck** [comment]
In that case you might be trying to reuse destroyed controllers. Can you try creating new controllers as well?

**Comment by ar3s3ru** [comment]
Tried that, as well.

The problem is that the view of **ControllerA** remains visible, I don't think that destruction plays some role here...

Given that it's a strange issue, I'll just explain my actual situation, rather than talking general.

In my **ControllerA** I have a `PagerAdapter` with **5 PageController** (each of them has a RecyclerView inside). 
**ControllerA** layout has a `CoordinatorLayout` as root `ViewGroup`, one `TabLayout` and the `ViewPager`.

`PagerAdapter` inherits from `ControllerPagerAdapter`, so I assume that  **ControllerA** has a child `Router` (don't know if it's relevant to the case).

I even tried `router.replaceTopController()` to switch to **ControllerB**, but with no luck (I still get `IllegalStateException` and **ControllerA** is still partially visible, IIRC).

If you want to take a look at the application yourself, check it out [here](https://github.com/ar3s3ru/Noty)

**Comment by EricKuck** [comment]
Thanks for the link. That was super helpful. Took a bit to figure it out, but it turns out you were just missing an argument in `inflater.inflate`. `NoteListController`'s call doesn't set `attachToRoot` to false (NoteCreationController, on the other hand, does). 

I know I said this earlier, but it is important - Controllers aren't meant to be reusable. There are several places you're injecting controllers or RouterTransactions. Instead, maybe inject controller/transaction factories?

**Comment by EricKuck** [comment]
FWIW, I'm adding an exception to the `Controller` make it obvious when this happens for the future.

**Comment by ar3s3ru** [comment]
> t turns out you were just missing an argument in inflater.inflate. NoteListController's call doesn't set attachToRoot to false (NoteCreationController, on the other hand, does).

How silly of me, thank you very much!
Now it perfectly works

> I know I said this earlier, but it is important - Controllers aren't meant to be reusable. There are several places you're injecting controllers or RouterTransactions. Instead, maybe inject controller/transaction factories?

Yeah, another silly thing.
Just saw that controllers are leaking, but I didn't find references where `Controllers aren't meant to be reusable` was actually specified (or, at least, I didn't read it, lol).

Thanks again, I'm closing the issue 👍
