### ISSUE TITLE
Maintain a changelog

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#181]
It would be great if you could continue maintaining a change log for new releases.

**Comment by hannesstruss** [comment]
There are changes logged in the GitHub releases: https://github.com/bluelinelabs/Conductor/releases

**Comment by PaulWoitaschek** [comment]
Only up to 2.0.3 - 4 and 5 are missing

**Comment by EricKuck** [comment]
Great call, thanks!
