### ISSUE TITLE
Demo crashing on API 25

### ISSUE THREAD

**Issue by JoniDS** [bluelinelabs/Conductor#183]
Hi, 

Thanks for the great library.
I tried running the demo on an API25 device and got a crash on "Child controllers".

Steps to reproduce:

1. API 25 device (Android 7.1)
2. Enable "Developer options"->Don't keep activities=true
3. Run the demo and go to "Child controllers", then try to change to a different app or go to the launcher screen (i.e. force the activity to be destroyed).

The app will throw the following crash:
> FATAL EXCEPTION: main
>                                                                                Process: com.bluelinelabs.conductor.demo, PID: 3416
>                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bluelinelabs.conductor.internal.LifecycleHandler.unregisterForActivityResults(java.lang.String)' on a null object reference
>                                                                                    at com.bluelinelabs.conductor.ActivityHostedRouter.unregisterForActivityResults(ActivityHostedRouter.java:79)
>                                                                                    at com.bluelinelabs.conductor.Controller.destroy(Controller.java:967)
>                                                                                    at com.bluelinelabs.conductor.Controller.destroy(Controller.java:960)
>                                                                                    at com.bluelinelabs.conductor.Backstack.pop(Backstack.java:61)
>                                                                                    at com.bluelinelabs.conductor.Router.popController(Router.java:122)
>                                                                                    at com.bluelinelabs.conductor.demo.controllers.ParentController$1.onChangeEnd(ParentController.java:63)
>                                                                                    at com.bluelinelabs.conductor.Controller.changeEnded(Controller.java:1132)
>                                                                                    at com.bluelinelabs.conductor.ControllerChangeHandler$1.onChangeCompleted(ControllerChangeHandler.java:177)
>                                                                                    at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.complete(AnimatorChangeHandler.java:146)
>                                                                                    at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.access$300(AnimatorChangeHandler.java:19)
>                                                                                    at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler$2.onAnimationEnd(AnimatorChangeHandler.java:186)

**Comment by EricKuck** [comment]
Thanks for the report. This is now fixed in the develop branch.
