### ISSUE TITLE
Router in ControllerPagerAdapter

### ISSUE THREAD

**Issue by nomisRev** [bluelinelabs/Conductor#187]
I have a Activity, with a ControllerPagerAdapter that hosts 3 controllers.

If I call `getRouter()` from within one of the hosted controllers, it doesn't return the "root" controller that I expected from my activity. Instead it returns a router with as container, the container the current controller resides in. (I hope that make sense)

So if I have MainActivity that hosts a ControllerPagerAdapter with ControllerA, ControllerB, and ControllerC. And ControllerA calls `getRouter` it returns a Router with as container "ViewPager". But what I actually expected was the get the router from MainActivity with as container ChangeHandlerFrameLayout where my ControllerPagerAdapter lives within.

Is this expected behaviour? And is that why the `RouterPagerAdapter.java` was introduced? Because this is a big issue in my app atm, and I'd need to resort to some dirty coding to work around it. I'd rather write a custom `ControllerPagerAdapter` than resort to dirty coding.

Any tips?

**Comment by nomisRev** [comment]
Okay, so I've dug deeper and I know what the issue is. ControllerPagerAdapter uses a ChildRouter to place the controllers within itself. But the "root" controller is never said on the controllers that are placed within that ChildRouter, thus if I call `getRouter` I get the Router of the ViewPager. 

In my use case I want to navigate to a detail of something selected from within the ViewPager so and because I hold the router of the ViewPager I go to a detail page within that ViewPager.

This could be fixed by calling `::setRouter` on the controller when placing it within the ViewPager like shown in the snippet below (will test and make a PR tomorrow).

If this was intended behavior please just close the issue or feel free to comment :) 

```Java
  @Override
    public Object instantiateItem(ViewGroup container, int position) {
        final String name = makeControllerName(container.getId(), getItemId(position));

        Router router = host.getChildRouter(container, name);
        if (savesState && !router.hasRootController()) {
            Bundle routerSavedState = savedPages.get(position);

            if (routerSavedState != null) {
                router.restoreInstanceState(routerSavedState);
            }
        }

        if (!router.hasRootController()) {
            Controller controller = getItem(position);
            controller.setRouter(host.getRouter())
            router.setRoot(RouterTransaction.with(controller).tag(name));
            visiblePageIds.put(position, controller.getInstanceId());
        } else {
            router.rebindIfNeeded();
        }

        return router.getControllerWithTag(name);
    }

```

**Comment by nomisRev** [comment]
This issue is does not have a easy (straight forward) fix. I'm going to implement a different solution, so I'm going to close this issue.

**Comment by EricKuck** [comment]
This is actually an interesting idea. The point of the `RouterPagerAdapter` was to allow each page to have its own backstack. Currently `ControllerPagerAdapter`'s Router is kind of pointless, since it really shouldn't be used. I wonder if we should make it so `RouterPagerAdapter` returns the child router and `ControllerPagerAdapter` returns the parent router?

BTW - A quick fix to your problem would be to use `getParentController().getRouter()`. I know it's not ideal, as it requires the controller to have a little more knowledge of its parent than it should, but it would work for you.

**Comment by nomisRev** [comment]
I already have a different solution in place. I'm working with a Navigator, first I was doing sharing a single implementation on "ViewScope" so I could easily access ChildRouters if I wanted to. But in this scenario it backfired.

So I opted for a Navigation class on "ActivityScope" injected with the router hosted by the activity. In the case I want a navigator on view level, I'd extend on that class and add the functionality for that specific view.

Anyhow, I think the current implementation seemed a little weird. I dug a little deeper in it, and adjusting ControllerPagerAdapter will not do. Because when you navigate back it, the controller from the ControllerPagerAdapter will bind itself back to the router of the ViewPager. At that point I thought it was pointless to dig deeper because I'd end up with dirty code to fix that problem.

However for the sake of searching for a solution I'm willing to dig deeper and collaborate to find a solution.

Thanks anyway for the response :)

**Comment by leonardo2204** [comment]
@nomisRev If you don't mind, you could post some snippet of this Navigator stuff you said (or maybe a sample ??). 
Thanks !
