### ISSUE TITLE
Lifecycle Issue?

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#188]
My setup is:

Activity -> Router -> Controller -> ViewPager -> Controller -> Multiple ChildController

In the Controller who hosts the ChildControllers in onAttach I do something like

```java
observable.compose(bindToLifecycle())
  .observeOn(observeOn)
  .subscribe(it -> {
    if (it) {
      Router router = getChildRouter(binding.dailyTip, "dailyTipRouter");
      if (!router.hasRootController()) {
        DailyTipController controller = DailyTipController.newInstance();
        RouterTransaction transaction = RouterTransaction.with(controller);
        router.pushController(transaction);
      }
    }
```

Now from time to time I receive a crash where the `DailyTipController`s `getActivity` returned `null` in `onAttach`. How is that possible?

**Comment by EricKuck** [comment]
Is this something you've seen (fairly reproducible), or are you going off stack traces from something like Crashlytics? Just wondering if there's a reliable way to see what's going on or if it'll just take a bunch of debugging to get to the bottom of.

**Comment by PaulWoitaschek** [comment]
Unfortunately it's case number 2 :(

**Comment by PaulWoitaschek** [comment]
I'm also heaving other weird lifecycle issues. 

At one place I replace the controller with a regular one (without any child controllers) and I received a NPE there because its `onTextChanged` of a `TextWatcher` was called when `isDestroyed()` returned `true`.
I logged all my events and I did not manually set a text to that EditText. However I can see logging events from the controller that was active before - so the controllers onTextChanged was called after it was popped.

**Comment by EricKuck** [comment]
Regarding the TextWatcher issue, are you by any chance reusing Controller instances? Conductor doesn't currently throw an exception if you add a destroyed Controller to a Router (though it will be doing so in the next release), so this could be a possibility?

**Comment by EricKuck** [comment]
Regarding the original issue, could you post a stacktrace?
