### ISSUE TITLE
What's the idiomatic way to wait for layout?

### ISSUE THREAD

**Issue by cbruegg** [bluelinelabs/Conductor#19]
I'm working on an app that displays data in a `RecyclerView` using a `GridLayoutManager`. I'm trying to compute the `spanCount` (the number of columns) by dividing the Controller's View's width by a desired tile width, but unfortunately `view.width` is `0` even in `onAttach(View)`. Is this intended behaviour? Is there an idiomatic way to deal with waiting for the initial layout apart from setting a listener in the View's `ViewTreeObserver`? To be clear, the View's width is set to `match_parent`.

**Comment by leonardo2204** [comment]
Something like this ?
```
public final class FlowUtils {

    public interface OnMeasuredCallback {
        void onMeasured(View view, int width, int height);
    }

    public static void waitForMeasure(final View view, final OnMeasuredCallback callback) {
        int width = view.getWidth();
        int height = view.getHeight();

        if (width > 0 && height > 0) {
            callback.onMeasured(view, width, height);
            return;
        }

        view.getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
            @Override
            public boolean onPreDraw() {
                final ViewTreeObserver observer = view.getViewTreeObserver();
                if (observer.isAlive()) {
                    observer.removeOnPreDrawListener(this);
                }

                callback.onMeasured(view, view.getWidth(), view.getHeight());

                return true;
            }
        });
    }

    private FlowUtils() {
    }
}
```

**Comment by sockeqwe** [comment]
Yes this is by design. `onAttach(View)` is called once the controllers view (returned from `onCreateView()` ) is attached to the window (or in other words `View.onAttachedToWindow()` has been invoked)

There is no difference regarding layout process compared to Fragments or Activities. So yes, you have to attach and detach a listener to `ViewTreeObserver`

And I don't see any reason to change that ...

**Comment by cbruegg** [comment]
Alright, thanks! Just wanted to check if I was doing something wrong or if this was unexpected behaviour. Thanks for clearing it up.
