### ISSUE TITLE
ControllerPagerAdapter leakead

### ISSUE THREAD

**Issue by gerc99** [bluelinelabs/Conductor#192]
![screenshot_1483725298](https://cloud.githubusercontent.com/assets/4727625/21727421/696c9896-d452-11e6-9b15-e7ffa102a6c9.png)

**Comment by EricKuck** [comment]
There's no chance of this issue being looked at without any details. For all I know this leak has nothing to do with Conductor.

**Comment by PaulWoitaschek** [comment]
I saw many leaks using conductor I couldn't make sense of. A lot of them involved the InputMethodManager.
