### ISSUE TITLE
Get controller from ControllerPagerAdapter via getRouter

### ISSUE THREAD

**Issue by ersin-ertan** [bluelinelabs/Conductor#195]
My use case is that I would like to use `getRouter().getControllerWithTag()` or `getRouter().getControllerWithInstanceId()` to reference the another controller within the same `ControllerPagerAdapter`, but since controllers are created with the tag of `return router.getControllerWithTag(name);` via `final String name = makeControllerName(container.getId(), getItemId(position));`,  we cannot know what the value of the tag is.

**Comment by duckinferno** [comment]
A method was recently added, `ControllerPagerAdapter.getController(pos)`

> Returns the already instantiated Controller in the specified position, if available.

Does this suit your needs?

**Comment by ersin-ertan** [comment]
Yes it does, thank you.
```java
((MyParentController)getParentController()).getMyPagerAdapter().getController(1);
```
Note for others: if you have not set the`viewPager.setOffscreenPageLimit(MY_NUM);`, then the `DEFAULT_OFFSCREEN_PAGES` = 1 and `getController()` may return `null`, thus consider increasing the limit to accommodate your getController request.
