### ISSUE TITLE
Don't understand this Exception

### ISSUE THREAD

**Issue by Rasalexman** [bluelinelabs/Conductor#196]
I Have MainActivity with router and register
if (!mainRouter.hasRootController()) {
            mainRouter.setRoot(RouterTransaction.with(new StartController()));
        }

then in in StartController onClickHandler i do change my Controller as in ExampleApp

this.getRouter().pushController(RouterTransaction.with(new LoginController())
                .pushChangeHandler(new HorizontalChangeHandler())
                .popChangeHandler(new HorizontalChangeHandler()));

and in LoginController i do
@OnClick(R.id.goBackToStart) void onGoBackToStart(){
        this.getRouter().popToRoot();
    }

after animation is complete i have this exception:
Can somebody explain what does it mean
Thanks

D/GestureDetector: [Surface Touch Event] mSweepDown False, mLRSDCnt : -1 mTouchCnt : 5 mFalseSizeCnt:0
D/GestureDetector: [Surface Touch Event] mSweepDown False, mLRSDCnt : -1 mTouchCnt : 8 mFalseSizeCnt:0
W/System.err: java.lang.IllegalArgumentException: Receiver not registered: android.widget.Editor$2@42f611c8
W/System.err:     at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:675)
W/System.err:     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1630)
W/System.err:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:452)
W/System.err:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:452)
W/System.err:     at android.widget.Editor.onDetachedFromWindow(Editor.java:471)
W/System.err:     at android.widget.TextView.onDetachedFromWindow(TextView.java:5060)
W/System.err:     at android.view.View.dispatchDetachedFromWindow(View.java:12441)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2626)
W/System.err:     at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3712)
W/System.err:     at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3687)
W/System.err:     at android.view.ViewGroup.removeView(ViewGroup.java:3619)
W/System.err:     at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler$2.onAnimationEnd(AnimatorChangeHandler.java:183)
W/System.err:     at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:765)
W/System.err:     at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1012)
W/System.err:     at android.animation.ValueAnimator.access$400(ValueAnimator.java:51)
W/System.err:     at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:623)
W/System.err:     at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:639)
W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:562)
W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:531)
W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:725)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err:     at android.os.Looper.loop(Looper.java:137)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5328)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/System.err: java.lang.IllegalArgumentException: Receiver not registered: android.widget.Editor$2@42f654f8
W/System.err:     at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:675)
W/System.err:     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1630)
W/System.err:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:452)
W/System.err:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:452)
W/System.err:     at android.widget.Editor.onDetachedFromWindow(Editor.java:471)
W/System.err:     at android.widget.TextView.onDetachedFromWindow(TextView.java:5060)
W/System.err:     at android.view.View.dispatchDetachedFromWindow(View.java:12441)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2626)
W/System.err:     at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3712)
W/System.err:     at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3687)
W/System.err:     at android.view.ViewGroup.removeView(ViewGroup.java:3619)
W/System.err:     at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler$2.onAnimationEnd(AnimatorChangeHandler.java:183)
W/System.err:     at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:765)
W/System.err:     at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1012)
W/System.err:     at android.animation.ValueAnimator.access$400(ValueAnimator.java:51)
W/System.err:     at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:623)
W/System.err:     at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:639)
W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:562)
W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:531)
W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:725)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err:     at android.os.Looper.loop(Looper.java:137)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5328)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by Rasalexman** [comment]
I have this message in debug on my mobile phone Samsung G4

**Comment by EricKuck** [comment]
I couldn't find much on this, but it sounds very similar to https://code.google.com/p/android/issues/detail?id=63228. This doesn't appear to be related to Conductor itself, as it happens when the view is simply removed from its parent. There's nothing special going on here. Given that the only Google results I found that kind of matched this exception are from the Galaxy S4, it seems like it's another Samsung bug. Are you doing anything in any other callbacks related to receivers?

**Comment by EricKuck** [comment]
I haven't heard anything about this for a while, so I'll close the issue. Definitely reopen if there's any updates here.

**Comment by Rasalexman** [comment]
Hello! Ok, please close it! So i have this exeption only in debug mode on my phone. 
Thanx for your work. I love CONDUCTOR!!
