### ISSUE TITLE
The right way of replacing controller with child routers

### ISSUE THREAD

**Issue by shchurov** [bluelinelabs/Conductor#199]
I think it's not really an issue, just a question what's the right way of doing it.
So I have `Controller A` that contains a couple of child controllers in their own routers: `Controller A1`, `Controller A2`.
Now I want to replace `Controller A` with `Controller B` and use a view from `Controller A1` in the animation `ChangeHandler`. The problem is that `setRoot` or `replaceTopController` methods remove all child controller views before executing the change and I can't use them during the animation.

I think as a workaround I can use `pushController` instead and then just pop previous controller, but is there any `official` way of doing it?

UPD: actually workaround doesn't really work, it removes the previous controller's view but `onDestroyView` is never called for some reason

**Comment by mDroidd** [comment]
Check out TransitionChangeHandler:
https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/changehandler/TransitionChangeHandler.java

**Comment by shchurov** [comment]
@mDroidd, although I'm using `AnimatorChangeHandler` at the moment, not sure how using different one should help, since the views are removed even before `executeChange` in a very base `ControllerChangeHandler`

**Comment by mDroidd** [comment]
I must admit I'm not an expert on this topic, but as far as I know the Transition framework is made specifically (as far as scenes go) to animate views that would otherwise have been removed.

I you're not willing to give it a shot than I'll see if I can set up a sample in the next week.

**Comment by shchurov** [comment]
@mDroidd, just tried it, it doesn't work. But that's quite expected, for instance `replaceTopController` clears all the children controllers' views here, before any calls to change handlers:
https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/Router.java#L166

**Comment by EricKuck** [comment]
This appears to be a bug in the library. It should not be removing child views before performing transitions. I'll take a look at this and should have a fix within the next day or so. Thanks for the report.

**Comment by EricKuck** [comment]
This should be fixed now. Let me know if the latest snapshot doesn't do what you need.

**Comment by shchurov** [comment]
`replaceTopController()` works now, but in case of `setRoot()` `from` argument is null in the change handler. Although from my point of view it makes sense, not sure if it's intentionally. Anyway it's ok for me, thanks for the fix!
