### ISSUE TITLE
Target Controller Use Case With Multiple Routers

### ISSUE THREAD

**Issue by cody1024d** [bluelinelabs/Conductor#200]
The following use-case currently results in a target controller that is null.

I have an Activity, MainActivity.  It contains 2 containers (and thus 2 routers), one for displaying dialog-controllers, and then one for displaying the actual content.

The actual content controller (call it controller A), wants to display a dialog, so, it get's it's activity, and I expose, via an interface, a method to display a controller (call it controller B) in that second router (essentially making it a dialog).  Controller A sets itself as a target on controller B.  Because of the implementation:

```java
    @Nullable
    public final Controller getTargetController() {
        if (targetInstanceId != null) {
            return router.getRootRouter().getControllerWithInstanceId(targetInstanceId);
        }
        return null;
    }
```

Controller B can never actually find controller A as it's target controller.  They don't share the same root router.

**Comment by cody1024d** [comment]
I have a work-around, although it essentially by passes the entire targetController system, so it's definitely less than ideal.

**Comment by EricKuck** [comment]
Curious - what made you decide to use 2 routers for this? This would probably be greatly simplified if you used child routers instead of two completely separated routers. I'm not against the idea of allowing inter-router communication in theory, but I'd have to look a little more into potential side-effects before committing to it.

**Comment by cody1024d** [comment]
@EricKuck 

It's very possible that that decision was incorrect haha.  My desired user-experience is to display a dialog-esque controller OVER other content.

**Comment by EricKuck** [comment]
Sorry, my previous suggestion was actually not great - doing it as a child router would mean that each controller you want to present a dialog in would need to have a ViewGroup to host them. A much better idea would be to simply push the dialog to the router you're already using. The following code would push your dialog controller on your existing router without removing the controllers that are already there:

```
getRouter().pushController(RouterTransaction.with(DialogController())
    .pushChangeHandler(new FadeChangeHandler(false))
    .popChangeHandler(new FadeChangeHandler())
```

The `false` param correlates to `removesFromViewOnPush`, which tells Conductor not to remove the view of the controllers that are already on the backstack when this ChangeHandler is run

**Comment by cody1024d** [comment]
Ah.  Bingo!  Thanks so much @EricKuck.  I knew it seemed like such a normal use-case, there had to be a solution to it.

Also, I've been doing Android Dev for a long time, this is the first time I've used this library; but I don't think I could go back, I am totally appreciative of you and Blueline labs for creating this.
