### ISSUE TITLE
SetRoot that works with animations 

### ISSUE THREAD

**Issue by FabianShallari** [bluelinelabs/Conductor#204]
Is there a way that `setRoot()` works with animations in case that the backstack is not empty when the `setRoot()` method is called?

_**For example:**_
I am deep in the controller backstack and user presses Logout. In order to clear the backstack properly I use `setRoot(RouterTransaction.with(new LoginController())
        .pushChangeHandler(new HorizontalChangeHandler(1000))
        .popChangeHandler(new HorizontalChangeHandler(1000)))` 

However `from` is null inside `HorizontalChangeHandler` so the `from` view does not get animated and it doesn't look smooth at all.

Or is there something else besides `setRoot` I should use for this use case?

Might also be related to #199

**Comment by EricKuck** [comment]
Thanks, should be fixed now!

**Comment by FabianShallari** [comment]
Thanks @EricKuck. I appreciate it 😄
