### ISSUE TITLE
Lifecycle Documentation

### ISSUE THREAD

**Issue by mheras** [bluelinelabs/Conductor#21]
Hi,

I'm trying to understand the lifecycle of a Controller and I have a doubt:

How can I differentiate a configuration change such as the device rotation from a navigation event such as the Controller being popped or be sent to the backstack?

When are the `onSaveInstaceState` and `onSaveViewState` methods called on each case?

I think more documentation on that topic would be great to fully understand why the lifecycle of a Controller is easier than the Activity one, as you state.

Thank you very much.
Your lib is great :)

**Comment by JakeWharton** [comment]
You can call getActivity().isChangingConfigurations().

**Comment by mheras** [comment]
Great thank you @JakeWharton.
