### ISSUE TITLE
Controller styling

### ISSUE THREAD

**Issue by AndrzejMistetskij** [bluelinelabs/Conductor#210]
Hi, 
How can I use different themes for Controllers?

**Comment by mDroidd** [comment]
I'm not sure this is a conductor question, but here's how I solved it.

Instead of inflating with 

        inflater.inflate(R.layout.fragment_timeline_recycler, container, false);
use 

        Context contextThemeWrapper = new ContextThemeWrapper(getActivity(), R.style.MyTheme);
        LayoutInflater inflater = inflater.cloneInContext(contextThemeWrapper);
        inflater.inflate(R.layout.fragment_timeline_recycler, container, false);

This will apply MyTheme to the inflated view.
