### ISSUE TITLE
[Question] ChildControllers defined for ViewGroups

### ISSUE THREAD

**Issue by saantiaguilera** [bluelinelabs/Conductor#211]
Currently, we can only create `ChildControllers` for `ViewGroups` (`getChildRouter(ViewGroup)`). 

Could we add a feature to attach Controllers to `View` instead of `ViewGroup` ? This way we could do easier MVP + benefit from `Activity`/`applicationContext`/`Router` stuff + have automated the attach/detach and lifecycles.

Currently the usual flow with a nested MVP is something like:
```Java
class MController extends Controller {

  private Contract1.Presenter presenter1;
  private Contract2.Presenter presenter2;

  onCreateView(..) {
    presenter1 = new Presenter1(args1);
    presenter2 = new Presenter2(args2);
    return inflate...;
  }

  onAttach(View view) {
    //Both view1 and view2 dont necessarily have to be a ViewGroup. They can be whatever extends View.
    presenter1.attachView((Contract1.View) view.findViewById(view1);
    presenter2.attachView((Contract2.View) view.findViewById(view2);
  }

  //Same on detach

}
```
While, if we could attach child controllers to `View` we could do something like this..
```Java
class MController extends Controller {

  onCreateView(..) {
    View rootView = inflater.inflate(...);
    getChildRouter(rootView.findViewById(view1))
      ...
      .setRoot(RouterTransaction.with(new Controller1(args1)
        .pushChangeHandler(...)
        ...);

    getChildRouter(rootView.findViewById(view2))
      ...
      .setRoot(RouterTransaction.with(new Controller2(args2)
        .pushChangeHandler(...)
        ...);

    return rootView;
  }

}
```

And our presenters now have access to context / routers + can benefit from lifecycles

Maybe im understanding bad MVP with Conductor ? =P

**Comment by EricKuck** [comment]
If a router could be attached to a View (not a ViewGroup), it would be impossible to push controllers (subviews) to it. I think maybe I'm misunderstanding your question.
