### ISSUE TITLE
onDetach not called when activity paused

### ISSUE THREAD

**Issue by blazeroni** [bluelinelabs/Conductor#213]
According to the lifecycle diagram, Controllers should have `onDetach` called when an activity is paused.  However, that doesn't seem to be true.  `onActivityPaused` is getting called, but not `onDetach`.  I see this when I start an activity with controllers then hit the home button.  I'm using 2.0.7.

Are the docs incorrect or the behavior?

**Comment by sockeqwe** [comment]
Which docs are you referring to?

blazeroni <notifications@github.com> schrieb am Do., 26. Jan. 2017, 23:33:

**Comment by blazeroni** [comment]
I'm looking at this image: https://github.com/bluelinelabs/Conductor/raw/develop/docs/Controller%20Lifecycle.jpg.  Notice the line from Controller In Focus to onDetach with the note beside it that reads: "Controller popped, pushed to backstack, or Activity paused"

**Comment by EricKuck** [comment]
Under what circumstance are you not getting onDetach when the Activity
pauses? It's working for me.

**Comment by blazeroni** [comment]
I build the conductor demo app with additional logging in onDetach() and onAttach() in BaseController.  Logs are output when navigating between controllers, but not when leaving the activity - either by pressing home, or clicking on the github link in the About popup.

**Comment by EricKuck** [comment]
Sorry about that! DIdn't realize I'd been testing with "Don't keep activities" on. This should now be fixed in the latest snapshot. FYI - `onDetach` is actually called during `onStop`, not `onPause`.

**Comment by blazeroni** [comment]
Ha, happens to me as well.  Great, thanks for fixing it!

**Comment by PaulWoitaschek** [comment]
Can we get a hotfix release for this? We lost a few users during the registration because some events were sent while the application was closed.

**Comment by PaulWoitaschek** [comment]
Can we get a hotfix release for this? We lost some users during the registration because some events were sent while the application was closed.

**Comment by EricKuck** [comment]
Sorry about that @PaulWoitaschek! I want to get a bit more testing in with the snapshot, but I can do a hotfix soon. Anyone else that wants to help test it would be greatly appreciated!
