### ISSUE TITLE
TransitionChangeHandler

### ISSUE THREAD

**Issue by nomisRev** [bluelinelabs/Conductor#214]
`java
 @Override
 public final boolean removesFromViewOnPush() {
    return true;
}
`

I'm doing a shared element transition of a fab to a dialog. similar as in Plaid. But since I'm transition to an overlay, I want the `from` view to not be removed. But `removesFromViewOnPush` is final and true in TransitionChangeHandler opposed of non-final in AnimationChangeHandler.

Any particular reason why it's final here? Or how I could achieve this with the current API?

**Comment by EricKuck** [comment]
If the `from` view isn't removed (or set to `GONE`), how does the shared element transition work? Do you have a link to something similar?

**Comment by nomisRev** [comment]
That is what I currently have. And it is working as "expected". You start `        TransitionManager.beginDelayedTransition(container, transition)` and then it will check what transition to do depending on what changes. So traditionally you do `remove(from)` and `add(to)`, and that will cause a transition `from -> to`

In my case I want to only do a transition on the FAB, the weird issue I'm seeing now is that the shared element works but the `to` ViewController jumps behind the `from` ViewController after `onChangeCompleted`. If I figure that out, I think I can get it working.

(I have a fairly simply layout list + FAB, when the FAB is clicked it transitions to the middle of the screen in a new VC). If I have that working I can add a custom ChangeBounds which will do a shared element with change bounds from FAB -> ViewGroup.


```java
    override fun performChange(container: ViewGroup, from: View?, to: View?, isPush: Boolean, changeListener: ControllerChangeHandler.ControllerChangeCompletedListener) {
        if (canceled) {
            changeListener.onChangeCompleted()
            return
        }

        val transition = getTransition(container, from, to, isPush)
        transition.addListener(object : Transition.TransitionListener {
            override fun onTransitionStart(transition: Transition) {}

            override fun onTransitionEnd(transition: Transition) {
                changeListener.onChangeCompleted()
            }

            override fun onTransitionCancel(transition: Transition) {
                changeListener.onChangeCompleted()
            }

            override fun onTransitionPause(transition: Transition) {}

            override fun onTransitionResume(transition: Transition) {}
        })

        TransitionManager.beginDelayedTransition(container, transition)
        if (from != null) {
            val view = from.find<FloatingActionButton>(R.id.fab)
            (from as ViewGroup).removeView(view)
//            container.removeView(from)
        }
        if (to != null && to.parent == null) {
            container.addView(to)
        }
    }
```

That is my push CH.

The desired transition can be found here https://github.com/nickbutcher/plaid.
HomeActivity => DribbleLogin

**Comment by nomisRev** [comment]
I fixed it by using z index now. Which doesn't feel right, I find it very weird that when I add `to` to container, it ends up under `from`.

Anyway, I'm willing to share the code once I finish it. Since it might be cool for an advanced example. So shall I leave this issue open for know? I'll add the animation to the animation section in the demo, if you want. I'll link this issue then, and maybe we can figure out some way to handle all this cleaner

**Comment by EricKuck** [comment]
@nomisRev Did you end up figuring out a good way to do this? I've been looking into it recently and am running up against a bunch of roadblocks that you've probably figured out by now.

**Comment by nomisRev** [comment]
@EricKuck I think can make some free time this weekend to make a PR for the dialog <-> FAB transition from Plaid.

There are some issues (workarounds) I had to do to make this work. I do still have 1 issue but that is unrelated to Conductor. I have a quite complex setup with RxJava2, Kotlin, RxRelay, etc to communicate between the `DialogViewController` and my `MainViewController` and I also use DI all over the place. So I have quite some cleaning up to do to make it work in the demo.

I will do my best to make time this weekend, and if I don't have enough time I'll definitely let you know here. But you can expect the PR next week. And hopefully we can figure out the last missing pieces together. Again it's unrelated to Conductor but it's an issue with using complex transitions like the FabTransform from Plaid in combination with a View based architecture and TransitionManager API. I've also encountered the issue when doing pure View based w/o Conductor, as well as using the Scene API from the TransitionManager API. But it will be more clear once you see the code and I'll include comments to describe the issue more clearly.

Anyhow, I was thinking to just add a new section in the HomeController for the FAB <-> Dialog. It makes more sense to give it a separate section. I'll lose the DI, Rx, Anko, Kotlin for the demo. Thoughts?

**Comment by sockeqwe** [comment]
I might be missing something, but you don't have to extend from `TransitionChangeHandler` at all, right? Why not making a custom `MyTransitionChangeHanlder extends ChangeHandler` where you can remove the views as you want?

**Comment by nomisRev** [comment]
That's what I did. There is no problem with that.
