### ISSUE TITLE
ControllerPagerAdapter stacks child menus

### ISSUE THREAD

**Issue by mDroidd** [bluelinelabs/Conductor#215]
I'm using a ViewPager and the supplied conductor ControllerPagerAdapter.

if I'm on page 2, even items that are not on the screen (e.g. pages 1 and 3) already show their menus. While I'm aware that this should be the case for normal controllers (controller is attached so its menu should show), I don't think it's the intended behavior for ControllerPagerAdapter.

What is your opinion on this issue, should I just find a workaround or is this something you'd like to fix?

Thanks in advance.

**Comment by EricKuck** [comment]
The issue with doing a global fix for this is that viewpagers can be setup to display more than one page on the screen at the same time. In some cases, the developer might actually want menu options for each of their pages to be visible (not really sure why, but it's possible).

My recommendation on this would be to add a listener to your viewpager. Call `setOptionsMenuHidden(true)` on all pages. When a new controller becomes the focused controller, call `setOptionsMenuHidden(false)` on that one. This could also be abstracted into a pager adapter if you'd like to get it out of your main controller logic. Does that make sense? Anything lacking with this solution?

**Comment by mDroidd** [comment]
If that's the case, I'll think I will experiment with overriding
setPrimaryItem in PagerControllerAdapter and submit a pull request if
that's okay with you. I'll make it optional with a setter on the adapter.

Otherwise I'll just keep that private, just thought others might be
interested.

You can close this issue :)

**Comment by hzsweers** [comment]
> You can close this issue :)

So can you!
