### ISSUE TITLE
Navigation inside ViewPager page

### ISSUE THREAD

**Issue by maoueh** [bluelinelabs/Conductor#217]
Maybe I'm doing something wrong, sorry if it's the case. 

It seems that I'm not able to navigate to a sub-page inside one of the ViewPager's page. Let's use the Demo App as example. What I try to achieve is to go to `ViewPager` entry, when there, swipe to go to Page 2, then when there, have a button that change content within this page.

When using the `ControllerPagerAdapter`, after navigating, the ViewPager container is blank. Back press works and make it go back correctly to initial page and then another back press back to demo app main menu.

I create a branch ([bug/navigation-inside-view-pager-not-working](https://github.com/maoueh/Conductor/commits/bug/navigation-inside-view-pager-not-working)) in my fork that showcase the problem: https://github.com/maoueh/Conductor/commit/3df7c5454c0c33b0d9910dddeaf2db57f7659a37.

If I switch from `ControllerPagerAdapter` to `RouterPagerAdapter`, it works correctly (however, if sub-navigation was done on Page 0 and I navigate to Page 2 then back to Page 0, router is re-initialized but that might be correct, did had time to work on this yet).

I try to investigate a bit, the view in the sub-navigation seems to be inflated correctly. Not quite sure what is the problem.

**Comment by EricKuck** [comment]
Your hunch was correct. `ControllerPagerAdapter` is not meant to allow navigation. It's just meant to display a single Controller per page. `RouterPagerAdapter` displays a Router per page, which is what makes the navigation work. Because of this confusion, `ControllerPagerAdapter` will be deprecated soon.

I'm not sure why your router would be re-initialized when going back to a page that's already been shown. Are you doing `if (!router.hasRootController()) {` before setting the root?

**Comment by EricKuck** [comment]
`ControllerPagerAdapter` was just deprecated in the latest snapshot (soon to be pushed to master) and one issue with viewpager backstacks has been fixed. I'm pretty sure this will close out your issue, but free to reopen if you still have any problems.

**Comment by maoueh** [comment]
@EricKuck Thanks, will test out the new release and open new issue if I hit other problems.

**Comment by maoueh** [comment]
@EricKuck Indeed the "disappearance" was caused by the fact that I was resetting the controller myself since I didn't had  the `if (!router.hasRootController())` line. Thank you.
