### ISSUE TITLE
Lifecycle question about getTargetController()

### ISSUE THREAD

**Issue by adi1133** [bluelinelabs/Conductor#22]
What lifecycle callback should I use to call `getTargetController()` as soon as possible ?

The call works from inside `onCreateView()`, but fails inside `onRestoreInstanceState()` or any of the constructors.
Ideally I'd use a lifecycle callback that happens only once per instance but has access to `getTargetController()`

My usecase is grabbing data from a "parent" controller, I set the parent controller using `setTargetController()`, later I want the child to get a dagger component from the parent to inject itself.

Am I doing it completely wrong ?

**Comment by EricKuck** [comment]
I hadn't really intended target controllers to be used this way, but this does bring up a bigger issue that it would be nice if the router (and therefore the activity, context, and target controllers) was available in onRestoreInstanceState. This has been addressed in 495145b.

**Comment by adi1133** [comment]
the child controller's `onRestoreInstanceState` is called before the parent's. This means that I still can get data from parent Controller after actvity recreation (caused by process death).

**Comment by EricKuck** [comment]
Indeed. The callbacks were re-sorted for controllers of the same hierarchy level, but not for those with a parent/child relationship. This is fixed in b8ccf36.

**Comment by adi1133** [comment]
Seems like we live in a different timezome, I will check tomorrow to see if it works in my use case.

**Comment by adi1133** [comment]
Seems to be working fine. b8ccf36 solved my issue.

**Comment by EricKuck** [comment]
This is now published in 1.1.4. Thanks again for the report.
