### ISSUE TITLE
RouterPagerAdapter Sub Navigation Issue

### ISSUE THREAD

**Issue by cody1024d** [bluelinelabs/Conductor#220]
I'm seeing a weird behavior when using the RouterPagerAdapter.

Specifically, if I perform a sub-navigation within Page 0, and then move to Page 2, then back to Page 0, and perform another sub-navigation, I am noticing strange behavior.  Specifically, I am seeing this issue because I have some clear backgrounds (to just use the window color as the background for the controller) that now display the previous controllers, where, without navigating to Page 2, it works as intended.

I saw you mention a backstack issue with RouterPagerAdapter in #217 so just curious if this is what was mentioned.  I did check the latest snapshot (2.1.1) and am still seeing this behavior there, as well.

Let me know if this isn't clear enough, and I can try and provide more detail.

For reference, here is my RouterPagerAdapter implementation currently:

```java
class MainTabAdapter extends RouterPagerAdapter {

    private ControllerTabItem[] items;

    @Inject
    public MainTabAdapter(Controller host, ControllerTabItem[] items) {
        super(host);
        this.items = items;
    }

    @Override
    public void configureRouter(Router router, int position) {
        if (!router.hasRootController()) {
            Controller controller = items[position].getControllerFactory().build();
            router.pushController(RouterTransaction.with(controller));
        }
    }

    @Override
    public int getCount() {
        return items.length;
    }

    public ControllerTabItem[] getItems() {
        return items;
    }

    public ControllerTabItem getItemAt(int position) {
        return items[position];
    }

}
```

**Comment by maoueh** [comment]
@cody1024d Using the conductor demo, with this adapter:

```
pagerAdapter = new RouterPagerAdapter(this) {
            @Override
            public void configureRouter(@NonNull Router router, int position) {
                if (!router.hasRootController()) {
                    Controller page = new ChildController(String.format(Locale.getDefault(), "Child #%d (Swipe to see more)", position), PAGE_COLORS[position], true);
                    router.pushController(RouterTransaction.with(page));
                }
            }

            @Override
            public int getCount() {
                return PAGE_COLORS.length;
            }

            @Override
            public CharSequence getPageTitle(int position) {
                return "Page " + position;
            }
        };
```

Where `ChildController` has a `Next` button doing:

```
        btnNext.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                getRouter().pushController(RouterTransaction.with(new TextController(String.format("Next from %s", getArgs().getString(KEY_TITLE)))));
            }
        });
```

I'm unable to reproduce on latest `develop` branch. When pressing `Next`, the sub-navigation work, then switching between pages never resets navigation on page where I pressed `Next`.

You can check out [bug/navigation-inside-view-pager-not-working](https://github.com/maoueh/Conductor/tree/bug/navigation-inside-view-pager-not-working) from my repo (see diff https://github.com/bluelinelabs/Conductor/compare/develop...maoueh:bug/navigation-inside-view-pager-not-working).

**Comment by cody1024d** [comment]
@maoueh Thank you for taking a look.  I am thinking about my issue, and I believe it to be completely unrelated, after the fact.  I am going to close this issue for now, until I can provide more information, and do a deeper dive into what is happening.
