### ISSUE TITLE
Question about controller lifecycle

### ISSUE THREAD

**Issue by mzgreen** [bluelinelabs/Conductor#226]
Hi, thanks for an awesome library!

I'm looking for a callback that is invoked when changing controllers like onAttach/onDetach pair but in order of their controllers. Let me illustrate with an example:

There are 2 controllers: `ControllerA` and `ControllerB`. Currently we see `ControllerA` so it's in `attached` state. Now we're going to `ControllerB` and what will happen is this:
`ControllerB.onAttach()`
`ControllerA.onDetach()`
which makes sense. What I'm looking for is callbacks that behave like below:
`ControllerA.aIsBeingClosed()`
`ControllerB.bIsBeingOpened()`
Is there anything like this?

Cheers

**Comment by EricKuck** [comment]
I'm not sure what the use case for this would be, but if you really need something sequential you can use `onChangeStarted` in both controllers and check the `changeType` parameter to see if it's an enter or exit.
