### ISSUE TITLE
Performance comparison between fragments and conductor with views

### ISSUE THREAD

**Issue by ar-g** [bluelinelabs/Conductor#230]
I would like to know is there are any performance benefits when using this library with views compare to standard fragments?

**Comment by EricKuck** [comment]
If you're looking for a benchmark, I don't have one. Given that Conductor is much lighter weight than Fragments though, it should be more performant. What kind of performance are you talking about here? Do you have a way to quantify it?

**Comment by PaulWoitaschek** [comment]
I never faced an issue where fragments or conductor are the limiting factor. What's slow is slow stuff like the view inflation itselft, but that's something both have to do.

**Comment by ar-g** [comment]
@EricKuck we noticed that some of our screens are opening really slow, but it is usually when transitioning between activities with multiple fragments. 

We have noticed that instragram works blazingly fast and it seems that they use all in one Activity.

We were wondering would it work faster if we switch to all in one activity. And whether we should use fragments or conductor?

**Comment by EricKuck** [comment]
Activities are much heavier than Fragments, which are heavier than Conductor Controllers. Again, I don't have any benchmarks, but converting from Fragments -> Controllers should be a bit faster and converting from Activities -> Controllers should be noticeably faster.
