### ISSUE TITLE
TransactionTooLargeException: Router keeps all ViewStates

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#236]
Android N introduced a TransactionTooLargeException if the saved state is too large.
I receive a lot of these exceptions in my current project.

This is because the viewstate of each router gets saved by the `RouterPagerAdapter`. It would be great if one could specify a limit of how many pages one likes to save.

**Comment by EricKuck** [comment]
This shouldn't be too bad to fix. Does your project have a huge number of pages? Or are you running into this with a "normal" amount?

**Comment by PaulWoitaschek** [comment]
Yes, huge number. You can swipe through days and you can view about 3 years=~1000 pages. On Android N it crashes after you swiped about 15 pages.

As a workaround I just created a copy of the `RouterPagerAdapter` and iterate over the `SparseArray` in `destroyItem` and just remove every position that is more than n+1 items larger/smaller from the position for which the ViewState will be saved.

**Comment by PaulWoitaschek** [comment]
Thanks! :)
