### ISSUE TITLE
AnimatorChangeHandler w/ removesFromViewOnPush=false breaks when popping multiple transactions

### ISSUE THREAD

**Issue by duckinferno** [bluelinelabs/Conductor#239]
Reproduction:
1. Start with RootController, push Controller1 and Controller2 using `new HorizontalChangeHandler(false)` as push/pop change handlers (or any other `AnimatorChangeHandler`)
2. Call getRouter().popToRoot() on Controller2

Expected: Controller1 and Controller2 are popped and their views are removed.

Actual: Controller1 and Controller2 are popped but only Controller2's views are removed.  Controller1's views remain on screen.

Attachments
1. Screenshot showing MainActivity's router backstack after popToRoot, verifying that only RootController exists.
![screen shot 2017-02-27 at 9 50 52 am](https://cloud.githubusercontent.com/assets/3953262/23343699/b6cf0d76-fcd4-11e6-8aa8-23e3a2f1a532.png)

2. Screenshot showing the inspected layout after popToRoot, showing that RootController and Controller1's views are inflated, while Controller2's views were removed from the container. 
![screen shot 2017-02-27 at 10 04 10 am](https://cloud.githubusercontent.com/assets/3953262/23343703/c0fb2ca8-fcd4-11e6-9d32-96a719402863.png)

3. Reproduction project
[ChangeHandlerConductorBug.zip](https://github.com/bluelinelabs/Conductor/files/802288/ChangeHandlerConductorBug.zip)

**Comment by sockeqwe** [comment]
This is a world class bug report! Well done! I wish more people would take the time to file such bug reports! 👍

**Comment by duckinferno** [comment]
You took the time to make this framework, I think it's the least we can do :)

**Comment by sockeqwe** [comment]
No it wasn't me, all credits to @EricKuck

**Comment by EricKuck** [comment]
Thanks for the great bug report. This should now be fixed in the latest snapshot.
