### ISSUE TITLE
Question about saveInstanceState

### ISSUE THREAD

**Issue by BlackHornet** [bluelinelabs/Conductor#242]
Hi,

currently I'm working on my first application moving from Fragments to Controllers.

Due to my app design I got my Activity with the main router and my "MainController" being set as root.

In addition I'm using another SecondController, that is set as root for a childRouter in my MainController

Activity > MainController > SecondController

my problem now is, that whenever I'm going for an orientation change or simulated "activity recreation", onSaveInstanceState is called in all of my controllers, but onRestoreInstanceState is not being called.

Is there something I missed in my general controller setup? the savedInstanceState bundle from Activity.onCreate is passed to the Conductor.attachRouter call in Activity onCreate.

Kind Regards

**Comment by EricKuck** [comment]
Your Controllers are retained through orientation changes, so `onRestoreInstanceState` will not be called. Only `onRestoreViewState` will be called, as only your view needs to be recreated in this case. `onSaveInstanceState` is simply called as a safeguard in case the Activity could be destroyed.

**Comment by BlackHornet** [comment]
Thanks alot for this short explanation 👍
