### ISSUE TITLE
New component: Module

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#243]
I have an unfinished idea I want to express:

In my apps I often use headless fragments to encapsulate framework behavior. For example I have a headless `PermissionFragment`, a headless `GoogleFitFragment`, ...
They use the callbacks (like permission result, or onActivityResult) to manage the state of the framework component.
That way I can just call `fun PermissionFragment.request(permission : String): Single<PermissionResult>` or whatever and do not have to re-implement the same logic in all classes that use permissions (or what ever).

Now I was thinking that it would be great to have something like this for conductor (because the headless fragment is a fragment and often there are lifecycle issues with it).
I'd call this something like `Module` and it would be quite similar to a `Controller` just without the view parts. There should be methods like `fun addModule(module : Module, tag: String)`, `fun findModule(tag: String) : Module?` on the router to add/receive these modules.

So now when the user is inside a controller he could call

```kotlin
fun onAttach() {
  val permissionModule = router.findModule(PERMISSION_MODULE) as PermissionModule
  permissionModule.request(CAMERA)
    .subscribe { println("result is $it") }
}

**Comment by sockeqwe** [comment]
You could also directly listen for those events in your Activity? There are a lot of such "plugin solutions" for activities like this https://github.com/passsy/CompositeAndroid

> do not have to re-implement the same logic in all classes that use permissions (or what ever).

One could encapsulate this logic into a `Controller.LifecycleListener`  lets say `class GoogleFitLifecycleListener extends Controller.LifecycleLisenter`. This is basically a plugin you can use for any other controller:

```java
class FooController {
      public FooController(){ addLifecycleListener( new GoogleFirLifecycleListener());}
}
```


```java
class OtherController {
      public OtherController(){ addLifecycleListener( new GoogleFirLifecycleListener());}
}
```

**Comment by PaulWoitaschek** [comment]
It would be coupled to the module and accessible by Controllers. Sure it is possible to put everything in the activity but I really see the use-case to have separate modules. 

With that argument you can remove all the `onPermissionResult`, `onActivityResult`, ... methods from the controllers and just do everything in the activity.

It's great that conductor ensures that there is always a single instance of a controller with a tag for each router. 
A lifecyclelistener does not have the `onXYZresult` callbacks.

**Comment by MFlisar** [comment]
In my projects I've successfully used this library for that: https://github.com/beworker/featured

And then I just add small modules to my controllers. I can show you a complete example for a lifecycle logger plugin I used in my projects if you're interested in that

**Comment by PaulWoitaschek** [comment]
I created my own scoped form of CompositeAndroid without all the overhead and am using it successfully.
I just let my activity implement an interface so it can provide each module to the controllers that need it.
