### ISSUE TITLE
ActionBar items visible from offscreen controllers with RouterPagerAdapter

### ISSUE THREAD

**Issue by grandstaish** [bluelinelabs/Conductor#244]
I'm using the `RouterPagerAdapter` class from `conductor-support` and noticing that when child controllers define their own options menu (e.g. `setHasOptionsMenu(true)`), that their option menu items are visible when they're either left or right of the currently active tab (e.g. when they're not yet visible).

My goal is to have contextual menu items for each child controller, and have the menu items change as you scroll through the pager. Is this currently possible or is it a bug in the library? 

Note that I've tried setting the ViewPager's offscreen page limit to 0, but it had no effect on this.

**Comment by kevelbreh** [comment]
`RouterPagerAdapter` uses child routers. I'm facing the same issue with attaching / detaching to child routers and the actionbar isn't respecting me menu changes.

**Comment by kevelbreh** [comment]
Looking back at this, child routers should probably know nothing about other child routers menu options. For example, say you have an `activity` displaying two containers. Each `container` interchanges controllers and has to add/remove menu items. The `actionbar` would need to contain both inflated menus from both controllers. 

This may not quite answer the original issue but does add some clarification on my response - assuming this is the intended design.

**Comment by inorichi** [comment]
[Here's a working solution](https://gist.github.com/inorichi/f1be316f815ad7bbd2def112a9f66c5d). I've replicated the logic in Android's `FragmentPagerAdapter` by overriding `setPrimaryItem` and keeping track of the current primary router. There's also a change at the end of `instantiateItem`, same as for fragments.

@EricKuck do you want me to send a PR?

**Comment by EricKuck** [comment]
@inorichi Sorry for the late response. Please do send a PR!
