### ISSUE TITLE
[Question] Add Controller from ViewPager into parent/root Controller

### ISSUE THREAD

**Issue by autovalue** [bluelinelabs/Conductor#252]
I have the following Controllers.
`HomeController` -> `CategoriesController` -> `CategoryDetailsController`.

- `HomeController` contains a viewpager of `CategoriesController`s using `RouterPagerAdapter` (using the demo example).
- Each `CategoriesController` contains a list of categories.
- Clicking a category entry opens up `CategoryDetailsController`.

The issue I'm having is that the new `CategoryDetailsController` adds the `CategoriesController` inside the viewpager, whereas I want it to add it on the `HomeController`/root level instead.

**Comment by autovalue** [comment]
Never mind, just a brain fart. `getParentController().getRouter()` is what I was looking for.

On a sidenote, is there a built in way to cache the `RouterPagerAdapter` views.

One of my viewpager contains a WebView, the WebView gets recreated almost every time which is pretty expensive.

**Comment by shakil807g** [comment]
Retain View Modes

setRetainViewMode can be called on a Controller with one of two values: RELEASE_DETACH, which will release the Controller's view as soon as it is detached from the screen (saves memory), or RETAIN_DETACH, which will ensure that a Controller holds on to its view, even if it's not currently shown on the screen (good for views that are expensive to re-create).

**Comment by autovalue** [comment]
Thanks for the suggestion @shakil807g, I already called `setRetainViewMode(RETAIN_DETACH);` on the Controller to no avail. 

On further debugging, what I needed was actually [`ViewPager#setOffscreenPageLimit(2)`](https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setOffscreenPageLimit(int)).
