### ISSUE TITLE
Blank pages when pushing ontop of a pager adapter

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#256]
When I have set a root controller which contains a pager adapter and push another controller on top, after popping the root controllers pages are not shown and it is completely blank.

This only happens if I add a `ChangeHandler` to the controller I push.

I made a demo here:  
https://github.com/PaulWoitaschek/ConductorPopBug

In the [MainActivity](https://github.com/PaulWoitaschek/ConductorPopBug/blob/master/app/src/main/java/de/paul_woitaschek/conductorbug/MainActivity.java) I add a [ControllerWithPager](https://github.com/PaulWoitaschek/ConductorPopBug/blob/master/app/src/main/java/de/paul_woitaschek/conductorbug/ControllerWithPager.java) that contains a `ViewPager` with a single [Yellow](https://github.com/PaulWoitaschek/ConductorPopBug/blob/master/app/src/main/java/de/paul_woitaschek/conductorbug/Yellow.java) Controller. Immediately I push a [Green](https://github.com/PaulWoitaschek/ConductorPopBug/blob/master/app/src/main/java/de/paul_woitaschek/conductorbug/Green.java) Controller with a `FadeChangeHandler`. When I now pop that `Green` controller I end up with a blank screen. When I however do not add a `FadeChangeHandler` like [here](https://github.com/PaulWoitaschek/ConductorPopBug/blob/master/app/src/main/java/de/paul_woitaschek/conductorbug/MainActivity.java#L25) the `Yellow` page gets displayed correctly.

This bug is very critical to me.

**Comment by EricKuck** [comment]
Thanks for the report! This was a pretty edge-case race condition that I probably would have never found without this.

**Comment by PaulWoitaschek** [comment]
Thanks a lot! It actually took me a while to identify this and break it down to it's essence.

**Comment by PaulWoitaschek** [comment]
Any plans for the next release? Do you think it's safe to use the snapshot in the meantime?
