### ISSUE TITLE
Control the Rotation in Controller class

### ISSUE THREAD

**Issue by nksaroj** [bluelinelabs/Conductor#257]
In the Fragment call inside onResume to lock to portrait:

`getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);`

then in onPause to unlock orientation:

`getActivity().setRequestedOrientation(ActivityInfo. SCREEN_ORIENTATION_SENSOR);`

How would you do the above in Controller for certain views only not for the entire app?

**Comment by nksaroj** [comment]
`    @Override
    protected void onViewBound(@NonNull View view) {
        super.onViewBound(view);
        viewPager.setAdapter(pagerAdapter);
        tabLayout.setupWithViewPager(viewPager);

        getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
    }

    @Override
    protected void onDestroyView(@NonNull View view) {
        viewPager.setAdapter(null);

        getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR);

        super.onDestroyView(view);
    }`

I ended up like above and it works. I am just curious if there is any better way. Thanks

**Comment by nksaroj** [comment]
@EricKuck Any thoughts on this?

**Comment by EricKuck** [comment]
`onAttach` and `onDetach` are the events that are closest to `onResume` and `onPause` for fragments.

**Comment by GeoffGodwin** [comment]
While attempting to lock my second controller to portrait I noticed some rather nasty behavior in my app using the above method. Perhaps one of you can reproduce it:

My first controller is allowed free rotation. I start the app in landscape mode. The second controller is locked to portrait using the above code example given by @nksaroj. When I launch the second controller from the first (still in landscape mode) the screen goes black and I begin an infinite loop of the lifecycle methods in the second controller.

I'm very confused as to what is causing this. At first I thought the call to change orientation was causing the lifecycle to restart so I surrounded it in an if to check and not run it but alas it still destroys and creates indefinitely. Thoughts?
