### ISSUE TITLE
Skip Controller from backstack

### ISSUE THREAD

**Issue by eGorets** [bluelinelabs/Conductor#270]
I have A -> B -> C navigation and I want to behavior on the back pressed action like this - C -> A (B skipped) 

How can I achieve this? 

Thanks for helping

PS
I used workaround like this

    override fun onDestroyView(view: View) {
        super.onDestroyView(view)

        router.popController(this)
    }

**Comment by PaulWoitaschek** [comment]
Then navigating to C instead of `pushController` use `replaceTopController`

**Comment by eGorets** [comment]
Thanks, It works
