### ISSUE TITLE
[Question] Handle back behavior

### ISSUE THREAD

**Issue by JuzTosS** [bluelinelabs/Conductor#272]
I've noticed that if we have only root controller in a router and call handleBack on that router, root controller is removed from the router but the view of the controller isn't removed from the view hierarchy.

What is the purpose of this behavior? IMHO it's unconsistent.

**Comment by EricKuck** [comment]
The purpose is that after you pop the last controller, there's nothing to display. If it's your root router, you should be finishing your activity when this happens. If it's a child router, you should be removing it. If controllers disappeared when you hit the back button the last time, you'd see a really ugly animation as the host activity finishes.

**Comment by JuzTosS** [comment]
We mustn't  pop root controller then.
We could just return false in handleBack() method and don't pop root controller at all 
And everything will be fine.
