### ISSUE TITLE
Unexpected behavior by lifecycle problem (?)

### ISSUE THREAD

**Issue by Mahtalitet** [bluelinelabs/Conductor#273]
**How reproduce it**
Replace root controller in demo to `RxLifecycle2Controller` (not require to use only this implementation, but with Rx it's most obvious to show). And...
_1 variant_. Disable screen (!). After run app from Android Studio in debug mode (shift+F9). Reproduce rate - 100%. [VIdeo here](https://drive.google.com/open?id=0BwUR-zUees3Ramlzb0YwT3lOdms).
_2 variant_. Disable screen (!). After run app from Android Studio (shift+F10) without debug mode. Reproduce rate - 50-70%.
_3 variant_. Run app from icon and immediately collapse it by tap on `Recent Apps` button. Reproduce rate - 70-100%. [VIdeo here](https://drive.google.com/open?id=0BwUR-zUees3RWkdrSlg0V20tRms).
When normal behavior [like that](https://drive.google.com/open?id=0BwUR-zUees3RZGtBamtPN21HRTg). 

**Logs (with trouble)**
1. While screen turned off
```
04-20 21:09:43.114 10033-10033/com.bluelinelabs.conductor.demo E/LOG: preCreateView
04-20 21:09:43.125 10033-10033/com.bluelinelabs.conductor.demo E/LOG: postCreateView
04-20 21:09:43.126 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onChangeStart
04-20 21:09:43.128 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onActivityStarted
04-20 21:09:43.129 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onActivityResumed
04-20 21:09:43.161 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onActivityPaused
04-20 21:09:43.168 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onChangeEnd
04-20 21:09:43.168 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onSaveViewState
04-20 21:09:43.169 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onSaveInstanceState
04-20 21:09:43.169 10033-10033/com.bluelinelabs.conductor.demo E/LOG: preDestroyView
04-20 21:09:43.169 10033-10033/com.bluelinelabs.conductor.demo E/LOG: postDestroyView
04-20 21:09:43.169 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onActivityStopped
```
2. After screen turned on
```
04-20 21:09:52.742 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onActivityStarted
04-20 21:09:52.773 10033-10033/com.bluelinelabs.conductor.demo E/LOG: onActivityResumed
```
**Logs (normal)**
1. While screen turned off
```
04-20 21:05:18.550 2801-2801/com.bluelinelabs.conductor.demo E/LOG: preCreateView
04-20 21:05:18.556 2801-2801/com.bluelinelabs.conductor.demo E/LOG: postCreateView
04-20 21:05:18.557 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onChangeStart
04-20 21:05:18.558 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onActivityStarted
04-20 21:05:18.559 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onActivityResumed
04-20 21:05:18.590 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onActivityPaused
04-20 21:05:18.608 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onChangeEnd

04-20 21:05:18.608 2801-2801/com.bluelinelabs.conductor.demo E/LOG: preAttach
04-20 21:05:18.609 2801-2801/com.bluelinelabs.conductor.demo E/LOG: postAttach

04-20 21:05:18.721 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onSaveViewState
04-20 21:05:18.721 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onSaveInstanceState

04-20 21:05:18.721 2801-2801/com.bluelinelabs.conductor.demo E/LOG: preDetach
04-20 21:05:18.722 2801-2801/com.bluelinelabs.conductor.demo E/LOG: postDetach

04-20 21:05:18.722 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onActivityStopped
```
2. After screen turned on
```
04-20 21:06:33.790 2801-2801/com.bluelinelabs.conductor.demo E/LOG: preAttach
04-20 21:06:33.812 2801-2801/com.bluelinelabs.conductor.demo E/LOG: postAttach
04-20 21:06:33.830 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onActivityStarted
04-20 21:06:33.851 2801-2801/com.bluelinelabs.conductor.demo E/LOG: onActivityResumed
```

Pay attention to Attach/Detach lines.

**Comment by EricKuck** [comment]
I unfortunately haven't been able to reproduce this on a Nexus 6P, 5X, the emulator, or Genymotion. I've been trying with your "While screen turned off" instructions. I wonder if this isn't dependent on the OS. What are you running these tests on?

**Comment by Mahtalitet** [comment]
I ran them on 6.0.1. And on 7.1.2 (5X) reproduced too, but with debug mode only.

**Comment by Mahtalitet** [comment]
How else can I help you find a trouble spot? I can try reproduce this issue on some other devices and versions... And I will try find a concrete commit(s) later. Because it's a critical, I think, as you could see on the video above.

**Comment by EricKuck** [comment]
Finally reproduced! Despite your excellent step-by-step instructions, I was doing it wrong :) Fix incoming!
