### ISSUE TITLE
Controller popping fails with Change Handler

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#274]
This seems similar to #256 but might be related to #266 

If I add / remove multiple Controllers at once, the `popController` does not work.

In my example I first add a `Green` controller as the root controller. Then I push 2 `Red` controllers who both  pop themself immediately when they get attached.

The correct thing would be to show a green screen. With only 1 `Red` controller, or without any `ChangeHandler` this works as expected. Buf if you have multiple, it fails and you see a red screen.

```kotlin
class MainActivity : Activity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val container = findViewById(android.R.id.content) as ViewGroup
    val router = Conductor.attachRouter(this, container, savedInstanceState)
    if (!router.hasRootController()) {
      router.setRoot(RouterTransaction.with(Green()))
      router.pushController(RouterTransaction.with(Red()).pushChangeHandler(FadeChangeHandler()))
      router.pushController(RouterTransaction.with(Red()).pushChangeHandler(FadeChangeHandler()))
    }
  }

  class Green : Controller() {
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup) = View(activity).apply { setBackgroundColor(Color.GREEN) }
  }

  class Red : Controller() {
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup) = View(activity).apply { setBackgroundColor(Color.RED) }
    override fun onAttach(view: View) {
      router.popController(this)
    }
  }
}
```

**Comment by EricKuck** [comment]
I appreciate all these edge-case bug reports. Working on fixes now. I am curious though why you're doing things like this in the first place? Why push, then immediately pop a controller? Why push 3 controllers simultaneously instead of just setting the backstack?

**Comment by PaulWoitaschek** [comment]
It's mostly while developing new features. For example I have a Controller that handles the purchase. In `onAttach` I subscribe to the user stream and once the user is pro I pop the controller.

In this case I added the purchase Controller with all its different modes on top of each other to test it.

Under the regular circumstances I do not suffer from too many issues through conductor. But when I find them I report them because under regular behavior they are quite hard to trigger but sure happen somemtimes.

**Comment by inorichi** [comment]
I've had weird app crashes (in external classes) if I popped a controlled in `onAttach` with `FadeChangeHandler`. It works fine if it's popped inside `onChangeEnded`.

I have a use case where I would like to "abort" a transaction/controller if some data isn't validated (a db query returns null because the object was deleted), so that view creation is skipped and I don't have to add additional checks until `onChangeEnded` is called. But I guess it's not a simple change.
