### ISSUE TITLE
Is there a way to know when animation changes are finished?

### ISSUE THREAD

**Issue by eGorets** [bluelinelabs/Conductor#278]
I have a `Controller` with internet request at the beginning, so it does some freazing of animation. 
How can I add a listener to know when `ChangeHandler` finised into my controller?

**Comment by EricKuck** [comment]
Network requests should never affect the UI, as they happen on a background thread. I'd look into what else is going on there that could cause issues.

Regarding your question, there's a `onChangeEnded` method you can override in your controller.
