### ISSUE TITLE
HorizontalChangeHandler incorrect animations inside ViewPager

### ISSUE THREAD

**Issue by sewar** [bluelinelabs/Conductor#279]
HorizontalChangeHandler in a child router inside ViewPager breaks when popping controller.

To reproduce:
1. Apply [this patch](https://gist.github.com/sewar/19bff9505cb51427de0070d17d5d4568).
2. Open ViewPager demo.
3. Select any tab/page other than the first.
4. Click next button, the older controller animates out to the left side.
5. Click back, the older controller animates back from the right side.

This is related to changes in 44bcd0f, it works fine when `fromLeft = 0`.

**Comment by EricKuck** [comment]
Thanks for the easy to reproduce issue!
