### ISSUE TITLE
[Question]How well conductor works with other UI controls?

### ISSUE THREAD

**Issue by nksaroj** [bluelinelabs/Conductor#284]
Hi,
 We are looking go build a new app and our entire team is unsure about conductor.
It would be great if anyone can able to answer few questions.

1. How Conductor works well with other android controls considering conductor life cycle is different to standard android lifecycle. Let us assume we ll try to use any third party libraries for UI such as MPAndroidChart which follows the standard android lifecycle .

2. Where I could find very comprehensive documents apart from annoying good bunch of people in issues sections?
 
3. Is there any active members to help-out in stackoverflow if any issues.

4. Can anyone please share their pain points if any using Conductor ? Let us be very honest :)

5. Can anyone share the list of app names been using conductor library?
   It's just to give some confidence in my team to encourage to use conductor.

**Comment by EricKuck** [comment]
1) There shouldn't be any issues with 3rd party views. Google's MapView is the only one I know of that's extremely coupled to activity/fragment lifecycle, and it works great with Conductor (see https://github.com/bluelinelabs/Conductor/issues/109#issuecomment-244774282).

2) The best docs are in the readme and in the demo app for now. Hopefully more will be out in the future. The demo app should have examples of just about anything you'd want to do.

3) I haven't been too active on stackoverflow, but I'll monitor the [conductor] tag if you have issues. I'm sure others can help out as well.

4) I made the lib, so I'll pass on this one.

5) Lots of apps use it. Reddit, theScore, KeepSafe, and GasBuddy are probably the biggest. Material Audiobook Player by @PaulWoitaschek is open source and it's a great reference if you need something beyond the demo.
