### ISSUE TITLE
2.1.3 deferrs onAttach

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#285]
With conductor 2.1.3 all my shared elements animations are broken because I set the transition names in `onAttach`. 

It seems that `onAttach` is now kind of deferred till after it's actually attached.

**Comment by EricKuck** [comment]
It does indeed call `onAttach` after the attach actually happens now. Without this change, there was an unavoidable NPE in Android's ViewGroup class in your previous example (#274).

I believe transition names should have always been set when the view is created instead of in `onAttach` anyway. Just as there's no contract with Android's `onAttachedToWindow` call saying it will happen at a certain point in the attach process, there's no contract in Conductor saying when that call will happen. Your code could have broken in the next version of Android anyway. Logically `onAttach` _should_ be called when the view is fully attached, not at an arbitrary point in the attach process.

**Comment by inorichi** [comment]
One change I've noticed when upgrading from 2.1.2 to 2.1.3 is that a `RecyclerView`'s layout manager isn't automatically restoring the scroll position when the view is restored after a rotation or controller pop.

The only requirement in 2.1.2 was to have a unique id set for the `RecyclerView`. Now it always stays at the top after a rotation.

I'll try to further investigate this new behavior.

**Comment by EricKuck** [comment]
Closing as the conversation has moved to #287 anyway.

**Comment by PaulWoitaschek** [comment]
I'm quite puzzled right now on how to setup MVP with conductor.

I want my presenter to get attached after the view was created and detached when it was destroyed.
However I cannot do that in onCreateView because the viewstate is not restored yet.

When I do so every change to the controller I make gets overwritten when the saved state gets restored.
But on the other hand I can't do it in `onRestoreViewState` because if there is no saved state, that callback won't get called.

**Comment by EricKuck** [comment]
It'd suggest using `RestoreViewOnCreateController` in that case. The `onCreateView` method includes the `savedViewState` bundle. The next major version of Conductor will include this in the main Controller class, but it wasn't possible to do this without a breaking API change.

**Comment by PaulWoitaschek** [comment]
But the view state is not restored in `onCreateView` yet. So you suggest to attach the presenter in `onCreateView` if the saved state is null and else in `onRestoreViewState`?

**Comment by EricKuck** [comment]
Ah sorry, I hadn't fully understood your question before answering. I guess I've never run into that problem, but yes, I suppose attaching it in one of those two places would be the solution. It sounds like your presenter and view state have opposing state data for the view? I'm curious why this would be the case.

**Comment by PaulWoitaschek** [comment]
1. Presenter sets a switch to ON
2. User turns switch off
3. Network call is made so that change is reflected in the api
4. Network call fails but user already navigated somewhere else
5. User returns and view gets restored. First presenter sets the state to ON because the OFF command was not sent to the backend successfully
6. View gets restored and overwrites the just set value

**Comment by PaulWoitaschek** [comment]
It would be great if that parameter could be added to the change listener too in a future version. Right now I have to overwrite it in my base controller and make it final and have an alias for all child controllers.

**Comment by dimsuz** [comment]
@PaulWoitaschek you might want to check how `mosby-conductor` library does this. I use it and never had any problems, though my use cases might be different.

IIRC it attaches view to a presenter upon some lesser known lifecycle event, something like onPostCreateView. On mobile now, hard to find the exact spot for you... :)

**Comment by PaulWoitaschek** [comment]
@dimsuz That's the same issue, it also attaches the presenter before the view state was restored. (Actually exactly 1 line before it get's restored).
