### ISSUE TITLE
Incorrect animations when using popToTag and HorizontalChangeHandler(false) - Version 2.1.3

### ISSUE THREAD

**Issue by King-Henry** [bluelinelabs/Conductor#286]
Hey, we are using Conductor in our application and happened to notice some odd animations when using the popToTag method with HorizontalChangeHandler(false). This seems incorrect, but we are not quite sure so we were hoping for some more information on this. We are new to this library.

1. Push controller with HorizontalChangeHandler(false) as the push change handler.
2. Push N >= 1 controllers with HorizontalChangeHandler().
3. Initiate popToTag from the top of the controller stack to another controller.
4. When popToTag is initiated, the animation to the controller you are going to happens incorrectly.

You can simulate this in your sample app by changing line 170 in HomeController.java from `.pushChangeHandler(new FadeChangeHandler())` to `.pushChangeHandler(new HorizontalChangeHandler(false))`
, pressing "next controller" a couple times, then pressing "go up".

This also causes an incorrect animation when popping to root using the same `.pushChangeHandler(new HorizontalChangeHandler(false))`:

1.  Press "Navigation Demo"
2.  Press "Pop To Root"
3.  Root controller animation does not slide in like it should.

**Comment by EricKuck** [comment]
Thanks for the easy to reproduce steps! This should now be fixed in the latest snapshot build.
