### ISSUE TITLE
[Question] Any way to keep a video playing (ExoPlayer) during an orientation change? 

### ISSUE THREAD

**Issue by josecalles** [bluelinelabs/Conductor#289]
I have a Controller that holds a SimpleExoPlayerView. I begin the playback on `onAttach` and release the player on `onDetach`. From my understanding, Conductor destroys and recreates the view during an orientation change, so would keeping a video playing though an orientation change even be possible?

**Comment by PaulWoitaschek** [comment]
Start the playback in the first onCreateView and stop it in onDestroyView, but only if not activity.isChangingConfigurations.
And set the surface in onCreateView each time.

**Comment by josecalles** [comment]
Thanks for the response! The only issue I'm having is that SimpleExoPlayerView comes with an immutable SurfaceView out of the box so I can't set it during `onCreateView`. The following is what I have at the moment. 

    class PlayerViewController(): BaseController() {

        @BindView(R.id.exo_player_view)
        lateinit simpleExoPlayerView: SimpleExoPlayerView

        private videoUri: Uri = Uri.parse("video_sample_uri")  

        override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View {
            //Calls onViewBound(view: View) when views are bound  
            return super.onCreateView(inflater, container)
        }


        override fun onViewBound(view: View) {
            simpleExoPlayerView.player = createPlayer()
            simpleExoPlayerView.player.playWhenReady = true
            simpleExoPlayerView.player.prepare(getMediaSource(withUri: videoUri))
        }    


        override fun onDestroyView(view: View) {
           super.onDestroyView(view)
           if (activity?.isChangingConfigurations == true) {
                return
           } else {
                simpleExoPlayerView.player.release()
                simpleExoPlayerView.player = null
        }

    }

**Comment by PaulWoitaschek** [comment]
That with the surface view applies only if you are using SimpleExoPlayer.
You are using a view directly. So make sure to only create your player once. The ExoPlayerView will handle the surface attaching / detaching through a holder automatically.

```kotlin
class Controller {
  var player : SimpleExoPlayer? = null
  fun onViewBound() {
    if(player == null) {
      // init and start playback 
    }
    exoView.player = player
  }
```

**Comment by josecalles** [comment]
That did the trick thanks! I've noticed that the video image stalls for 2-3 seconds while the audio continues to play on rotate. I know this is beyond the scope of the initial issue, but I was just wondering if you've experience something similar.

**Comment by PaulWoitaschek** [comment]
Yes, there is no way around this except of handling configuration-changes yourself.
