### ISSUE TITLE
SharedElement transition not working with DataBinding

### ISSUE THREAD

**Issue by The0ldM0nk** [bluelinelabs/Conductor#290]
I have tried to extend Conductor Demo App with Android DataBinding in the same way ButterKnife is present in the Demo App i.e. with a base controller which take care of view binding and another controller which integrate Canary API.

Databinding works fine but shared element transition is broken. I tried this with a layout similar to below for both controllers:

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">

    <data>

        <variable
            name="viewModel"
            type="demo.conductor.databinding.HomeControllerModel" />
    </data>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <TextView
            android:id="@+id/text_view_0"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="5dp"
            android:layout_marginRight="5dp"
            android:text="@{viewModel.userOption}"
            android:textAllCaps="false"
            android:transitionName="@string/transition_home_screen_feature" />

    </FrameLayout>
</layout>
```

But it is not working.
I am using the following changeHandlers:

```
.pushChangeHandler(new TransitionChangeHandlerCompat(new SharedElementDelayingChangeHandler(names), new FadeChangeHandler()))
.popChangeHandler(new TransitionChangeHandlerCompat(new SharedElementDelayingChangeHandler(names), new FadeChangeHandler())))
```

Did I miss something? Any help is appreciated

**Comment by EricKuck** [comment]
I've never used databinding, so I don't have any real advice for this question. If you'd like to share a forked repo where Butterknife is replaced by Databinding I'd be happy to take a look and help debug though!

**Comment by The0ldM0nk** [comment]
@EricKuck Thanks for the reply.
This might be relevant to #291.

I have noticed that adding `padding` is the key which fixes it. Unfortunately this is an unmarked bug present in Design Support Library v.24.2.1.

I'd happy to contribute to Conductor; but I am just not ready yet for the time being :)

**Comment by The0ldM0nk** [comment]
@EricKuck [Here](https://github.com/The0ldM0nk/Conductor/tree/integration-android-databinding) are some short additions I have prepared to reproduce this bug.

For the sake of simplicity, I haven't removed the existing ButterKnife integration.

**Comment by The0ldM0nk** [comment]
has anyone tried Conductor API together with android databinding?

**Comment by AllanHasegawa** [comment]
a



m

**Comment by The0ldM0nk** [comment]
upstream rebase and voila' 😬
