### ISSUE TITLE
remove page programmatically from RouterPagerAdapter

### ISSUE THREAD

**Issue by Kyba1985** [bluelinelabs/Conductor#292]
Hi, i have a gallery on controllers in RouterPagerAdapter. Each one must show an image, that use a model to find the source from local file or from http url. My problem is can't find a solution to delete a controller from RouterPagerAdapter. I know that i must use this method for handle the change in position when notifydatasetchanged is called:

@Override
            public int getItemPosition(Object object) {
                return super.getItemPosition(object);
            }

but i can't find the correct way to remove the visible page from viewpager. Any suggestions?

**Comment by serjooo** [comment]
I could think of multiple solutions. One approach might be to remove one of the Controllers from your list and notify the `RouterPagerAdapter` that the `DataSetChanged()`.  Another thing you could do if it is `TabLayout` you can call `remotTabAt(int position)`. Now I haven't tried it personally but this is the approach I would personally take.

**Comment by EricKuck** [comment]
As @serjooo mentioned, you'd simply remove the data from whatever backing structure you have and call `onDataSetChanged()`. This isn't a question that's relevant to Conductor, as it applies to any view pager.

**Comment by Kyba1985** [comment]
Thanks for the reply, the solution posted by @serjooo don't works. the viewpageradapter is different from normal adapter, and i tried it before post my issue. 

The solution that i found is customize the behavior of routerpageradapter. 

The piece of code where i can remove controller from adapter is: 

@Override
            public int getItemPosition(Object object) {
                Router selected = pages.get(positionLastImageRemoved);

                if (selected != null && selected.equals(object)) {
                    pages.remove(positionLastImageRemoved);
                    positionLastImageRemoved = -1;
                    return POSITION_NONE;
                } else
                    return super.getItemPosition(object);
            }

pages is hashmap that contains position and Router: 
HashMap<Integer, Router> pages = new HashMap<>(); 

when i deleted an element call notifydatasetchanged and whit this custom getimetposition the controller go away and the next is shown.
