### ISSUE TITLE
Transparent Controller

### ISSUE THREAD

**Issue by ReginFell** [bluelinelabs/Conductor#294]
Hi everyone! 

I ran into problem, I need to one Controller to be overlay another Controller, but first one must be partially visible. 
Is there possibility to create partially transparent Controller? 

I think a lot about this problem and only way that I invented, is to create ViewGroup overlay and use childRouter instead of base router, but it doesn't look good actually. Maybe there is some mechanism for this purpose?

**Comment by EricKuck** [comment]
There's an example of this in the demo app. Check out how the dialog controller is displayed when you click the toolbar button. The dialog itself is a controller that sounds similar to what you're trying to do.

**Comment by ReginFell** [comment]
Found it, thanks a lot!

**Comment by MkhytarMkhoian** [comment]
It's not so good solution because you have extra overdraw

**Comment by dimsuz** [comment]
I thought about this too and had 2 options in mind:

1. Show solid background only while change is running. This can be automated somehow
2. Remove `windowBackground` from Activity. This way overdraw will be present only when transitionning. But this has the drawback that while Activity is starting, it will be transparent for a brief moment of time. Again: maybe remove windowBackroung only after Router is set up.

Both are hacky enough, maybe there's something cleaner...
