### ISSUE TITLE
Bottom sheets Components

### ISSUE THREAD

**Issue by nksaroj** [bluelinelabs/Conductor#296]
After digging through the Conductor samples , I noticed that there is no Dialog Fragments. It's just another controller with just style and layout changes and it hides the entire background view(Navigates to other controller with big paddings around).I am looking to build and equivalent of Bottom sheets Components with help of controller.On the UX side, the user will have option to choose from a list of items from the bottom of the view. I am looking to keep the background transparent and the bottom sheet should animate from bottom. It would be great if anyone can share some samples

**Comment by nksaroj** [comment]
I manage to end-up of doing the following and seem to be very close to working...It is exactly same as Dialog Fragment and mainly position to the bottom of the screen.



> <?xml version="1.0" encoding="utf-8"?>

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/dialog_window"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <View
        android:id="@+id/dialog_background"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/immersive_background" />

    <ScrollView
        android:id="@+id/dialog_container"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_gravity="bottom"
        android:background="@drawable/dialog_bg"
        android:elevation="@dimen/dialog_elevation"
        android:fillViewport="true"
        android:orientation="vertical"
        android:transitionName="@string/fab_dialog_transition_name">

        <ListView
            android:id="@+id/list"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"></ListView>

    </ScrollView>


</FrameLayout>

Below is the controller code where Only I need to return the result to parent from target controller which I've not done but it is very easy to do.

> 

package com.bluelinelabs.conductor.demo.controllers;
import android.support.annotation.NonNull;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import com.bluelinelabs.conductor.demo.R;
import com.bluelinelabs.conductor.demo.controllers.base.BaseController;
import butterknife.BindView;
import butterknife.OnClick;

public class BottomSheetController extends BaseController {
    @BindView(R.id.list)
    ListView listView;
    // Defined Array values to show in ListView
    String[] values = new String[] { "Android List View",
            "Adapter implementation",
            "Simple List View In Android",
            "Create List View Android",
            "Android Example",
            "List View Source Code",
            "List View Array Adapter",
            "Android Example List View"
    };
    @Override
    protected View inflateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
        return inflater.inflate(R.layout.controller_bottom_sheet, container, false);
    }
    @Override
    public void onViewBound(@NonNull View view) {
        super.onViewBound(view);
        ArrayAdapter<String> adapter = new ArrayAdapter<>(getApplicationContext(),
                android.R.layout.simple_list_item_1, android.R.id.text1, values);
        // Assign adapter to ListView
        listView.setAdapter(adapter);
    }
    @OnClick({R.id.dialog_window})
    public void dismissDialog() {
        getRouter().popController(this);
    }

    @Override
    public boolean handleBack() {
        return super.handleBack();
    }
}

It is appreciated if anyone is agree with my approach. Thanks

**Comment by EricKuck** [comment]
This looks like a good approach. With the right change handler it should look right. The transition name isn't needed, and I'd probably use a RecyclerView over a ListView, but those are minor changes.

Also note that you could just use the standard bottom sheet component if you wanted to. There's no requirement to reimplement things as controllers, although it can simplify some things to do it this way.

**Comment by nksaroj** [comment]
Thanks @EricKuck . Agree It's not
