### ISSUE TITLE
[Proposal] More Null safety with JSR 305’s @ParametersAreNonnullByDefault

### ISSUE THREAD

**Issue by lenguyenthanh** [bluelinelabs/Conductor#297]
Just read Jesse Wilson blog: https://medium.com/@swankjesse/non-null-is-the-default-58ffc0bb9111. I think it's a really good way to make the library have better Null safety.

**Comment by EricKuck** [comment]
This won't do anything to help null safety, as `@NonNull` and `@Nullable` are already used throughout the library. What this does do is reduce boilerplate and make the code more readable, so we'll look at making this transition soon. Thanks!
