### ISSUE TITLE
Communication between child controllers  

### ISSUE THREAD

**Issue by SaeedMasoumi** [bluelinelabs/Conductor#298]
I read this [issue](https://github.com/bluelinelabs/Conductor/issues/115), But if I have a `ParentController` and it has two sibling child controllers and these children want to communicate with each other, So how can I achieve this?

**Comment by nksaroj** [comment]
You could use rxJava to communicate between them or use interface pattern. Which  is very common in Android simalr to fragment communication

**Comment by SaeedMasoumi** [comment]
I know these patterns, but i think maybe there is a built-in feature in controllers which make this communication easier

**Comment by EricKuck** [comment]
The built-in feature for this is `setTargetController`, as was mentioned in the issue you linked to. The way I prefer to use this is to have a constructor on the controller that takes a target controller and enforces a certain interface for it to conform to. As @nksaroj mentioned, rx is a great way to handle this too!
