### ISSUE TITLE
[Discussion] Controller constructor validation and Bundle helper

### ISSUE THREAD

**Issue by cs-victor-nascimento** [bluelinelabs/Conductor#3]
Controllers that call super(bundle) directly don't pass validation. This makes the API more verbose. I know it is not good to try and find constructors in super types but we could have an initialization flag to know if those were called.

Also, there could be a generic Controller builder that would substitute the BundleBuilder helper. This could ease a bit the API. Something like:

```java
Controller.newBuilder(AController.class).putInt(KEY_SMTG, value).putString(KEY_SMTG_ELSE, anotherValue).pushChangeHandler(new DifferentChangeHandler()).toRouterTransaction();
```

If the idea is somewhat valid I can send a WIP PR to better show the interface.

**Comment by cs-victor-nascimento** [comment]
Oooooops... hit send accidentally...

**Comment by EricKuck** [comment]
I've actually been thinking of moving to more of a Fragment-like API, where the recommendation would be to create a static `newInstance()` method instead of using custom constructors. After doing a few projects that use Conductor, it feels a little weird to always have a custom constructor and a bundle constructor. What do you think about this change? It wouldn't really change anything in the library itself, just the recommended usage.

**Comment by EricKuck** [comment]
Also, I forgot to mention - the reason the bundle constructor needs to be present in your class, rather than in a super class, is so Conductor can restore your Controllers when Android kills your process. Simply calling `super(bundle)` isn't enough...each Controller actually needs to have either a `Controller()` or `Controller(Bundle bundle)` constructor. This is the same reason that Fragments have to have a default constructor.

**Comment by cs-victor-nascimento** [comment]
Yeah I know that the constructors are called reflectively during recreation. 

IMHO it is not a good idea to follow the fragment approach for some reasons:
1. It is not a standard but more like a recommended practice throughout Google's documentation.
2. I think that 99% of the time people will use a custom constructor to delegate to a bundle configuration since there are other callbacks available to do real initialization work in the controller that would depend on views for example. 
3. Most of the time people will create a controller only to create a transaction (at least from my noob point of view atm). Making this a 2-step seems unnecessary and making a 2-step with the need for a bundle constructor even more strange. This could be comboed in a builder-like API that could have a `toRouterTransaction()` and a `build()`  methods for example.

If you demand only an empty constructor (like fragments) and provide some builder-like API for building the bundle I believe you get a nicer implementation. The disadvantage being that all constructors declaration inside a Controller would not have a bundle available for doing any customizations (getArgs() would return an empty bundle in the constructor).

So, right now I have something like this:

```java
public class SomeController extends Controller {

    private static final String KEY_IMAGE = "SomeController.image";
    private static final String KEY_TEXT = "SomeController.text";
    
public SomeController(@DrawableRes int mainImage, @StringRes int descriptionText) {
           // there is a builder here already!
           this(new BundleBuilder(new Bundle())
                .putInt(KEY_IMAGE, mainImage)
                .putInt(KEY_TEXT, descriptionText)
                .build());
    }

    public SomeController(Bundle args) {
        super(args);
    }
    // ...
}
```

And I use it like this:

```java
getRouter()
    .replaceTopController(RouterTransaction
                                .builder(new SomeController(mainImage, descriptionText))
                                .build());
```

IMHO this is better:

```java
public class SomeController extends Controller {

    public static final String KEY_IMAGE = "SomeController.image";
    public static final String KEY_TEXT = "SomeController.text";

    // ...
}

// ... probably need a better name...
getRouter()
    .replaceTopController(Controller.builder(SomeController.class)
                                               .putInt(SomeController.KEY_IMAGE, mainImage)
                                               .putInt(SomeController.KEY_TEXT, description)
                                               .toRouterTransaction());
```

You would need to have an initArgs method or something like it to set the args bundle and generate the instanceId (which perhaps is better to use `System.identityHashCode(object)` but I really can`t say because haven`t looked where it is used).

This is all just some crazy thoughts! It is very likely that I am not seeing the whole picture here and if that is the case, I am sorry and beg for your patience. Since this is only a discussion, feel free to close the issue if you want.

**Comment by EricKuck** [comment]
Haha no need to apologize. I love the feedback. You're right on `newInstance` - people can do that if they want, but whether or not that's the recommended usage doesn't really matter.

The idea of a builder makes a lot of sense for the way you (most people?) use Bundles. I might be in the minority on this, but I personally prefer to expose a constructor that takes the stuff a controller needs, then let the controller itself figure out how it wants to be bundled. To me at least, this is a little cleaner, ensures you'll always have all the data you need, and allows me to keep all my bundle keys private. With a controller builder, it would be possible for a controller that's used in 20 places to be missing a `putInt` call in one place and totally screw stuff up.

All that being said, I agree there's a certain level of awkwardness with the current API and would love to keep this discussion going.

**Comment by sockeqwe** [comment]
>  With a controller builder, it would be possible for a controller that's used in 20 places to be missing a putInt call in one place and totally screw stuff up.

+1 Exactly! That is the main reason a constructor should be used! 

However, I think that with annotation processing we could reduce writing that "boilerplate code" (write / read arguments into / from bundle). I have written an annotation processor called [FragmentArgs](https://github.com/sockeqwe/fragmentargs) which generates "builders" for fragments that will write / read things into / from bundle. I think the key components of FragmentArgs processor could be shared. 
What do you think? If yes, we should open a new issue for that an continue the discussion there (i.e. FragmentArgs also supports optional arguments).

**Comment by EricKuck** [comment]
@sockeqwe That would be fantastic. I actually started looking at what it would take to make something similar for Controllers a few days ago and was using your repo as a reference. I'll open another issue for that now.

@cs-victor-nascimento What do you think about this solution? It seems like it should fit your needs as well, right?

**Comment by cs-victor-nascimento** [comment]
I think that having everything you need in the constructor to avoid forgetting some input to your bundle is nice. I haven't thought about that. I see the benefit but I still think the API of having at least 2 constructors declared when you want to pass in your data is strange. It gets weirder once you find out that the constructor with the arguments have to call `this(bundle)` and not simply `super(bundle)`. 

The builder approach though does not have to override what is currently working. I think they can live along just fine.

It seems that a lot of things in Android are trying to go the processor way (some say this is cheating heheh). I guess this should be another discussion, but I believe if that ever comes to be, it should be on a separated dependency. To me, applying a processor only for building controllers might be a killer.

**Comment by EricKuck** [comment]
Agreed. The annotation processor would definitely be a separate project. The constructor doesn't necessarily have to call this(bundle), it just makes it a little easier to have one place where your local fields are extracted. You could call super(bundle), then extract them elsewhere.

**Comment by cs-victor-nascimento** [comment]
If we have a custom constructor we should also include an empty or bundle constructor and I agree with you that using this(bundle) makes it more readable. I think I am getting used to it by now. 

Still, `BundleBuilder` and some other builder like helpers could be part of the library or, at least, be part of a utils package. I don`t see people not coming to some similar implementation in real apps.

I think we can all agree that there is not much we can do with this issue and I believe it was a good discussion so I`ll close this now. If this come back again in the future we can reopen a fresh discussion.
