### ISSUE TITLE
[Question] Should parentController be set in the backstack after process death?

### ISSUE THREAD

**Issue by tikimcfee** [bluelinelabs/Conductor#300]
Hey there!

Quick question for ya regarding parentControllers and their interaction with the back stack. Specifically, when a parent controller is expected to be accessible (non null) from within the backstack.

The scenario is this:

```
-> Top level controller w/ childRouter backstack :
	--> controller 1
	--> controller 2
	--> controller 3
```

When the controllers are first pushed onto the stack, everything seems honky dorey. I'm able to access the parent controller with getParentController().

In testing some lifecycle stuff, in this case a full app-process-death, I found out that this happens:

```
(app activity restarts from background death)

-> Top level controller w/ childRouter backstack :
	--> controller 1 (no parent controller; null)
	--> controller 2 (no parent controller; null)
	--> controller 3 (no parent controller; null)

--- back press ---

-> Top level controller w/ childRouter backstack :
	--> controller 1 (no parent controller; null)
	--> controller 2 (parent controller is set)
```

It looks like the parent controller is only set during a change handling transaction. The workaround I have for this now seems to be just fine - I'm setting the targetController on child pushes instead of relying on parentController - but it was definitely a curiosity. What do ya think - weird edge case, or totally expected?

Happy to give some more details if ya need!

**Comment by EricKuck** [comment]
Great catch! This should be fixed now in the latest snapshot. Thanks!
