### ISSUE TITLE
[Bug] Two controllers are displayed simultaneously

### ISSUE THREAD

**Issue by JuzTosS** [bluelinelabs/Conductor#303]
The bug is hard to reproduce, but I created a test app.
https://github.com/JuzTosS/ConductorBug

**Behaviour of the application:**
The first controller is set as root.
The second controller is pushed to backstack in 5 seconds.

**Device:** Samsung Galaxy S6, Android 6.0.1
Conductor version 2.1.2 - 2.1.3

**Preconditions:**
Enable **don't keep activities** option in the developer menu.

**Steps to reproduce:**
1. Launch the app
2. Press the power button (screen is black)
3. Wait more than 5 seconds (The second controller will be attached in background)
4. Press the power button again (application is visible)
5. Press home button (Application has gone to background)
6. Launch application again
7. Both controllers are visible at the same time. For both of them onAttach is called. And both of them are on the screen.

**Comment by EricKuck** [comment]
Thanks for the easy to reproduce report. This should be fixed in the latest snapshot build.
