### ISSUE TITLE
[Feature] Ability to set tags for routers dinamycally

### ISSUE THREAD

**Issue by JuzTosS** [bluelinelabs/Conductor#305]
I'm working on RouterPagerAdapter with ability to add and remove pages dynamically.
But the `tag` field is private in the `ControllerHostedRouter` and that doesn't let me to add or remove pages the "clean" way.

I would like to have a public setter for tag in `Router` class.
```
pubic void setTag(String tag) {
    ...
}
```

I would like to create a pull request if you approved the feature.

**Comment by EricKuck** [comment]
Sorry for the late response, but pages shouldn't be removed by simply taking away their routers. The pages would come back when the user scrolled enough anyway. Pages should be removed using the standard ViewPager API of removing whatever backing data is there and calling `notifyDataSetChanged()`.

**Comment by EricKuck** [comment]
Feel free to reopen this if there's another use for adding tags to a router, but I can't think of one.
