### ISSUE TITLE
views in controller remains attached to root after pop root controller

### ISSUE THREAD

**Issue by Kyba1985** [bluelinelabs/Conductor#306]
Hi,
i have 2 layouts , each one with its router. One is for the normal navigation in the application, another is for a controller that must be upon the others, like youtube does. 
the layout: 

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <FrameLayout
        android:id="@+id/fl_root_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    </FrameLayout>

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/fl_playList_root_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    </android.support.design.widget.CoordinatorLayout>

</FrameLayout>

My problem is that after i popped the controller from his root with: 

public Router getPlayerRouter() {
        return routerPlayList;
}

((MainRouterActivity) getActivity()).getPlayerRouter().handleBack();

the controller goes away, but the views of the layout after a layout orientation change returns on the screen. I can't explain why it happened. 

The Main activity has 
android:configChanges="keyboardHidden|orientation|screenSize"

all the app with the other router works without problems.

**Comment by EricKuck** [comment]
This is by design. You normally don't want the last view in a router to disappear when you hit the back button, as that would make the Activity's `finish()` animation look really bad. To handle special use-cases like yours, you'd have to handle the case where `handleBack()` returns false by removing the view from the container ViewGroup.

**Comment by Kyba1985** [comment]
Thanks for the replay, yes two minutes ago i did add these lines of codes,

in the main activity router:

    public void popRootAndClean() {
        routerPlayList.popCurrentController();
        clPlayListRootContainer.removeAllViews();
    }

The important thing is the motivation of this behavior , thanks.

**Comment by EricKuck** [comment]
Sorry, I just realized I totally spaced on the correct answer for this question. You can call `Router.setPopsLastView(true)` when you're initializing it instead of calling `removeAllViews()` on the container!
