### ISSUE TITLE
Router.handleBack() returns false when root controller is popped

### ISSUE THREAD

**Issue by kboyarshinov** [bluelinelabs/Conductor#31]
When root controller is being popped in [`handleBack()`](https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/Router.java#L75) and controller does not handle back press, `popCurrentController()` returns `false` because backstack became empty after popping happened and thus `handleBack()` returns `false`. It means that router did not handle back press when it actually did by doing pop.

It works well when root controller is on root view within activity. But in my case I have root view without any Router attached and its child View with backstack controlled by Router:
```
+----------------------------------------+
|                  +-------------------+ |
|                  |                   | |
| Root View        | Child View with   | |
| that controls    | attached Router   | |
| its child        | and backstack     | |
| (without own     |                   | |
| backstack)       |                   | |
|                  |                   | |
|                  |                   | |
|                  |                   | |
|                  +-------------------+ |
+----------------------------------------+
```
So when back pressed on activity I expect it to be consumed by child View's Router even if only root controller left in backstack.

Btw thank you for the library!

**Comment by EricKuck** [comment]
Good point. I suppose in this case it should always return `true` and the developer should be expected to something like this in their `onBackPressed()` method:

```
if (!router.handleBack() || !router.hasRootController()) {
    super.onBackPressed();
}
```

This feels a little weird though. Anyone have suggestions for a better approach?

**Comment by JakeWharton** [comment]
That's exactly what our view coordinator requires except its only one
method call.

**Comment by EricKuck** [comment]
@kboyarshinov Maybe I'm not totally understanding your use case. What exactly makes it not work as well when the router is a child to some larger view? If `handleBack()` returns false, that basically means the router is now has nothing left to display and that you should handle that. Isn't that what you'd want?

**Comment by kboyarshinov** [comment]
@EricKuck My case is to handle back presses with child backstack and hide its root view when backstack is empty. But this is what happens:
- Router.handleBack does not consume last back press with root view, returning false (this issue). It forces my activity to close although it should not.
- Commenting `super.onBackPress()` should at least hide a view, but [because view is root](https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/Router.java#L501) it does not happen. I handle it with `ControllerChangeListener` added to Router, when change ends I check backstack size and remove view manually. This is ok actually.

> I suppose in this case it should always return `true`

Agreed. This behavior should be expected. `handleBack` implementation may look like that for this case:
```
public boolean handleBack() {
    if (!mBackStack.isEmpty()) {
        if (mBackStack.peek().controller.handleBack()) {
            return true;
        } else {
            popCurrentController();
            return true;
        }
    }

    return false;
}
```

>  the developer should be expected to something like this in their onBackPressed() method:
```
if (!router.handleBack() || !router.hasRootController()) {
    super.onBackPressed();
}
```
This feels a little weird though. Anyone have suggestions for a better approach?

Thats a bit more work from developer side. Since the case with single root view is much more general than mine or any Master-Detail variation, probably overloaded `handleBack(boolean popRoot)` may be the option:
```
public boolean handleBack() {
    return handleBack(false)
}

public boolean handleBack(boolean popRoot) {
   ...
}
```

**Comment by EricKuck** [comment]
I think the way it currently works is actually correct. It returns false to signal that you should do something to handle the back event. 

It sounds like your issue is that the Activity is finishing when `handleBack()` returns false. If you don't want this to happen, and instead just want to hide the view that it's contained in, why not just change your `onBackPressed` implementation to do that? Something like:

```
    @Override public void onBackPressed() {
        if (!mRouter.handleBack()) {
            if (containerViewIsShowing()) {
                hideTheContainerView();
            } else {
                super.onBackPressed();
            }
        }
    }
```

**Comment by kboyarshinov** [comment]
That's what I do now already. I thought that returning `false` is incorrect when root controller is popped from backstack even if View is still visible.

Probably this behaviour needs to be mentioned in documentation to clarify any possible issues.
