### ISSUE TITLE
Controller "lost" after Config Change

### ISSUE THREAD

**Issue by cody1024d** [bluelinelabs/Conductor#311]
I have the following Router/Controller scenario:

**Controller A** -> Has a child Controller (Controller B) through a RouterPagerAdapter

**Controller B** -> A button press here creates Controller C, and attaches it to the parent controller's router (this is to display it as a dialog, as I want it over the tab view that Controller A displays)

**Controller C** -> This is the "full-screen-dialog" controller.  It has a Target Controller set to Controller B (in order to perform callback behavior)

In the following scenario, in the happy path, all works as intended.  Controller C pops up, you enter some information, hit "save" and Controller B is called via the TargetController reference and all is well.

However, if a configuration change has occurred, it seems Controller B is not kept around.  Specifically, TargetController is null on Controller C, AND looking back up to parent controllers, they no longer have the correct references in their childRouter property.  Specifically, I would expect to a backstack of Controller A and Controller C, with Controller A having a childRouter which ends up pointing to Controller B.

**Comment by cody1024d** [comment]
Let me know if a demo project of some sort would help exemplify what I'm seeing

**Comment by EricKuck** [comment]
This is super weird. I've tested stuff like this quite a bit, so there must be something slightly different about the way you're doing it than what I've been doing. If you can add a demo project that would be super helpful!

**Comment by cody1024d** [comment]
Yeah in the most basic of test-projects, it seems to be working completely as intended.  I'm going to dig a bit deeper via the debugger, and see if I can't uncover what's happening in the main project.  Unfortunately I can't just give you the larger project as it's for my 9-5 gig.  I'll respond here, one way or the other, when I figure something out

**Comment by cody1024d** [comment]
@EricKuck 

This was a total mistake on my part.  At some point during development of this project, I guess in hopes of suring-up memory leaks someone nulled-out ControllerA's adapter during destroy, which makes sense that it won't have reference to any of it's children when the state is saved.  Closing this, and the egg is on my face for even opening this issue, for sure lol.
