### ISSUE TITLE
Controllers without backstack?

### ISSUE THREAD

**Issue by i-schuetz** [bluelinelabs/Conductor#312]
I just started using this lib- sorry if I miss something obvious, was wondering how to implement an interface with multiple controllers, which exist merely as (lifecycle aware) organizational units, not navigation/backstack related?

So far I see it's only possible to add controllers using a router, and except for the root controller everything is pushed on the backstack?

I also see that there are child routers - maybe something like adding a child router with a root controller for each of these units "does the trick" but that seems like a very weird approach.

**Comment by AllanHasegawa** [comment]
> So far I see it's only possible to add controllers using a router, and except for the root controller everything is pushed on the backstack?

Well, you have complete control of the backstack. But most of the time you will either push a controller to it or pop from the top.

> I also see that there are child routers - maybe something like adding a child router with a root controller for each of these units "does the trick" but that seems like a very weird approach.

That is how the demo handles "child controller"s:
https://github.com/bluelinelabs/Conductor/blob/09ce640d9c01363cae0a86b67acf532ebd7de5c1/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/ParentController.java#L42

The demo complicates this operation with the `childController.addLifecycleListener`, but if you ignore that part everything is straighforward.

You first find a container (a view, usually a `FrameLayout` with an `id`) for your controller, then get a child router associated with that FrameLayout's id, and then set a child controller in there.

If you don't care about handling the "back button" navigation for your children, then that's it.

**Comment by EricKuck** [comment]
It sounds like you're trying to use Controllers as general logic containers. They're not meant for that though - they're meant to be the View layer of your app. If I'm misunderstanding your intentions, can you maybe explain a little more what you mean about using them as organizational units?

**Comment by i-schuetz** [comment]
@AllanHasegawa ah ok the back button handling has to be added manually - I was just remembering the fragment API, where adding the fragment to the backstack means that the fragment will consume the back button press...

@EricKuck just a very tiny amount of view-related logic, like attaching listeners to the views (the handling of the events is done somewhere else), or on updates, forwarding the model to the contained views...

**Comment by i-schuetz** [comment]
@EricKuck perhaps I should not use these controllers but a custom presenter - following MVP?

**Comment by hannesstruss** [comment]
@i-schuetz like others said, I don't have a full picture of what you're trying to achieve, but could you just use custom ViewGroups and save yourself the overhead of adding a library?

**Comment by i-schuetz** [comment]
@hannesstruss thanks for answering! As I said in the previous message, I'll use presenters (lightweight own classes) instead of controllers, removing thus the dependency of a library. ViewGroups are not suitable because they are views and the idea is to keep this logic outside of the views.
