### ISSUE TITLE
Bundle does not get restored correctly

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#313]
When one stores values to the args, they get restored on orientation change. However they only get restored on process restart when the controller has a bundle constructor. Else the bundle is initialized empty.

As a sample project you can take this:

```java
public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    ViewGroup container = (ViewGroup) findViewById(android.R.id.content);
    Router router = Conductor.attachRouter(this, container, savedInstanceState);
    if (!router.hasRootController()) {
      RouterTransaction transaction = RouterTransaction.with(new C(new Bundle()));
      router.setRoot(transaction);
    }
  }

  public static class C extends Controller {

    public C (Bundle args){
      super(args);
    }

    @NonNull @Override protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
      Log.d("C", String.valueOf(getArgs().getInt("key", -1)));
      getArgs().putInt("key", 42);
      return new View(getActivity());
    }
  }
}
```

First log is of cause -1. Upon orientation change it is 42. Upon process restart it is 42 too.

If you now remove the bundle constructor, the value is -1 upon process restart.

I found this because I have written a conductor way of [FragmentArgumentDelegate](https://gist.github.com/yanngx/efdfbf777d21d6f0e73fab4efe47e924).

**Comment by EricKuck** [comment]
This should now be fixed. Feel free to share your ControllerArgumentDelegate if you want!

**Comment by PaulWoitaschek** [comment]
Thanks, works great!

I just created a gist here:
https://gist.github.com/PaulWoitaschek/ea893f26dd1fe1b30c0fcc286685ea00

I decoupled it from a specific serialization mechanism so you can put any object you can represent in a bundle.
