### ISSUE TITLE
Controller's shouldShowRequestPermissionRationale always returns false 

### ISSUE THREAD

**Issue by siiandlbn** [bluelinelabs/Conductor#317]
I was testing the runtime permissions functionality accross the framework and I noticed, that shouldShowRequestPermissionRationale in Controller class always returns false. Other part of requesting and handling runtime permissions worked great apart from that. Calling that method should reflect the result from calling ActivityCompat.shouldShowRequestPermissionRationale(getRouter().getActivity(), YOUR_PERMISSION).

To reproduce it, just call request permissions anywhere in the Controller, and then for example in "onRequestPermissionsResult(...)" call shouldShowRequestPermissionRationale(..) for the same permission.

The quick workaround is to override that method in your controller and call
"ActivityCompat.shouldShowRequestPermissionRationale(getRouter().getActivity(), YOUR_PERMISSION)" which returns correct values

**Comment by EricKuck** [comment]
Thanks! This is now fixed in the latest snapshot build.
