### ISSUE TITLE
Calling Activity.recreate() results in an empty view

### ISSUE THREAD

**Issue by gabrielittner** [bluelinelabs/Conductor#32]
I've modified the demo's `NavigationDemoController` to call `getRouter().getActivity().recreate()` when the up button is pressed. The Activity will be destroyed and created again, but the view is blank. Pressing back once will correctly show the view of the previous Controller in the backstack.

**Comment by sdrygalski** [comment]
Probably for the same reason InstaRun from Android Studio 2.0 doesn't work - after Cmd-R I end up with empty activity.

**Comment by EricKuck** [comment]
Thanks for the report. This is now fixed in 116b5066c9d16147480f493f3b1b564e17472efa.
