### ISSUE TITLE
Move toolbar to view level

### ISSUE THREAD

**Issue by bangarharshit** [bluelinelabs/Conductor#320]
Currently toolbar is handled in Activity and used in setSupportActionBar(toolBar). Why not just move the toolbar to views? Everyone is responsible for inflating their own menu item and navigation icon. It may add some code in individual views but it is far more flexible than the current solution. Currently, it is also possible to do that and I think the changes I am proposing may break the actionBars but will make library much more simple.

**Comment by EricKuck** [comment]
You're welcome to design your apps this way. Nothing in the library prevents it. The demo app has the Activity hosting the toolbar because that allows it to stay static while views animate in and out. If each controller had its own toolbar, they would be animating with the views.

**Comment by bangarharshit** [comment]
Got it.
