### ISSUE TITLE
How to push controller to new window from router pager adapter?

### ISSUE THREAD

**Issue by putraxor** [bluelinelabs/Conductor#323]
One root controller has a `viewPager`, inside `viewPager` there is some widgets those have clickListeners. Whenever each of them been clicked will redirect into new `controller` outside the `viewPager`. Can it be done with single activity?
Thanks in advance

**Comment by EricKuck** [comment]
Instead of calling `getRouter()`, you'd call `getParentController().getRouter()` to get the host controller's router.
