### ISSUE TITLE
Issues resolving arch-components-lifecycle module

### ISSUE THREAD

**Issue by bachhuberdesign** [bluelinelabs/Conductor#324]
I'm having issues when trying to add the experimental Architecture Components module to my build. Every other Conductor module resolves fine, but when I add

`    compile "com.bluelinelabs:conductor-arch-components-lifecycle:0.1.1"`

it fails to resolve. Any ideas? Should I be using a different version? 

Thanks for your effort on Conductor -- I've been using it for a while and am very excited to finally have the chance to use it in a greenfield project at work.

**Comment by EricKuck** [comment]
Sorry about that! The module name is actually `conductor-archlifecycle`. I'll fix that in the readme now.

**Comment by bachhuberdesign** [comment]
Thanks for the quick reply. It works fine now with the proper import.
