### ISSUE TITLE
[Help Please] Which conductor navigation pattern  should be used

### ISSUE THREAD

**Issue by nksaroj** [bluelinelabs/Conductor#326]
I have the following use case:
- Login Page where there won't be any navigation drawer won't be shown 
- Upon successfully  login the use will be landed on Home Page and also in the same time use can 
   choose to navigate to other pages
-  At anytime the user can end-up with a graph with the traversal of screen. Let use assume A,B,C  and X are the menu on the navigation drawer which would be shown after the Login success.
Login  -->     A --> A1(Home Screen) --> A2-->A3-->C3
                     B --> B1-->B2-->A3 --> C2
                     C --> C1--> C2-->C3
                     X->SignOut--> Login
   
On clicking on the home menu at any point of the journey can be navigated to A1 as it's the home screen.
-  User will be redirected to Login screen on session time out.

After looking the samples of conductor I am not sure which pattern I need to choose. Master Detail or Multiple Controller or Combination of both.  getRouter().popToRoot() normally wind all the user journey and return back to the Root Controller. I am confused Which one should be my Root Controller Login/Home ? 
I am thinking of using master detail where A,B,C are the main controllers for the master details journey If So Is there any option to Pop to specific master rather navigating to the Login screen  with the usage of getRouter().popToRoot().

I understand it's very simple use case But I would like to make the right decision to use the most useful approach. It would be great If anyone can share some lights from your experiences.

**Comment by EricKuck** [comment]
I'm not sure what your UI looks like, so I can't really say if master/detail is the right choice for your app. I will say though that, assuming the login page is something that only gets shown the first time they use the app or if their session times out, I wouldn't make it the root controller.

For this type of situation I usually do something like this from my Activity's `onCreate`:

```
    if (!isLoggedIn()) {
        router.setRoot(RouterTransaction.with(LoginController()))
    } else {
        router.setRoot(RouterTransaction.with(HomeController()))
    }
```

Then somewhere else I'd listen for session timeout events and do

```
    router.setRoot(RouterTransaction.with(LoginController())
            .pushChangeHandler(FadeChangeHandler())
            .popChangeHandler(FadeChangeHandler())))

    // Show a toast, dialog, whatever explaining why they got logged out
```

**Comment by nksaroj** [comment]
@EricKuck . Thank you...
