### ISSUE TITLE
Set default page in pagerAdapter

### ISSUE THREAD

**Issue by jamesvanhallen** [bluelinelabs/Conductor#329]
How to set default page in ViewPager?
something like `setCurrentPage(2)` in standart ViewPager

**Comment by nksaroj** [comment]
Yes you are right

**Comment by jamesvanhallen** [comment]
```mPagerAdapter = new RegionsLeaguesPagerAdapter(...);
mViewPager.setCurrentItem(1);```
it doesn't work

**Comment by EricKuck** [comment]
This library doesn't come with a ViewPager. The ViewPager you're using IS the standard ViewPager, so the method you mentioned in the question works.
