### ISSUE TITLE
[Question] How do I get the currently displayed Controller from a RouterPagerAdapter?

### ISSUE THREAD

**Issue by djweber** [bluelinelabs/Conductor#334]
First, I'd like to say that I love what you've done with this framework -- it's a breeze to work with!

I was curious: is there is an official way to get the currently displayed Controller from a RouterPagerAdapter? I noticed there used to be a way to get it via the proposed solution in #195, but that seems to be deprecated now. My use-case is that I'd like to trigger an action on the currently displayed page given an interaction on the host controller. I tried doing something like the following:

```
Router router = routerPagerAdapter.getRouter(ticketViewPager.getCurrentItem());
if (router == null) {
    throw new IllegalStateException("Router does not exist");
}
List<RouterTransaction> backStack = router.getBackstack();
if (backStack.size() == 0) {
    throw new IllegalStateException("Attempting to retrieve controller from empty backstack");
}
return (ActiveTicketPageController) backStack
    .get(backStack.size() - 1)
    .controller();
```

However, when attempting to interact with this controller after the view pager change, I'd sometimes get a `null` value back for the router -- probably has something to do with the underlying internals of the ViewPager API, or my own misunderstanding of the RouterPagerAdapter API. Is there a better way to get the current controller?

**Comment by EricKuck** [comment]
What you're doing appears to be correct. `getRouter` will return the router for the requested page as long as it's been instantiated. I have no idea why you'd be getting `null` in that case, unless perhaps the host controller isn't attached or the `ViewPager` hasn't laid out yet.
