### ISSUE TITLE
Allow defined ChangeHandler when popping last Controller

### ISSUE THREAD

**Issue by bgogetap** [bluelinelabs/Conductor#339]
In `Router#performControllerChange` _line_ _#755_, the change handler is set to `NoOpControllerChangeHandler` if we're popping the root Controller.

My use case is this: I have one router for main navigation, and one for modals. The main container is padded for the Toolbar/AppBar, so pushed Controllers would not cover them. I have a separate modal container that fits the entire screen.

The modal container will always only have one Controller pushed to it, and when popped, I would expect it to animate away as defined.

This is pretty easy to work around, but would you be interested in PRs that allow this behavior without affecting current expected behavior? Or is my use case easily handled with another pattern that I'm overlooking?

Thanks!

**Comment by EricKuck** [comment]
If you just call Router.setPopsLastView(true), you'll get exactly what you're looking for. This is false by default, as the standard use case for routers is to not perform a pop animation and to simply let the host handle the event instead.

**Comment by bgogetap** [comment]
Wow, no excuse for missing that on my part.

Thanks for the quick response!

**Comment by EricKuck** [comment]
Haha no worries! The docs on that are a little hard to discover.
