### ISSUE TITLE
windowSoftInputMode issue on conductor

### ISSUE THREAD

**Issue by shakil807g** [bluelinelabs/Conductor#341]
when a view got focused it move up and keyboard shows but second time when view got focused it don,t it move up and keyboard above it

**Comment by EricKuck** [comment]
Does this somehow relate to conductor? Sounds like you just have an issue with your app logic.

**Comment by shakil807g** [comment]
sorry you are right it was my error please close this issue

**Comment by EricKuck** [comment]
No worries. Thanks for the update.
