### ISSUE TITLE
Back to parent controller

### ISSUE THREAD

**Issue by eGorets** [bluelinelabs/Conductor#342]
Is there the easier way to back from child controller to previous parent controller?
I have simple navigation rules like

```
A --> B
        B1 --> B2 --> B3
A <---------------------
```

How can I achieve that?

Thanks for advice

**Comment by JuzTosS** [comment]
So, you can just call `handleBack()` on the parent controller or router.

**Comment by hannesstruss** [comment]
Although it would probably be a bit cleaner for `B3` to ping `B` that it is done, so `B` can pop itself.

**Comment by eGorets** [comment]
I tried to do that with no luck

my parent controller looks like

```
....
 override fun onAttach(view: View) {
        super.onAttach(view)

        childRouter = getChildRouter(view.findViewById(R.id.controllerContainer))

        if (childRouter.hasRootController().not()) {
            childRouter.setRoot(RouterTransaction.with(PhoneController()))
        }
    }
....


    override fun exit() {
        router.handleBack()
    }

```

when I call `exit()` it leads me to previous child contoller

**Comment by hannesstruss** [comment]
I think `router.popController(parentController)` should do what you need!

**Comment by eGorets** [comment]
yep. thanks. It works, just tried
