### ISSUE TITLE
handleBack() removed view from container

### ISSUE THREAD

**Issue by McGars** [bluelinelabs/Conductor#343]
Case
- PageViewAdapter with Controller's
- router.replaceTopController(transition)
- from activity router.handleBack()
- Controller call onDestroyView, but Controller is last in back stack

I set double pressed on back button for exit and in this case i get withe screen

on 2.1.3 this not happened

**Comment by EricKuck** [comment]
I don't understand what this issue is for. What's the problem?

**Comment by McGars** [comment]
When i press back button i trigger timer in 3 second and show the message so that the user presses the button again to exit. In onDestroyView i kill links  (adapter == null) and get empty page if Controller was last in back stack. How don't destroy last Controller when user press back button? 

![screenshot_1502790708](https://user-images.githubusercontent.com/7271425/29310976-9a586b88-81b8-11e7-80e5-48949a361f33.png)
![screenshot_1502790711](https://user-images.githubusercontent.com/7271425/29310977-9a90fcdc-81b8-11e7-862f-be70b684b01a.png)

**Comment by McGars** [comment]
I solved my issue
``` kotlin
if (backStack.last().controller().handleBack()) {
        return true
}

 if (router.backstackSize > 1) {
        router.popCurrentController()
        return true
 }
```
