### ISSUE TITLE
Controller Lifecycle & ViewPager position after screen rotation

### ISSUE THREAD

**Issue by uburoiubu** [bluelinelabs/Conductor#351]
I have a problem with ViewPager not saving its position after screen rotation. I tried debugging and what I got in the logcat doesn't correspond to the controller lifecycle, as described [here](https://github.com/bluelinelabs/Conductor/issues/10#issuecomment-252174643).

I got these:

```
onSaveViewState:  called
onSaveInstanceState:  called
onCreateView:  called
onRestoreViewState:  called
onCreateView:  called
```

I save ViewPager position inside `OnSaveViewState` and trying to restore it inside `onRestoreViewState`. Then `onCreate` is called second time, and so the changes that i've made inside `onRestoreViewState` have no effect. I don't understand where this last `onCreateView` is coming from.

Update: I also noticed that `onDestroyView` gets called **after**(!) `onRestoreViewState` after screen rotation. Here's the sequence (from the moment where the screen is rotated): `onSaveViewState → onSaveInstanceState → onDestroyView → onCreateView → onRestoreViewState → onDestroyView → OnCreateView`.

**Comment by EricKuck** [comment]
What is `onCreate` here? There is no `onCreate` method on Controllers.

**Comment by uburoiubu** [comment]
@EricKuck, sorry, it was a typo. I meant `OnСreateView`.

**Comment by sockeqwe** [comment]
When do you set the ViewPager adapter? In `onCreateView`? Does the ViewPager has a unique id?

**Comment by uburoiubu** [comment]
@sockeqwe , the` ViewPager` does have a unique id and I set it Inside` onCreateView` as follows:
```
 @NonNull
    @Override
    protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
        View view = inflater.inflate(R.layout.controller_card, null);
        unbinder = ButterKnife.bind(this, view);

        ArrayList<String> titles = new ArrayList<>();
        titles.add(getActivity().getString(R.string.pager_info));
        titles.add(getActivity().getString(R.string.pager_history));
        titles.add(getActivity().getString(R.string.pager_task));
        titles.add(getActivity().getString(R.string.pager_reports));

        [...]

        CardTabAdapter tabAdapter = new CardTabAdapter(inflater, getActivity(), titles, vehicle, slidingPanel, this);
        viewPager.setAdapter(tabAdapter);
        tabLayout.setupWithViewPager(viewPager);
        tabLayout.setBackgroundColor(getResources().getColor(R.color.colorPrimary));
        tabLayout.setTabTextColors(Color.BLACK, Color.BLACK);

        return view;
    }
```

**Comment by uburoiubu** [comment]
@sockeqwe, @EricKuck, I moved it here: 

https://stackoverflow.com/questions/47232228/conductors-controller-unexpected-lifecycle
