### ISSUE TITLE
Leaking InputMethodManager

### ISSUE THREAD

**Issue by mradzinski** [bluelinelabs/Conductor#354]
Hi, I'm having multiple leaks using Conductor which I simply can't make sense of. Here's a screenshot taken from LeakCanary:

<img width="383" alt="screen shot 2017-09-09 at 4 46 02 pm" src="https://user-images.githubusercontent.com/4214209/30243435-aa9f7650-957f-11e7-9c34-8810005364bd.png">

Any idea why Conductor might be leaking the InputMethodManager? 😕 

I think also @PaulWoitaschek was observing the very same kind of leaks (he mentioned something on another issue, but can't seem to find it right now).

**Comment by sevar83** [comment]
There are long standing platform leaks related to `InputMethodManager`. https://github.com/square/leakcanary/issues/750
What's your API level?

**Comment by EricKuck** [comment]
Can you provide some detail? What happened to get you this leak? Any sample code? We've made a ton of apps with Conductor and none have this issue, so it's very unlikely to be a library issue. Particularly since InputMethodManager is never referenced.

**Comment by mradzinski** [comment]
@sevar83 API Level 19 and above, all show up the same IMM leak.

@EricKuck, I don't reference the InputMethodManager either. It's a plain and simple app, three empty controllers navigated through a BottomNavigationView. I'll try drop a simple demo on a repo later today so you can check it out.

**Comment by ousenko** [comment]
Actually it is not a surprise that IMM leaks stuff.

What really puzzles me is: how can DecorView#mContentView hold a Context **that references a Router** ? 

<img width="385" alt="13123" src="https://user-images.githubusercontent.com/5771855/34033213-bda39600-e192-11e7-8f18-602be3ad8805.png">

Haven't digged deep into Conductor/Router sources yet, maybe @EricKuck could provide any hints? 

Problem is really annoying :-/

**Comment by hannesstruss** [comment]
@ousenko the context of your LinearLayout is an Activity, which usually holds the Router.

**Comment by ousenko** [comment]
@hannesstruss In client code I ensure no references left to router after onDestroy - by explicitly null-ing it. I see no other facility in my code that could leak the router after onDestroy.

I understand that IMM-related leaks are usually to be ignored, cause they happen due to platform implementation flaw. 

Still, I would be happier if only Activity/Context references leaked, - and not Conductor related stuff..

**Comment by hannesstruss** [comment]
@ousenko then I would investigate whether your LeakCanary runs at the correct time.

**Comment by ousenko** [comment]
> then I would investigate whether your LeakCanary runs at the correct time.

@hannesstruss What exactly do you mean by that? Could you explain your idea in a bit more details?

**Comment by hannesstruss** [comment]
I'm not sure how you have implemented LeakCanary into your app, but if you null the reference to the router in onDestroy, that probably means LeakCanary runs before onDestroy (or onDestroy isn't called).

If you're building your own `RefWatcher`, you can [increase the delay after which it runs](https://github.com/square/leakcanary/blob/master/leakcanary-android/src/main/java/com/squareup/leakcanary/AndroidRefWatcherBuilder.java#L35), though the default is usually fine and the error lies somewhere else.

**Comment by ousenko** [comment]
@hannesstruss You're right - I use custom ref watcher and watch references not only in Activity#onDestroy, but in Controller#onDestroyView and Controller#onDestroy. 

I'll check it out and get back here, thank you!
