### ISSUE TITLE
Slow performance on API 26 (Android 8.0)

### ISSUE THREAD

**Issue by LPirro** [bluelinelabs/Conductor#355]
I'm having slow performance using Conductor on API 26 (Google Pixel, Android 8.0).

When i use router.pushController(...) or router.setRoot(...), the controller is not showed immediately, there is a delay of ~1 second. 

With API 25 (or below) it's ok: The controller is pushed immediately after the router.pushController(...) or router.setRoot(...).

**Comment by nksaroj** [comment]
Yes I've noticed the same. Also I have the noticed the transition animations are not smooth anymore.

**Comment by EricKuck** [comment]
Is there any tangible demo of this? I've seen no difference in any of my apps. The demo app is exactly as fast as it's always been. My phone has been noticeably slower overall since I got Oreo, but performance issues are equally noticeable on all apps for me (Conductor powered or not).

**Comment by tomblenz** [comment]
I don't think this is Conductor-specific.  I noticed the slowdown too and assumed it was Conductor, but soon realised that my Pixel is just generally a bit laggy under Oreo.  Others have been reporting a speed increase so I dunno.
