### ISSUE TITLE
Preferred mechanism for communication between sibling controllers?

### ISSUE THREAD

**Issue by rodly** [bluelinelabs/Conductor#356]
With fragments we can set a target along with a request code, and the sibling can then communicate backwards via onActivityResult with the target request code and any respective data.

The `Controller` API provides an accessor/mutator for a target controller but lacks the request code (i'm assuming this was intentional).

I see in `setTargetController` the following comment.

`It is recommended that Controllers enforce that their target Controller conform to a specific Interface.`

Is the idea here to provide various communicating interfaces that the target can implement?

Something like:

```kotlin
interface FooTarget {
  fun setResult(result: Result)
}
```

and in callee controller

```kotlin
(targetController as? FooTarget)?.setResult(...)
```

I hope I'm horribly mistaken.

**Comment by EricKuck** [comment]
This is exactly how it's supposed to work. Why would you want to be mistaken about this? IMHO it's a much better design than using arbitrary integers and a mysterious bundle object to get results.

**Comment by rodly** [comment]
Uh, because that's one of the most common patterns in Android.

Arbitrary integers? They're completely encapsulated by the caller and meaningful within the caller too.

Mysterious bundle object? Once again, this is Android, it's not mysterious and you can quite easily transfer data in Bundles very sanely.

Anyways, thanks for the response.

**Comment by EricKuck** [comment]
"We've always done it this way" doesn't necessarily mean it's a good pattern. If you do really like that pattern though, you can absolutely replicate it with a simple BaseController class that adds `setRequestCode` and `onContollerResult` methods. There's nothing stopping you from using any pattern you'd like to use.

**Comment by rodly** [comment]
I totally agree with you in general. Sorry for the snippy comment at first, thanks for the information.
