### ISSUE TITLE
Pop controllers above a certain point in the stack

### ISSUE THREAD

**Issue by pwalk112** [bluelinelabs/Conductor#359]
```
A - - -                 - - - C1 - - - C2 - - - etc.
         \            /
	     - - - C - - - D
	 /
B - - -

```

There are multiple arrival points (A, B) to my base controller (C) in this flow. C has a child router with the flow of C1, C2, etc. When C attaches, it immediately pushes a dialog controller (D) with `removesFromViewOnPush = false`.

I need the ability to pop C from the flow at any point and return to the previous controller (whatever it might be). This can be triggered even with D pushed on top of C. 

Essentially, I want to pop C and have any views on top of it be popped as well but I haven’t been able to figure out how to do that. These controllers (excepting the controllers in C's child router) are all on the same router with a Home controller as root.

Any thoughts? Thanks!

**Comment by hannesstruss** [comment]
It's not super nice to couple the child controllers to their parent, but this could probably be achieved by walking up the backstack like this: https://github.com/hannesstruss/ConductorResources/blob/master/library/src/main/java/de/hannesstruss/conductor/resources/ResourceManager.java#L32-L55

**Comment by pwalk112** [comment]
That is a very helpful resource, thank you.
