### ISSUE TITLE
LifecycleListener: postCreateView() called after onRestoreViewState()

### ISSUE THREAD

**Issue by sockeqwe** [bluelinelabs/Conductor#36]
Hi, 
I have noticed that  `LifecycleListener.postCreateView()` is called after `LifecycleListener.onRestoreViewState()` .

Is that per purpose? To me it sounds like a little bit a contradiction of Conductors lifecycle diagram where `onCreateView()` becomes before `onRestoreViewState()` so that I was expecting that `LifecycleListener.postCreateView()` will be called right after `onCreateView()` and before `onRestoreViewState()`.

I'm facing the problem where I do some `View foo = findViewById(R.id.foo)` in `LifecycleListener.postCreateView()`  but also wanted to recover the state of `View foo` manually in `LifecycleListener.onRestoreViewState()` which leads to a NullPointerException because `LifecycleListener.postCreateView()` is called after `LifecycleListener.onRestoreViewState()`  ...

Obviously I can rewrite my code to avoid that problem, I just wanted to ask if this execution order is by design?

**Comment by EricKuck** [comment]
You're right, this is not intentional. I'll have a fix up in a snapshot within a few hours.

**Comment by EricKuck** [comment]
This is fixed now in f8a05731d9d6b678b62f213b56af953f7cc879b9. I'll do a proper 1.1.5 release this weekend. Thanks for the heads up!
