### ISSUE TITLE
[Enhancement] Support Android Databinding #Hacktoberfest

### ISSUE THREAD

**Issue by The0ldM0nk** [bluelinelabs/Conductor#362]
Hey guys, 
In the past I had worked on a sample which integrates Android Databinding into Conductor API and I'd like to prepare a pull-request for that.

Kindly apply #Hacktoberfest label to this ticket [Github's](https://github.com/blog/2433-celebrate-open-source-this-october-with-hacktoberfest) #[Hacktoberfest](https://hacktoberfest.digitalocean.com/#resources) 2017 which would promote the cause as well.

Cheers,
Monk

**Comment by EricKuck** [comment]
I'm so sorry for the late response! I just applied the label, so you still have 2 days :)

That being said, I'm not too keen on adding a Databinding dependency into the core project. I assume your PR would be some kind of external module?
