### ISSUE TITLE
RxLifecycle 1.1.5 snapshot is currently broken

### ISSUE THREAD

**Issue by adi1133** [bluelinelabs/Conductor#37]
https://oss.sonatype.org/content/repositories/snapshots/com/bluelinelabs/conductor-rxlifecycle/1.1.5-SNAPSHOT/conductor-rxlifecycle-1.1.5-20160419.202538-1.pom

There is a dependency on Conductor:conductor:unspecified, this dependency is broken.

```
<dependency>
<groupId>Conductor</groupId>
<artifactId>conductor</artifactId>
<version>unspecified</version>
<scope>compile</scope>
</dependency>
```

The workaround I am using is including the dependency using:
```
compile 'com.bluelinelabs:conductor:1.1.5-SNAPSHOT'
compile('com.bluelinelabs:conductor-rxlifecycle:1.1.5-SNAPSHOT') {
    exclude group: 'Conductor', module: 'conductor'
}
```

**Comment by EricKuck** [comment]
This is the first time I've used sonatype to host my artifacts, so I'm not too sure what's going on here or how to fix it. Maybe @sockeqwe has an idea? I compared my build.gradle files with the ones in the Mosby repo and can't tell what the difference is.

**Comment by cs-victor-nascimento** [comment]
Conductor support is also broken in SNAPSHOT. It has a typo on the artifact suPPPort.

![screenshot from 2016-04-27 22-00-11](https://cloud.githubusercontent.com/assets/7049728/14872521/82f04c24-0cc3-11e6-89df-a719dadad93b.png)

Once you declare it with the typo it falls short on this same issue. If you want I can open a separate issue but I guess both will be resolved together.

**Comment by EricKuck** [comment]
Wow, can't believe I didn't notice that typo. It should be fixed now. I'm still not sure what needs to be done for the dependency version to be anything other than unspecified though.

**Comment by burntcookie90** [comment]
Michael Evans had this issue on Aftermath, he fixed it in [this](https://github.com/MichaelEvans/Aftermath/pull/18) PR. Might be useful to check out.
