### ISSUE TITLE
ObsoleteLintCustomCheck

### ISSUE THREAD

**Issue by timrijckaert** [bluelinelabs/Conductor#370]
I got this while running lint.

` Lint found one or more custom checks using its older Java API; these checks are still run in compatibility mode, but this causes duplicated parsing, and in the next version lint will no longer include this legacy mode. Make sure the following lint detectors are upgraded to the new API: com.bluelinelabs.conductor.lint.ControllerChangeHandlerIssueDetector, com.bluelinelabs.conductor.lint.ControllerIssueDetector`

**Comment by PaulWoitaschek** [comment]
Fixed by 5ce857bb24b00661190d3e6f545a596270332031

**Comment by nikslushkin** [comment]
Hi! Are you sure it is fixed in 2.1.5? 
I see next issue:
`
conductor-2.1.5.aar/.../lint.jar: Lint found an issue registry (com.bluelinelabs.conductor.lint.IssueRegistry) which did not specify the Lint API version it was compiled with.
`

**Comment by PaulWoitaschek** [comment]
Looks like a different issue for me, open a bug :)

**Comment by PaulWoitaschek** [comment]
Should be fixed by https://github.com/bluelinelabs/Conductor/pull/460

**Comment by EricKuck** [comment]
Thanks @PaulWoitaschek! Does the lack of API version cause it to run in legacy mode as well? If so, we should probably cut a quick 2.1.6 so people's builds can speed up.

**Comment by PaulWoitaschek** [comment]
I'm not sure. All I could find on this was:
https://groups.google.com/forum/#!topic/lint-dev/eCxw9PdTpVI
