### ISSUE TITLE
Leaks in Conductor demo

### ISSUE THREAD

**Issue by dzeroone** [bluelinelabs/Conductor#373]
After installing the `demo` app,  behind the scene there is another app installed automatically named `Leaks`.
What is it? How it get installed?

**Comment by serjooo** [comment]
It is called leakCanary helps find memory leaks in your application. You could read more about the library here:

https://github.com/square/leakcanary

**Comment by EricKuck** [comment]
You're seeing https://github.com/square/leakcanary. It's a part of the demo app to track if any leaks occur.

**Comment by PaulWoitaschek** [comment]
It's not another app it's just an activity shipped by the debug builds from LeakCanary

**Comment by EricKuck** [comment]
Good job teaming up to cover this answer at the same time everyone! High fives all around.

**Comment by PaulWoitaschek** [comment]
If all questions were that simple to answer...
