### ISSUE TITLE
AutoDispose: Any plans to update to 0.4.0?

### ISSUE THREAD

**Issue by StephanSchuster** [bluelinelabs/Conductor#374]
Just a question: Are there any plans to update the autodispose module to uber/AutoDispose 0.4.0? Currently Conductor is using 0.2.0 and it seems that uber's lib has change quite a bit since then.

**Comment by PaulWoitaschek** [comment]
I guess a PR would be welcome for that :)

**Comment by bensandee** [comment]
See PR #382
