### ISSUE TITLE
RouterPagerAdapter return incorrect position values.

### ISSUE THREAD

**Issue by uburoiubu** [bluelinelabs/Conductor#375]
I have a controller inside which a view pager for other controllers. When I check an item position inside `configureRouter` of `RouterPagerAdapter`, I got false values:

```
@Override
            public void configureRouter(@NonNull Router router, int position) {

                if (!router.hasRootController()) {
                    Controller page = new ExerciseGrammarPageController(useCases.get(position));
                    router.setRoot(RouterTransaction.with(page));
                }

                Log.e("position", String.valueOf(position));

                loadImage(useCases.get(position).getPicture());
            }
```

Especially when I swipe to the left. Often it can be a sequence like the following one:

**0 - 1 - 2 - 3 - 4 - 3 - 1.**
_(is it related to saving state process?)_

I need it to be exact to load images on the parent controller.

What might be the issue here? Or should I get the correct item position from some other method?

**Update:** Using `ViewPager`'s default `OnPageChangeListener`I was able to get the correct item position. I leave the issue open, in case you consider `configureRouter`'s described behaviour as a bug.

**Comment by gstepniewski** [comment]
I don't think this is a bug in Conductor.

The `configureRouter` method is called whenever the ViewPager needs the adapter to instantiate an item - not necessarily when that page becomes active. In some cases, the ViewPager will preload multiple pages in advance, causing `configureItem` to be called for all of them at once.

So basically, using this method is not the correct way of tracking which page is being displayed - `OnPageChangeListener` is.
