### ISSUE TITLE
Avoid Controller detach on inflate.

### ISSUE THREAD

**Issue by ghost** [bluelinelabs/Conductor#376]
Hi, whenever I inflate my Navigation Drawer my Controller get detached, how to avoid that?

**Comment by EricKuck** [comment]
This has never happened for me. Sounds like you have a bug of some kind. If you want to post your project I can take a quick look.

**Comment by ghost** [comment]
> I'm using Material Drawer by Mike Penz, building a drawer it will:
> mActivity.getLayoutInflater().inflate(R.layout.material_drawer, mRootView, false);
> and I think this is detaching my Controller. I've tried to extend the builder for pass the ViewGroup of the actual controlleras rootView , but with no success

Edit: sorry, I check better, it's not the inflating, I was pretty sure about that, there is something other in that builder that detachs it

**Comment by EricKuck** [comment]
I've never used that library, but I'd guess it's re-parenting your entire view. If that's the case, just add your controller after you have the nav drawer setup. It sounds like conductor's doing exactly what it should.

**Comment by ghost** [comment]
Yes I was guessing the same, I wrote to him and he just said "The building of the drawer will inflate the DrawerLayout to the view hierarchy.".
The problem is that I'm using a single Activity and the drawer is in my "root" controller, so it's like:
Activity -> root controller -> drawer -> child controller.

**Comment by ghost** [comment]
```
`View originalContentView = mRootView.getChildAt(0);

            //remove the contentView
            mRootView.removeView(originalContentView);

            //create the layoutParams to use for the contentView
            FrameLayout.LayoutParams layoutParamsContentView = new FrameLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.MATCH_PARENT
            );
            mContainer.addView(originalContentView, layoutParamsContentView);

            //make sure we have the correct layoutParams
            if (mContainerLayoutParams == null) {
                mContainerLayoutParams = new ViewGroup.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.MATCH_PARENT
                );
            }
            //add the drawerLayout to the root
            mRootView.addView(mContainer, mContainerLayoutParams);`
```

any way to workaround it?

**Comment by ghost** [comment]
@EricKuck Looks like moving the building process into the onCreateView solved the problem.
