### ISSUE TITLE
How to work with notification builder with conductor

### ISSUE THREAD

**Issue by Osmandiyaka** [bluelinelabs/Conductor#378]
At the moment this is how i am creating notification` Intent intent = new Intent(this, SignUpActivity.class);
    intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
    PendingIntent pendingIntent = PendingIntent.getActivity(this, 1410, intent, PendingIntent.FLAG_ONE_SHOT);

    NotificationCompat.Builder notificationBuilder = new
        NotificationCompat.Builder(this)
        .setSmallIcon(R.drawable.ic_account_box_black_24dp)
        .setContentTitle("SpaceWek")
        .setContentText(remoteMessage.getNotification().getBody())
        .setAutoCancel(false)
        .setContentIntent(pendingIntent);

    NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
    notificationManager.notify(1410, notificationBuilder.build());`

what i want is to navigate to a controller when the notification is tap. please can anyone help me

**Comment by EricKuck** [comment]
You'd just set an action on the intent that you then handle in your activity by synthesizing the backstack for whatever you're deep linking into.

**Comment by Osmandiyaka** [comment]
@EricKuck thanks so much for your quick response.But am new to android and finding difficult to understand what you just explain.Please i would be glad if u can explian further maybe with some code sample thank you.
