### ISSUE TITLE
How to determine the current active controller from inside a service

### ISSUE THREAD

**Issue by Osmandiyaka** [bluelinelabs/Conductor#379]
I am recieving push notification from Firebase cloud messaging(FCM) and i want to treat the notification differently depending on which controller is active. but i cannot figure out the best way to achieve thtat. any help

**Comment by sockeqwe** [comment]
Dont do that. Whatever you want to do, getting info about UI (like
ViewController) is the entirely wrong way to go.
Btw. You can't do that either with fragments or activties.

Osmandiyaka <notifications@github.com> schrieb am Do., 2. Nov. 2017, 12:42:

**Comment by Osmandiyaka** [comment]
This is how i am currently doing it. i attach a routerChangerListener to my router and track the current controller. i can then return it in a static method
