### ISSUE TITLE
[Question] What happens with retained controller views when another Controller is pushed?

### ISSUE THREAD

**Issue by Gaket** [bluelinelabs/Conductor#380]
Hello,

I have a question: What happens with controllers views when another Controller is pushed with `RETAIN_DETACH`? I know what lifecycle methods will be called in the first Controller. I looked at the code and I saw, that Controller will still have a strong link on its views. 

The question is what happens with these views regarding the Android's `WindowManager`? If a new `Activity` was pushed instead of `Controller`, it would have a new `Window` for views. But what happens here? Am I right that Conductor uses the same `Window` and just removes the whole `ViewGroup` of the first `Controller` from a `Router` container, and puts new one there? Am I right that in this case views inside the first `Controller` will get `onDetachFromWindow()` callback from Android?

**Comment by atrang89** [comment]
I've done this and it's a little buggy, If there is a new activity that pushes on top of the current activity, there seems to be a memory leak.  For instance opening a camera or google map which requires an activity.  When you dismiss the new activity and go back to the activity on the bottom, sometimes it will recreate the bottom activity view or maintain it.
