### ISSUE TITLE
React native Controller 

### ISSUE THREAD

**Issue by patrickmuhi** [bluelinelabs/Conductor#381]
Is it possible to create a controller that has React native?

**Comment by EricKuck** [comment]
What are you looking to do exactly? Doesn't react native use its own components and architecture? What advantage would there be to using conductor if you're going react native?

**Comment by patrickmuhi** [comment]
@EricKuck I want to render a RN component inside a Controller.

RN can be rendered inside an Android fragment, so i thought it'd be awesome to plug it into a Controller. due to Controller's reusability i'd switch through different RN Apps compared to traditional one-activity RN.

**Comment by EricKuck** [comment]
If you can add it to a Fragment I'm sure you can add it to a Controller. I never have/probably never will use RN, so I can't really be of help here.

**Comment by mradzinski** [comment]
@1k2k I know this is an old issue, but did you have any luck doing this? Just wondering how possible it is.

**Comment by patrickmuhi** [comment]
@mradzinski it's practically possible, however i stopped using classic java, am now fully into RN. 

Please note that wiring a react native app into a controller will add more complications to your code + performance issues. I mean not only will you have to handle android lifecycles, which are bond to one large activity attached a number of  controllers. Your activity will consume all resources worst case might even freeze.

**Comment by EricKuck** [comment]
Closing due to lack of recent activity.
