### ISSUE TITLE
It seems RETAIN_DETACH doesn't work as expected

### ISSUE THREAD

**Issue by b1uebyte** [bluelinelabs/Conductor#39]
So. I expect retained view to be reattached after activity recreation. But nothings happens.

```Controller``` keeps view — thats ok. But view itself keeps its parent. And ```SimpleSwapChangeHandler``` can't add it on router recreation:
```
if (to != null && to.getParent() == null) {
    container.addView(to);
}
```

**Comment by adi1133** [comment]
Views are not kept after activity recreation (this is an android limitation). After activity recreation you get a call to onCreateView.
That flag affects what happens if you navigate using the Conductor router.

**Comment by EricKuck** [comment]
@adi1133 is exactly right. This flag isn't meant to hold views across different host activities. I briefly had a feature like this, but it's almost impossible to reuse a view with different activities without causing lots of leaks.
