### ISSUE TITLE
How to update view on restore?

### ISSUE THREAD

**Issue by frakc** [bluelinelabs/Conductor#390]
i am using conductor 2.1.4

I have controller page which is chils of Pageroutercontroller.
From page controller, i open edit controller and change data which is relevent to page and save it to preferences.
Then I pop edit controller -             getRouter().popController(ProfileEditController.this);
And here is my problem. 
```java
if (!TextUtils.isEmpty(birth)) {
      holderBirth.setVisibility(View.VISIBLE);
      dividerBirth.setVisibility(View.VISIBLE);
      tvBirth.setText(null);

      Log.e("mcheck", "onViewBound: setbirth " + birth);
      tvBirth.setText(birth);
    } else {
      holderBirth.setVisibility(View.GONE);
      dividerBirth.setVisibility(View.GONE);
    }
```
this block is called insede page onCreateView. Log shows me the new value of field birth. But (TextView) tvBirth displays the value before edit.

**Comment by frakc** [comment]
the only way i manage to ensure view update is by setting value inside post
```java
tvBirth.post(new Runnable() {
        @Override public void run() {
          if (tvBirth != null) tvBirth.setText(birth);
        }
      });
```

**Comment by joaolisboa** [comment]
Not sure if this is still an active issue for you but since it's still open could you show the rest of the code of the controller, or controllers?
