### ISSUE TITLE
Dagger 2

### ISSUE THREAD

**Issue by timrijckaert** [bluelinelabs/Conductor#397]
Hi, 

I'm sorry if this is out of scope or not related.
But I was wondering if anybody has a good starter sample on how to use Dagger 2 with Conductor.
In particular with the _new_ Android support for Dagger 2. 

I am quite far at showcasing this on my [GitHub](https://github.com/timrijckaert/conductor-dagger).
Any help?

Thanks

**Comment by IVIanuu** [comment]
You could use my library contributer to use @ContributesAndroidInjector with controllers.
https://github.com/IVIanuu/Contributer/

**Comment by timrijckaert** [comment]
I made a small [sample](https://github.com/timrijckaert/conductor-dagger) on how to implement this yourself. But you could use IVIanuu's lib too.

**Comment by PaulWoitaschek** [comment]
Closing this as there seems to be a solution :+1:

**Comment by vincent-paing** [comment]
Anyone know solution to use it with [Dagger Hilt](https://dagger.dev/hilt/)?
