### ISSUE TITLE
Pop Controller Issue with RouterPagerAdapter

### ISSUE THREAD

**Issue by pawarn** [bluelinelabs/Conductor#402]
In my Application, I added controller in RouterApger Adapter like this.

routerPagerAdapter = new RouterPagerAdapter(this) {
            @Override
            public void configureRouter(@NonNull Router router, int position) {
                if (!router.hasRootController()) {
                    router.setRoot(RouterTransaction.with(controllerMap.get(position)).tag(position + ""));
                }
            }

            @Override
            public int getCount() {
                return controllerMap.size();
            }
        };

I put all controller On Map and passed this rounterPager to viewPager.

I have added more controller to viewPager first position controller.
But when I am handling on backPressed event I pop current controller. At the time of getRouter().getBackstackSize() returns me size 0 even if there is controller available in router.

Please help me to solve this issue.

**Comment by EricKuck** [comment]
If I'm reading this correctly, the issue is that each page has a different router. Unless you pushed a 2nd controller to a page, what you're seeing is correct. Feel free to reopen if I misunderstood.
