### ISSUE TITLE
Espresso best practices

### ISSUE THREAD

**Issue by cody1024d** [bluelinelabs/Conductor#409]
I'm trying to create some automated UI tests for my (fairly) complex app.  Within the application I have a main router attached to my activity, who's controllers may or may not also have sub-routers and controllers (along with some that are view pagers).

Is there a "good" way to essentially get the visible controller(s) nicely, so that I can access their public variables within Espresso to test?  I can lean more towards black-box testing EVERYTHING, but there are some things that are much easier to test (such as checking if any of the items in a list contain a specific data model) leveraging an exact reference.

**Comment by dimsuz** [comment]
Such questions should be asked on StackOverflow instead. Github issues are for reporting bugs in the library...

**Comment by cody1024d** [comment]
I apologize; I didn't realize there was a large Conductor community on stackoverflow; figured I'd get something straight from the horse's mouth, so to speak posting here.  Closing, and will repost on Stackoverflow instead.

**Comment by cody1024d** [comment]
Although to play devil's advocate a bit, and explain my reasoning:

I do think this is a place missing from examples, and perhaps even documentation.  Testing is an important feature and as Conductor essentially replaces the entire activity/fragment framework, I feel as though there should be some improved documentation on how to properly test it (from a functional/UI perspective).

**Comment by dimsuz** [comment]
I agree. Documentation is currently lacking, something that should be improved...

**Comment by ghost** [comment]
About using Conductor and Espresso tests: https://www.novoda.com/blog/testing-views-in-isolation-with-espresso/

This library looks promising: https://github.com/novoda/espresso-support
