### ISSUE TITLE
Fragment deprecation in Android P

### ISSUE THREAD

**Issue by miquelbeltran** [bluelinelabs/Conductor#411]
As leaked days ago: https://github.com/android/android-ktx/pull/161#issuecomment-363270555

> The next version of Android will deprecate the version of fragments that are part of the platform.

As I understand, Conductor uses a headless Fragment for the LifecycleHandler class.

https://github.com/bluelinelabs/Conductor/blob/df70e983be2f4b37930b78bf8fee90e77b57e53c/conductor/src/main/java/com/bluelinelabs/conductor/internal/LifecycleHandler.java

This means we would have to switch to use the Support Library Fragment. Anyone in the community has a better idea? Or would it be safe to ignore and keep using it?

**Comment by Zhuinden** [comment]
Just because it (platform fragment) is not developed further doesn't mean it'll stop working.

No need to depend on support library for a retained top-level fragment. I'd just add a `@SuppressWarning` personally.

**Comment by EricKuck** [comment]
I agree with @Zhuinden on this one. There's currently no reason to add a dependency on the support library to this project. If that ever changes (extremely unlikely) we'll definitely make the transition quickly though.
