### ISSUE TITLE
Issue with demo - TargetDisplayController / TargetTitleEntryController

### ISSUE THREAD

**Issue by jcuypers** [bluelinelabs/Conductor#412]
Call to setTextView() is useless, since onTitlePicked is called before the View is ready.
When the function is called it doesnt execute since its TextView is null.  it gets called a second time within the OnViewBound where it can execute with the new values.

```
   @Override
    public void onTitlePicked(String option) {
        selectedText = option;
        setTextView();
    }
```

**Comment by EricKuck** [comment]
This is absolutely true for the demo. It was written this way to prevent bugs when subtle things change. For example, a developer using this code as guidelines for their app might want to use a `ControllerChangeHandler` that doesn't remove the `from` view. In this case, the view would never be destroyed, and therefore `onViewBound` wouldn't be called when the controller is going to reappear. We were just going for covering all possible cases that might reasonably arise.
