### ISSUE TITLE
EditText issues when setting value

### ISSUE THREAD

**Issue by jcuypers** [bluelinelabs/Conductor#413]
Maybe someone knows the whole technical story behind this (and how to deal with it), but I want to share this to avoid people wasting time (as I did).  There seems to be an issue when trying to set the value of an EditText together with the lifecycle of Conductor.  
I'm passing values around back/forth as shown in the  demo ("Target").  TextView doesn't have the issue.   
I've have found a "solution" by applying `edittextfield.setSaveEnabled(false);`  as described here
[link](https://stackoverflow.com/questions/13303469/edittext-settext-not-working-with-fragment)

Not sure if this is the best solution. Any ideas?

**Comment by miquelbeltran** [comment]
Hi @jcuypers I cannot understand the issue. Can you describe a bit more problem you have? For example what you expect to happen vs what actually happens.

**Comment by jcuypers** [comment]
Hi @miquelbeltran Sorry for that. My descriptions are notoriously hard to decypher :) I can explain based on the existing Target example in the demo.   just convert the textview (id:tvselection) into an edittext and the result will not appear (setText will refuse to work, setHint works as a cross-check).
Only after you set EditTextField.setSaveEnabled(false) in onViewBound everything works as expected.

**Comment by PaulWoitaschek** [comment]
Thanks for sharing!

As this happens with fragments too, this seems like the regular behavior so I'm closing this now.
