### ISSUE TITLE
Lifecycle issue with NavigationView and Parent/Child controllers

### ISSUE THREAD

**Issue by curiousily** [bluelinelabs/Conductor#416]
Here's a sample project that reproduces the issue [https://github.com/iPoli/Conductor-Lifecycle](https://github.com/iPoli/Conductor-Lifecycle).

We have standard Activity with DrawerLayout in RootController (HomeController).

The controllers look like this:

```kotlin
class HomeController : RestoreViewOnCreateController() {
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup,
        savedViewState: Bundle?
    ): View {
        val view = inflater.inflate(R.layout.controller_home, container, false)
        view.showNextButton.setOnClickListener {
            router.pushController(
                RouterTransaction.with(SecondController()).pushChangeHandler(
                    FadeChangeHandler()
                ).popChangeHandler(FadeChangeHandler())
            )
        }
        return view
    }

    override fun onAttach(view: View) {
        Timber.d("Home before attach")
        super.onAttach(view)
        Timber.d("Home after attach")
        val childRouter = getChildRouter(view.childRouterContainer, null)
        if (!childRouter.hasRootController()) {
            childRouter.setRoot(
                RouterTransaction.with(ChildController()).pushChangeHandler(
                    FadeChangeHandler()
                ).popChangeHandler(FadeChangeHandler())
            )
        }
    }
}

class ChildController : RestoreViewOnCreateController() {

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup,
        savedViewState: Bundle?
    ): View {
        return inflater.inflate(R.layout.controller_child, container, false)
    }

    override fun onAttach(view: View) {
        Timber.d("Child before attach")
        super.onAttach(view)
        Timber.d("Child after attach")
    }
}

class SecondController : RestoreViewOnCreateController() {
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup,
        savedViewState: Bundle?
    ): View {
        val view = inflater.inflate(R.layout.controller_second, container, false)
        view.goBackButton.setOnClickListener {
            Timber.d("Pressing Back")
            router.handleBack()
        }
        return view
    }

}
```

When the `NavigationView` in `controller_home.xml` is commented out we obtain the following output at start:

```
Home before attach
Home after attach
Child before attach
Child after attach
```

After pressing the buttons the following is obtained:

```
Home before attach
Home after attach
Child before attach
Child after attach
```

Which is expected, since we want to prepare the parent controller before attaching the child.

When we uncomment the `NavigationView` at start we have:

```
Home before attach
Home after attach
Child before attach
Child after attach
```

So far, so good. However, after clicking the buttons we have:

```
Child before attach
Child after attach
Home before attach
Home after attach
```

Again, here is the sample [https://github.com/iPoli/Conductor-Lifecycle](https://github.com/iPoli/Conductor-Lifecycle).

Is this behavior expected?

**Comment by jcuypers** [comment]
For what it's worth:  I haven't seen this kind of behavior. I use a similar, but not identical setup.   activity/homecontroller with navigationdrawer, which points to another controller with viewpager/tablayout and multiple children (RouterPagerAdapter), with additional navigation from the children to other controller add/edit/... functionality

**Comment by curiousily** [comment]
Hi @jcuypers,

Yes, your setup looks kinda similar but not identical. Thanks for the quick response!

I just rerun the sample just to make sure I wasn't imagining things 😸 Turns out I was not.

The issue is reproducible using `2.1.5-SNAPSHOT` as well.

**Comment by polyvjk** [comment]
I also managed to reproduce it and it doesn't matter if the NavigationView is in another container.

**Comment by curiousily** [comment]
We've managed to workaround the issue by placing the `NavigationView` above the `CoordinatorLayout` and using `view.rootCoordinator.bringToFront()` in `onDetach()` and `view.navigationView.bringToFront()` in `onAttach()` in `HomeViewController`. 

So is it order (z-order) issue?

**Comment by EricKuck** [comment]
I have absolutely no idea what the cause of this is. If you use the debugger, you can see that the views are actually being attached by Android out of order. Since `onAttach` is the callback that happens when the view is attached, this is technically the correct behavior. That being said, it's weird and hard to handle, so I'll try to do a workaround for it.
