### ISSUE TITLE
Integrating React Native and Conductor

### ISSUE THREAD

**Issue by mradzinski** [bluelinelabs/Conductor#418]
Hi, has anyone attempted to integrate a RN component inside a Controller? Just wondering how possible it is to do such thing. I know for a fact its possible to do it on a Fragment, but kind of clueless on how to integrate a component inside a Controller and handle the lifecycle of both 😕.

**Comment by EricKuck** [comment]
If you can do it in a Fragment you can almost definitely do it in a Controller. I don't have an interest in RN, so I can't really be of help here.

**Comment by PaulWoitaschek** [comment]
It does not seem to be supported by RN natively.

You could port the implementation of this project to conductor: https://github.com/hudl/react-native-android-fragment/
