### ISSUE TITLE
Questions about the Bundle named "LifecycleHandler.routerState*******"

### ISSUE THREAD

**Issue by wemped** [bluelinelabs/Conductor#420]
Using version 2.1.4.

When minimizing/closing the app, the activity's `onSaveInstanceState` is called, and the bundle size is pretty large. Most of the size is coming from a bundle with a key that always looks something like `LifecycleHandler.routerState2131230819`.

This is causing a TransactionTooLargeException and crashing the app as soon as it's minimized/closed.

And I see that most of the size of the data in this `LifecycleHandler.routerState2131230819` is my own necessary data for each Controller, that is created using a pattern discussed in  #3. 

```
public SomeController(@DrawableRes int mainImage, @StringRes int descriptionText) {
           // there is a builder here already!
           this(new BundleBuilder(new Bundle())
                .putInt(KEY_IMAGE, mainImage)
                .putInt(KEY_TEXT, descriptionText)
                .build());
    }

    public SomeController(Bundle args) {
        super(args);
    }
    // ...
}
```

Question 1: would removing this bundle be problematic? Currently I have a fix that seems to work:
```
//MainActivity.kt

override fun onSaveInstanceState(outState: Bundle?) {
       super.onSaveInstanceState(outState)

       outState?.keySet()?.filter { it.contains("LifeCycleHandler", ignoreCase = true) }?.forEach {
            outState.remove(it)
       }
}
```

Question 2: Are there better options to store data for each Controller than the constructor mentioned above - that doesn't cause this bundle to be huge?

Previously I was not calling `super.onSaveInstanceState()` in `MainActivity` at all, and it caused a hard-to-reproduce StackOverflow that I brought up here #419. So I want to be careful not to break something else in Conductor that is equally hard to solve.

**Comment by PaulWoitaschek** [comment]
I'm not sure what you are doing but by putting ints and strings in a bundle you are definitely not causing the TransactionTooLargeException.

Maybe you are passing real data to the controller? In that case you should persist the data somewhere else and just pass an id key for the data.

**Comment by wemped** [comment]
@PaulWoitaschek Thanks for the response, I think you are on to something. I come from an iOS background, and still not familiar with all the lifecycle pitfalls in Android.

What I am doing is passing a “Model” to that Controller’s initializer. The Model contains mostly just strings/ints. But that Controller contains a recyclerview, which is populated by an api, and I store the data from the api in that same “Model”. So the further you scroll, the more data is stored in the Model.

I suspect the recyclerview’s data in the Model is the cause of the large bundle.


I’m still not quite understanding how the information in this bundle is used. My assumption would be it is used to rebuild the Controller, but my current solution wipes out everything in that bundle - and if I close/minimize the app and reopen it, all the data persists. How is that possible?

I’ve been looking around for ways to test/reproduce the different ways the OS can reopen the app from the many different background states, but I’m not coming up with much. Needless to say it’s very hard to develop for these cases I can’t currently test. Do you know of a good way to test these cases? I know Conductor’s goal is to simplify some of this lifecycle management, does that mean I only need to test a subset of these cases?

**Comment by EricKuck** [comment]
It sounds like you're likely storing far too much data in the arg Bundle. You should pass the minimum amount of data you need to create a screen into the constructor, just like you'd do for an Activity or Fragment. If more data that needs to be saved for state restoration is creating during the session, that can be saved in `onSaveInstanceState`. Dynamically adding and subtracting to the Bundle passed into the constructor isn't supported.

**Comment by EricKuck** [comment]
Regarding your question of how to test different background states, open the developer options on your phone. "Don't keep activities" is good for testing what happens if Android needs to recreate an activity. Setting the "Background process limit" to 0 is a good way to test what happens if Android kills your process entirely.
