### ISSUE TITLE
Adding onRequestPermissionsResult and onActivityResult to Controller.LifecycleListener?

### ISSUE THREAD

**Issue by angusholder** [bluelinelabs/Conductor#421]
We use NFC in a lot of places in our app, which mean many controllers have to do the whole thing of:

    if (nfcAntennaEnabled) {
        if (hasPermission(NFC)) {
            enableNfcReader()
        } else {
            requestNfcPermission()
        }
    } else {
        startActivityForResult(Intent(Settings.ACTION_NFC_SETTINGS))
    }

and then override onRequestPermissionsResult and onActivityResult to receive the response from both of those. Does it sound reasonable to add these two callbacks to the lifecycle listener?

**Comment by angusholder** [comment]
I've ended up going with a 'headless Fragment' style of solution: put all my NFC logic into a Controller which returns an empty View() in onCreateView, and becomes a child of any Controller where I want to use NFC, allowing me to use composition instead of inheritance to factor out all my NFC handling code.

**Comment by hannesstruss** [comment]
Related: https://github.com/bluelinelabs/Conductor/issues/358
