### ISSUE TITLE
getRouter from recyclerview adapter

### ISSUE THREAD

**Issue by chingiz** [bluelinelabs/Conductor#423]
What is the safest way to push controller from recyclerview adapter?

**Comment by inorichi** [comment]
I'd delegate the call from the adapter to the controller and push new controllers there. Adapters shouldn't handle navigation.

**Comment by chingiz** [comment]
but what if you have clickable text(spannable) with different values to navigate through app?

**Comment by inorichi** [comment]
It makes no difference. You just need to create an interface with one method for every clickable view, like `onRowClicked(position)`, ...

Then implement that interface in your controller and pass it to the adapter as constructor parameter. There are plenty of answers in StackOverflow, for example https://stackoverflow.com/questions/44238018/recyclerview-onclick-for-multiple-buttons-and-handling-from-activity
