### ISSUE TITLE
Lifecycle problem

### ISSUE THREAD

**Issue by chingiz** [bluelinelabs/Conductor#427]
I'm having difficulty with lifecyle of the conductor.

I do add things to recyclerview adapter, select one of the items to push to the next controller, when i  handleback things in recyclerview duplicates it's items.

I do use onAttach to handle this situtation, but it seems that it is not working. What should I do?

**Comment by joaolisboa** [comment]
onAttach will get called when the Controller is attached and if it was already instanced it'll add the new items. You could use onCreateView right after the layout is inflated.

#321 - This should help you understand the lifecycle.

**Comment by chris6647** [comment]
Alternatively, you could improve the RecyclerView's adapter to update its entries using DiffUtils or something similar, which would cause it to update the elements only if needed, instead of adding duplicates.
