### ISSUE TITLE
isBeingDestroyed() returns false in 2.1.5-SNAPSHOT

### ISSUE THREAD

**Issue by MRezaNasirloo** [bluelinelabs/Conductor#429]
Hi,
I noticed a bug in the SNAPSHOT version.
Calling `popToRoot()` on the main `Router` without providing a `ChangleHandler`  or calling it with `SimpleSwapChangeHandler()` will cause the `isBeingDestroyed()` method of the top Controller to return `false` in its `onDestroyView()` method.

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        router = Conductor.attachRouter(this, container, savedInstanceState)

        button.setOnClickListener {
            ControllerHome.counter = 0
            router.popToRoot(SimpleSwapChangeHandler()) // <=== Causes the isBeingDestroyed to return false
            // router.popToRoot(HorizontalChangeHandler()) // Works as expected
        }
        if (!router.hasRootController()) {
            router.setRoot(RouterTransaction.with(ControllerHome()))
        }

    }
```
Calling `setBackStack`  has the same result.

2.1.4 works as expected.

Here is a sample project in [my github repo](https://github.com/MRezaNasirloo/conductor-bug-issue-429)

**Comment by EricKuck** [comment]
Thanks for the report! Should be fixed now.
