### ISSUE TITLE
Sonatype Authentication

### ISSUE THREAD

**Issue by sockeqwe** [bluelinelabs/Conductor#43]
As discussed in #42 here is just a friendly reminder how to setup authentication for snapshot deployment from travis properly (remove previous `env / global / secret` definitions:
```
travis encrypt -r bluelinelabs/Conductor "ORG_GRADLE_PROJECT_NEXUS_USERNAME=InsertYourUsername" --add
travis encrypt -r bluelinelabs/Conductor "ORG_GRADLE_PROJECT_NEXUS_PASSWORD=InsertYourPassword" --add
```

**Comment by EricKuck** [comment]
Fixed now. Thanks @sockeqwe and @JakeWharton for the help on this!
