### ISSUE TITLE
[Question] Is Conductor Project is still getting the love?

### ISSUE THREAD

**Issue by nksaroj** [bluelinelabs/Conductor#430]
Sorry, I have been a great fan of conductor and love to use it.
But, I am bit reluctant as seem to be it's not getting any more love as @EricKuck is very busy.

Last commit was made in Oct 2017. Does it mean there are no bugs or it's not getting any momentum ?

There should someone who is still can lead the project to help the life of the Android/Conductor community

**Comment by dimsuz** [comment]
I agree, project needs some love an attention. It's quite stable, but housekeeping is needed as can be seen by growing number of unhandled issues and (to smaller amount) PRs. 

This has been already discussed in #401 (though no practical outcome for now)

**Comment by Rawa** [comment]
I'm afraid this library risk becomming obsolete because of the lack of support, and especially now when Android P introduces the Navigation component. The NavHostFragment is basically the same thing as conductor.

**Comment by PaulWoitaschek** [comment]
I'm also worried. I love the project and made a big commitment as it's basically all over my project.

@EricKuck Maybe you can spend some of your time to delegate the daily work (managing PR's, closing and answering Issues etc) to contributors?

It feels like we have quite the active community who is willing to contribute to this project.

**Comment by Rawa** [comment]
@PaulWoitaschek I also have it in my current project. I looked into the Navigation component. Luckily it is quite similar and a transition should not be too hard once it is released.

**Comment by MRezaNasirloo** [comment]
I've already moved on, removing conductor from my project, it wasn't too much of a borden.
Conductor and Framgemt API have lots of similaties and if your code is abstract enough you shouldn't have much of a problem. 

Conductor was a breeze of fresh air but it didn't last long.

**Comment by tomblenz** [comment]
I don't think the Navigation lib is up to snuff yet - it is still in alpha, but it doesn't seem to meet Conductor's transition customisation potential.

**Comment by nksaroj** [comment]
Agree @tomblenz . Conductor navigation is way richer compare to the navigation component.

**Comment by EricKuck** [comment]
I just took a first stab at a pretty robust set of contribution guidelines that should really move this project along. Any thoughts? https://github.com/bluelinelabs/Conductor/blob/develop/CONTRIBUTING.md

**Comment by tomblenz** [comment]
Beautiful

**Comment by nksaroj** [comment]
Thanks @Erickuck for making time for us. Glad to see you are back.

**Comment by curiousily** [comment]
@EricKuck can't wait for a new release 😉

Thanks for returning to improving Conductor!

**Comment by PaulWoitaschek** [comment]
Looks like this is back a live  :)
