### ISSUE TITLE
Best practice to save/restore Controllers in ViewPager

### ISSUE THREAD

**Issue by pro100svitlo** [bluelinelabs/Conductor#431]
Hi!

First of all, thanks a lot for such a nice tool!

Can you please provide me with some your best practices?
1) I have controller with viewPager inside. And there 2 controllers inside it, one per each page.
Eveything works ok. But when I rotate phone, 2 controllers are restoring by library and then, there are 2 controllers set by me... as result - looks like i see new created fragments, but not restored ones.
So how properly set and restore controllers to viewPager if I need save their states also?

2) I need to show title for tabLayout. Because it should contain itemsCount (each page has list) I decide to do it via interface method ```getTitle()```. But because of adapter method ```getPageTitle()``` called earlier then child controllers created, i need to use dirty hack with ```post{}```. Also I need another dirty hack if I need to refresh tabLayout title fro contoller inside pager.

I guess it will be easy to understand, if I show some code here:

```
class MainListController: BaseController(), IMainListView {

    @Inject lateinit var presenter: MainListPresenter

    private lateinit var adapter:MainListPageAdapter

    private lateinit var tabLayout: TabLayout
    private lateinit var viewPager: ViewPager

    override fun onViewCreated(view: View) = with(view){
        tabLayout = findViewById(R.id.tabLayout)
        viewPager = findViewById(R.id.pager)
        adapter = MainListPageAdapter(this@MainListController)
        viewPager.adapter = adapter
        tabLayout.setupWithViewPager(viewPager)

        val children = ArrayList<BaseController>().apply {
            add(FirstListController())
            add(SecondListController())
        }

        adapter.swap(children)
        post {
            //update tabLayout title
            adapter.notifyDataSetChanged()
        }
    }
}

class FirstListController: BaseController(), IFirstListView,
        MainListPageAdapter.ListPageTitle {

    private val PREF_TITLE = "PREF_TITLE"

    @Inject lateinit var presenter:FirstListPresenter

    private var pageTitleStr:String? = null

    override fun onViewCreated(view: View) = with(view){
        setPresenter(presenter)
        pageTitleStr = getString(R.string.tab_first)
    }

    override fun getPageTitle(): String? {
        return pageTitleStr
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.putString(PREF_TITLE, pageTitleStr)
    }

    override fun onRestoreInstanceState(savedInstanceState: Bundle) {
        super.onRestoreInstanceState(savedInstanceState)
        pageTitleStr = savedInstanceState.getString(pageTitleStr)
    }
}

class MainListPageAdapter(host:Controller) : RouterPagerAdapter(host){

    private var list:ArrayList<BaseController>? = null

    override fun configureRouter(router: Router, position: Int) {
        if (!router.hasRootController()){
            val page = list!![position]
            router.setRoot(RouterTransaction.with(page))
        }
    }

    override fun getPageTitle(position: Int): CharSequence? {
        return (list!![position] as ListPageTitle).getPageTitle()
    }

    override fun getCount(): Int = list?.size ?: 0

    fun swap(l:ArrayList<BaseController>?){
        list?.clear()

        list = if (l != null)
            ArrayList(l)
        else
            null

        notifyDataSetChanged()
    }

    interface ListPageTitle {
        fun getPageTitle():String?
    }

}
```

Will be glad to hear your best practices :)

**Comment by pro100svitlo** [comment]
this is become rather serious question, cos i see same behaviour (which is ok for your lib) when i click list item and go to the detailView.
So when I return with backBtn, main controller recreated from state, inside his onCreateView I add to viewPager adapter two controllers instead of using that ones, whose state also recreates...

**Comment by EricKuck** [comment]
I'm a little unclear as to what you're trying to do here. Conductor restores the controllers that were already in your ViewPager, so why are you resetting it with all new Controllers each time? You're explicitly removing the restored ones and replacing them with your brand new ones.
