### ISSUE TITLE
Lost values of variables in onCreateView

### ISSUE THREAD

**Issue by stonelai75** [bluelinelabs/Conductor#435]
The value of phhotoname and photopath gets lost at the step3 and below. How come?

=======================================
public class zoomController extends Controller implements absImageLoader {

    private String _photoname;
    private String _photoPath;
    private ViewGroup _rootView;

    public zoomController(String _path, String _name){
        Log.i("step1", _path + ":" + _name);
        Bundle _bundle = new Bundle();
        _bundle.putString("name", _name);
        _bundle.putString("path", _path);
        new zoomController(_bundle);
    }

    public zoomController(Bundle _bundle)
    {
        super(_bundle);
           _photoname = _bundle.getString("name");
           _photoPath = _bundle.getString("path");
        Log.i("step2", _photoPath + ":" + _photoname);
    }

    @Override
    protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
        Log.i("step3", _photoPath + ":" + _photoname);
        return inflater.inflate(R.layout.controller_zoom, container, false);
    }

    @Override
    protected void onChangeEnded(@NonNull ControllerChangeHandler changeHandler, @NonNull ControllerChangeType changeType) {
        super.onChangeEnded(changeHandler, changeType);
        Log.i("step4", _photoPath + ":" + _photoname);
        if (_rootView == null)
        {
            _rootView = (ViewGroup) getView();
            _rootView.getChildAt(1).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    MainActivity.getRouter().handleBack();
                }
            });
            ViewHelper.showLoader(_rootView, true);
            Log.i("step5", _photoPath + ":" + _photoname);
            bitmapLoader _loader = new bitmapLoader(_photoPath, _photoname, this);
            _loader.execute();
        }
    }

    @Override
    public void onImageLoaded(Bitmap _bitmap){
        ViewHelper.showLoader(_rootView, false);
        PhotoView _photoView = (PhotoView) _rootView.getChildAt(0);
        _photoView.setImageBitmap(_bitmap);
    }
}

**Comment by EricKuck** [comment]
There's something else going on that isn't listed in the code you posted. It isn't possible for a variable to just become null like you're saying. Java doesn't work that way. Maybe you actually have 2 controller instances?

**Comment by PaulWoitaschek** [comment]
In the constructor you are creating just another instance of the class itself and don't do anything without it. 
Rather you should call super(bundle) with the filled bundle. 

Also it's really confusing to break Java conventions like naming classes lowerCase.
