### ISSUE TITLE
  AnimatorChangeHandler Animator with startDelay

### ISSUE THREAD

**Issue by jsaber90** [bluelinelabs/Conductor#436]
i use custom AnimatorChangeHandler with startDelay but there is strange behavior  the controller appear then after delay the animation apply

 @NonNull
    @Override
    protected Animator getAnimator(@NonNull ViewGroup container, @Nullable View from, @Nullable View to, boolean isPush, boolean toAddedToContainer) {
        AnimatorSet animatorSet = new AnimatorSet();

        if (isPush) {
            animatorSet.setStartDelay(3000);
            if (to != null) {
                animatorSet.play(ObjectAnimator.ofFloat(to, View.TRANSLATION_X, to.getWidth(), 0));
            }
        } else {
            if (from != null) {
                animatorSet.play(ObjectAnimator.ofFloat(from, View.TRANSLATION_X, from.getWidth()));
            }
        }

        return animatorSet;
    }

**Comment by EricKuck** [comment]
Right now you're doing nothing for 3 seconds (so the view displays like normal, with no translation), then you start an animation from right to left. If you want the view to be all the way to the right side before the animation starts, you'll have to set the translation on it (`to.setTranslationX(to.getWidth())`)

**Comment by jsaber90** [comment]
thanks that help.
