### ISSUE TITLE
ControllerPagerAdapter does not save or restore view state

### ISSUE THREAD

**Issue by R4md4c** [bluelinelabs/Conductor#44]
Hello,

Firstly, Thanks a lot for this great library!

I'm using ControllerPagerAdapter inside a ViewPager, and each child controller contains a RecyclerView.
The problem is that my RecyclerView displays a list of 50 items of size and I'd like to save the 50 items in a bundle so that I could prevent loading it from the backend.

The problem arises when I scroll the ViewPager and the adapter's destroyItem method is called, you destroy the Child controller completely and remove it from the host controller as a result neither onSaveViewState or onRestoreViewState is called and I'm unable to restore the removed page state when the user returns to it and everything is loaded all over again.

Perhaps restoreState and saveState should be overriden to fix this behavior?

Hope that I've been able to explain the issue clearly.

Thanks!

**Comment by EricKuck** [comment]
You're right, the controllers are currently being destroyed in the PagerAdapter's `destroyItem` method. I don't think this is the wrong behavior for a lot of applications, but it will cause issues for restoring state. I'm thinking maybe this should be a flag to determine whether a page should be destroyed or simply removed from the window (which would allow its state to be saved).

**Comment by R4md4c** [comment]
I was thinking about doing that myself by extending ```ControllerPagerAdapter``` to ```ControllerStatePagerAdapter```, but I realized that the methods that are responsible for saving and restoring state are package private, and I can't access them from outside. 

So I'm interested to know how would you approach that?

**Comment by EricKuck** [comment]
This is finally addressed in baa9072b180c364097f42becdb53219213bf3c6d, which will be released when v2 comes out. A release candidate should be out shortly.

**Comment by EricKuck** [comment]
This is now available in the v2 release candidate. Updated docs can be found at https://github.com/bluelinelabs/Conductor/blob/v2/README.md. Feel free to suggest any changes before before we officially go to v2!
