### ISSUE TITLE
Removing Controller from the backstack while adding new one

### ISSUE THREAD

**Issue by curiousily** [bluelinelabs/Conductor#448]
Hi all,

Our team has the following situation:

Given 3 controllers: A, B, C (all using the same Router)

We start from A and go to B. While being at B we transition (with `pushController()`) to C and want to simultaneously remove B from the backstack (so users can go back directly to A if they press any back button).

We observed some weird transitions using 
```kotlin
popCurrentController()
pushController()
```
Maybe something related to #410 ?

What is a proper way to handle such situation, that is, remove a Controller from the backstack?

Thanks!

**Comment by dimsuz** [comment]
You can use `replaceTopController()` for that.

**Comment by curiousily** [comment]
Thanks, @dimsuz! That did the trick!
