### ISSUE TITLE
isBeingDestroyed() is false before process death

### ISSUE THREAD

**Issue by ghost** [bluelinelabs/Conductor#449]
I trying to call `isBeingDestroyed()` from `onDetach()` and it returns false before process death despite of the `Controller` is going to be destroyed.

_Conductor version: 2.1.4_
_also reproducible on last snapshot_

**Comment by EricKuck** [comment]
You've provided no details at all. What do you mean before process death? What's happening in the app? Feel free to reopen when this is an actionable issue.

**Comment by ghost** [comment]
@EricKuck , 
_Sorry for that, I thought I provided enough information, but yes, I could add some details_

### In brief

Description of the problem in two points:
1. `Controller.isBeingDestroyed()` is TRUE during `Controller.onDetach()` if current Controller is detached because of `router.popCurrentController()`.
2. And `Controller.isBeingDestroyed()` is FALSE during `Controller.onDetach()` if Controller is detached because of Activity is going to be destroyed or process is going to killed by the system.

But controller will be actually destroyed in both cases, so `Controller.isBeingDestroyed()` must return TRUE in both cases too.

-------

### How to reproduce

For example, let's assume we have two screens:
1. `HomeController` with **go to Details(`DetailsController`) button**
2. `DetailsController` with **back button**

To investegate this issue, lets write such `HomeController`
```
class HomeController : Controller() {

    companion object {
        private const val TAG = "HomeController"
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View {
        val view = LayoutInflater.from(activity!!).inflate(R.layout.home, container, false)
        view.details_button.setOnClickListener {
            routeToDetails()
        }
        return view
    }

    private fun routeToDetails() {
        router.pushController(
                RouterTransaction.with(DetailsController())
                        .pushChangeHandler(HorizontalChangeHandler())
                        .popChangeHandler(HorizontalChangeHandler())
        )
    }

}
```

And `DetailsController` with listeners to `onDetach` and `onDestroy`:
```
class DetailsController : Controller() {

    companion object {
        private const val TAG = "DetailsController"
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View {
        return LayoutInflater.from(activity!!).inflate(R.layout.details, container, false).apply {
            back_button.setOnClickListener {
                router.popCurrentController()
            }
        }
    }

    override fun onDetach(view: View) {
        Log.d(TAG, "detaching, isBeingDestroyed='$isBeingDestroyed'")
        super.onDetach(view)
    }

    override fun onDestroy() {
        Log.d(TAG, "destroying")
        super.onDestroy()
    }

}
```

#### Testing case 1

1. App starts with `HomeController`
2. Click on **GO TO DETAILS**
3. `DetailsController` pushed to front
4. Click on **BACK** button
5. See at logcat output:
```
D/DetailsController: detaching, isBeingDestroyed='true'
D/DetailsController: destroying
```
great!

#### Testing case 2
with `Don't keep Activities` enabled in Developer options to force Activity to be destroyed by system when app goes in background

1. App starts with `HomeController`
2. Click on **GO TO DETAILS**
3. `DetailsController` pushed to front
4. Go to tasks view(recent apps) so activity will be destroyed (`Don't keep Activities` enabled in Developer options!)
5. Activity is destroyed
6. See at logcat output:
```
D/DetailsController: detaching, isBeingDestroyed='false' // why false?
D/DetailsController: destroying // it's destroyed!
```
not great :(

I think that this is unexpected behavior and should be fixed. What do you think?

**Comment by EricKuck** [comment]
Thanks for all the details. I'll be going through all this soon.

**Comment by EricKuck** [comment]
After going through all this, I'm pretty sure you're seeing expected behavior. At the time that `onDetach` is called, the Activity has not yet started to be destroyed (Android does this after the Activity is fully backgrounded). So it's true that the Controller is not yet being destroyed at the time of `onDetach`.

Additionally, I don't believe this is anything you'd actually see in the real world. There are no scenarios in which Android will kill an Activity the instant it's backgrounded, with the exception of this developer option being checked.

Even if this was the incorrect behavior and it was something that could happen in the real world, I don't believe there's anything we could do about this. AFAIK there's no way to tell if an Activity will be destroyed in the near future.

**Comment by ghost** [comment]
Thanks for your time and clarification!
