### ISSUE TITLE
ControllerLifecycleRegistryOwner propagates incorrect state on `postDetach`

### ISSUE THREAD

**Issue by molokoka** [bluelinelabs/Conductor#451]
Hello!

We are developing a small app with LiveData in it. And we would like to release soon, but we face small bug because LiveData wasn't unsubscribed correctly after controller detach.

I believe this happens because the released version of conductor archlifecycle 0.1.1 propagates incorrect state to lifecycleRegistry on method `postDetach` :
```
@Override
public void postDetach(@NonNull Controller controller, @NonNull View view) {
    lifecycleRegistry.markState(State.STARTED);
}
```

But in repository code, everything looks ok. 
Can you please release a fresh version of conductor archlifecycle.

Best regards!

**Comment by EricKuck** [comment]
`2.1.5` has just been pushed to maven central. Sometimes takes a bit to be available, but it's there.

**Comment by dimsuz** [comment]
@EricKuck will changelog be available? After such a long delay it would be great to see what exactly has changed. I suspect its mostly bugfixes?

**Comment by EricKuck** [comment]
Changelog is now up. Thanks for the reminder.
