### ISSUE TITLE
setBackstack() doesn't perform transition correctly.

### ISSUE THREAD

**Issue by cbnewham** [bluelinelabs/Conductor#453]
I'm using setBackstack() and I note that only the "to" view is animated correctly. The "from" view just vanishes without performing any animation even though the animation is being played correctly (i.e.: the view is View.VISIBLE and the Translation of the X value starts and ends at the correct values).

Some debugging indicates that "from" is having its height set to 0 somewhere before the animation starts, but I cannot see where - it appears to be at some time between when OnAnimationReadyOrAbortedListener() is set up and when its onReadyOrAborted() method is called in AnimatorChangeHandler.

**Comment by cbnewham** [comment]
Always find a solution once I've posted a question.

The process is sensitive to the layout being used to contain the views for Conductor. I had a Linear which I swapped to a Frame. All works fine now.

**Comment by EricKuck** [comment]
That makes sense, as the LinearLayout was likely swapped which view had MATCH_PARENT. LinearLayout doesn't support overlapping the way a FrameLayout does.
