### ISSUE TITLE
EasyPermissions integration

### ISSUE THREAD

**Issue by adin234** [bluelinelabs/Conductor#456]
any tutorials or sample code for this? basically, i want to request for permissions using [EasyPermissions](https://github.com/googlesamples/easypermissions) but right now it only accepts an activity as param, are there any ways to integrate this with the controllers?

**Comment by EricKuck** [comment]
That lib is hardcoded to only work with Activities and Fragments, so it's not going to work out of the box with anything else. You'd probably have to fork the library and copy their Fragment implementation to work for Controllers. Find and replacing "Fragment -> Controller" would most likely be all you needed.
