### ISSUE TITLE
RouterPagerAdapter page titles not being translated

### ISSUE THREAD

**Issue by ildar2** [bluelinelabs/Conductor#459]
I have string resourses `R.string.priceplans_title` and `R.string.services_title` for pager titles in two languages, but in reality only default language is used. All other strings in app are being translated correctly.

       RouterPagerAdapter pagerAdapter = new RouterPagerAdapter((Controller) mCallback) {
            @Override
            public void configureRouter(@NonNull Router router, int position) {
                if (!router.hasRootController()) {
                    Controller page;
                    switch (position) {
                        case 0:
                            page = new PriceplansController();
                            break;
                        default:
                            page = new ServicesController();
                            break;
                    }
                    router.setRoot(RouterTransaction.with(page));
                }
            }

            @Override
            public int getCount() {
                return 2;
            }

            @Override
            public CharSequence getPageTitle(int position) {
                switch (position) {
                    case 0:
                        return mContext.getString(R.string.priceplans_title);
                    default:
                        return mContext.getString(R.string.services_title);
                }
            }
        };
        mCallback.bindPager(pagerAdapter);
        mEventLogger.logOpenOffers();
    }

**Comment by EricKuck** [comment]
What is mContext? That's likely to be there source of your issue, not Conductor or the ViewPager.
