### ISSUE TITLE
Using Conductor + afollestad 

### ISSUE THREAD

**Issue by douglasalipio** [bluelinelabs/Conductor#462]
Hi guys,

Is it possible to use [afollestad](https://github.com/afollestad/material-dialogs) (Dialog lib) with Conductor?

**Comment by dimsuz** [comment]
This question should be asked on StackOverflow instead. This tracker is for bugs/suggestions for the library itself.

**Comment by PaulWoitaschek** [comment]
Yes it's completely unrelated to conductor.

**Comment by douglasalipio** [comment]
I see.
