### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by ursusursus** [bluelinelabs/Conductor#464]
Hi, is there any recipes type documentation with all the features? In you demo I dont know where to look for custom manipulating of backstack etc.

**Comment by EricKuck** [comment]
The readme has an overview. The javadoc is here: http://javadoc.io/doc/com.bluelinelabs/conductor/2.1.5. It's also open source. Any specific questions?

**Comment by ursusursus** [comment]
From top of my head: permissions, activity results, dialogs, synthetic back stack from say notification, screen flows (main > a > b > c > main), back disabling

**Comment by EricKuck** [comment]
Honestly all of that stuff is pretty self-explanatory.

`requestPermissions` is the same as it is for activities/fragments

Activity results aren't often used, assuming you're going single-activity. Regardless, there is a sample of this in the demo.

Dialogs are dialogs.

`setBackstack` does your synthetic backstack for you.

Pretty much every possible iteration of screen flow is demonstrated in the demo.

Back disabling is the same as it is with fragments.

Take some time to go through the demo app. It currently serves as the best way to find out how to do anything.
