### ISSUE TITLE
Help: Hierarchy single backstack-wise but multi view-wise?

### ISSUE THREAD

**Issue by ursusursus** [bluelinelabs/Conductor#465]
Hey, Id like to mimic this multi-activity behaviour.
I have screen where there is bottom nav and tabs. In some of the tabs there is a list. After clicking on a item of the list, new screen comes up. New screen should be "above" the bottom nav, i.e. fullscreen.

In fragment terms, Id use 2 fragment containers, each for each layer, like so

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <FrameLayout
            android:id="@+id/tabControllerContainer"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"/>

        <android.support.design.widget.BottomNavigationView
            android:id="@+id/bottomNav"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:menu="@menu/bottom_nav"/>
    </LinearLayout>

    <FrameLayout
        android:id="@+id/detailControllerContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</FrameLayout>
```

How can I mimic this in Conductor? I know I can have router per container but then I have 2 backstacks (per container) right?

Thanks

**Comment by EricKuck** [comment]
You can do this exactly like you would with Fragments, like you already said. Another (probably better) option would be to have a root-level controller that hosts the bottom nav view itself and the related views as child controllers. When you click a list item, you would push a new root controller.

So basically:
```
   HomeController          DetailController
-------------------       -------------------
|                 |       |                 |
| ChildController |       |     Details     |
|                 |  ->   |                 |
|                 |       |                 |
|                 |       |                 |
|                 |       |                 |
-------------------       |                 |
|   Bottom Nav    |       |                 |
-------------------       -------------------
```

**Comment by ursusursus** [comment]
Right, and how would I do that option 1? In controller I only have access to router afaik, which is already tied to view ontainer, or should I cast activity and then access the "fullscreen" router?

**Comment by EricKuck** [comment]
It would literally be the same implementation you mentioned in your first post, just swapping out FragmentManager for Router and Fragment for Controller. Again, this is not the way I'd recommend doing it.

**Comment by ursusursus** [comment]
Right, I just want to figure out the capabilities here.

I dont get it, could you post some pseudo code? If I were just to swap fragment manager etc, meaning I´d need 2 routers right? And isnt backstack router local? Then detail and home wouldnt know of each other, unless manually orchestrated, i.e. I have to manually let detail router to handle backstack first, then if unhandled, let home router at it?

**Comment by EricKuck** [comment]
That's correct. Your activity would have this:

```
if (!detailRouter.handleBack() && !homeRouter.handleBack()) {
    super.onBackPressed()()
}
```

**Comment by ursusursus** [comment]
Okay, thanks. That means item click within HomeController would need to access detailRouter instance, only via hacky way of getting it from activity. And thats what you advocate against?

**Comment by EricKuck** [comment]
Exactly. It's just much cleaner to have it work the way I laid out in my original response.

**Comment by ursusursus** [comment]
Right I get It know.

One more question, what If the detail screen were somehow transparent and Id like to see the previous view underneath? Would that work when replacing the root controller or would I need to have separate router+container then?

**Comment by EricKuck** [comment]
Yep that would still work. You'd probably want to make a custom ControllerChangeHandler that did whatever animation you want, but leaves the root controller in the view hierarchy.
