### ISSUE TITLE
RemovesFromViewOnPush setting to false allows me to click a view from previous view

### ISSUE THREAD

**Issue by juliansmartwave** [bluelinelabs/Conductor#472]
I set it to false on any push change handler. 

Clicking on the previous location of a button on the FrameLayout(for example) of my new view/controller triggers the onclick event of that button.

Why is this so?

**Comment by juliansmartwave** [comment]
well for a workaround, i've found i need to set the rootview layout of the top controller to clickable so as it wont pass click events to the view of the previous controller.

**Comment by MkhytarMkhoian** [comment]
I think you need to handle this case by your own because it's not a library responsibility

**Comment by EricKuck** [comment]
As @MkhytarMkhoian said, this is not something Conductor does, or should, handle. If you set an onClickListener on a view, that view is going to respond to clicks. You'd see the same thing with fragments.
