### ISSUE TITLE
popToRoot() does not trigger ControllerChangeHandler.ControllerChangeListener.onChangeCompleted()

### ISSUE THREAD

**Issue by michaelheiniger** [bluelinelabs/Conductor#476]
Hello,
The documentation of ``myRouter.popToRoot()`` states that it pops all controllers until the root is reached (root controller being not popped). As I understand, it should be equivalent to

``while(myRouter.getBackstackSize > 1 && myRouter.popCurrentController()) { /* do nothing*/ }``

However, as far as my tests show, when using ``myRouter.popToRoot()``, the function ``onChangeCompleted()`` of a listener ``ControllerChangeHandler.ControllerChangeListener`` previously added to ``myRouter`` is not called for all the popped controllers, but only for the top one (i.e. the first controller to be popped).

Is that a correct behavior ?

Thanks
Michael

**Comment by DrewCarlson** [comment]
This behavior is correct, a single change occurs from the top transaction to the target (root or tag).  Any transaction in between is simply omitted from the new backstack. See [`popToTransaction`](https://github.com/bluelinelabs/Conductor/blob/7a24f77b59a221f07c95bd70e834cf60b02c29c2/conductor/src/main/java/com/bluelinelabs/conductor/Router.java#L685-L706). The documentation for the `popToRoot` and `popToTag` methods could be improved.

**Comment by michaelheiniger** [comment]
Fair enough, thanks for the answer.
