### ISSUE TITLE
How to make "PIN screen on resume" - type of flow

### ISSUE THREAD

**Issue by ursusursus** [bluelinelabs/Conductor#478]
Hey, I am getting started with this library, and I love the ability to manipulate backstack. However Ive got one case I am not sure how to tackle.

_Usecase: Say banking app, you want to show PIN screen on every activity onResume (after it was paused once). In a pin screen you enter the pin and you should be where you left off._

For security? reasons Id like for there to not be any screens under PIN screen. So I would setRoot with PinController. **However now after entering pin I want to comeback to my previous (before pausing) backstack.** 

_How to go about this? Should I keep a reference to previous router.getBackstack? Is this safe?_ If so, it gets problematic to pass the list reference to the pinscreen to setBackstack upon entering pin. I think I like the sound of popping self better there.

I dont want to just to place PinController on top and disable backpress since back should take me out of the app. (although technically there will be no views under pin controller since they will be destroyed when popped via setRoot PinController)

**Comment by PaulWoitaschek** [comment]
I think this is what you actually want:

https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE

**Comment by ursusursus** [comment]
Isnt that just to prevent screenshoting? Im thinking of passcode in Dropbox app for example

**Comment by PaulWoitaschek** [comment]
An I misunderstood. You can add a PinController from Activity onStop without a Changehändler. 
Then when the users entered the pin you call popController on it.
Would that suffice your needs?

**Comment by ursusursus** [comment]
Well no, because if you push it, its on top of backstack, so backpress pops it and you see previous controller. Backpress should put the activty to background.

Unless you look at backstack manually in activity.onBackpress ..if top is pin super.onBackPress, which Id like to not do unless I have to

I was thinking setting it as current root would be nicer, and keeping previous backstack somewhere in a variable

**Comment by PaulWoitaschek** [comment]
The controller has a handleBack method

**Comment by ursusursus** [comment]
Right, but is only to return true if controller wants to consume the click event, no? How could it tell the router to finish activity?

**Comment by PaulWoitaschek** [comment]
Check it in the Activity's back press, what's the current controller and call super.onBackPressed accordingly.

**Comment by ursusursus** [comment]
Okay that was my plan B. Is that caching of backstack a no-go? That I feel would be more elegant

**Comment by EricKuck** [comment]
Caching of the backstack is indeed a no-go, as controllers are destroyed once they're removed from the router. Displaying a view over your current backstack doesn't have any downsides over the caching solution - what makes that more elegant?

**Comment by ursusursus** [comment]
The elegance would come in backhandling, meaning if PinController would be the only one on backstack, backpress would take me out of the app.

**Comment by pro100svitlo** [comment]
Just call activity.finish when handling back btn press and - voala!

**Comment by ursusursus** [comment]
Logic in onBackpress would be better
