### ISSUE TITLE
[Question] How do you keep DialogController's background transparent?

### ISSUE THREAD

**Issue by ildar2** [bluelinelabs/Conductor#480]
I tried copying code from demo, but my background is always gray, while in demo an underlying controller is seen through View's `android:background="@color/immersive_background"`

**Comment by MkhytarMkhoian** [comment]
Can you show your code?

**Comment by EricKuck** [comment]
Most likely you're using a change handler that's removing the controller you're trying to show the dialog over. Make sure `removesFromViewOnPush` is false for whatever change handler you're using.
