### ISSUE TITLE
Postpone a SharedElementTransition

### ISSUE THREAD

**Issue by ghost** [bluelinelabs/Conductor#483]
Hi, I know this is a topic that has been already debated but I didn't find a solution.

I don't want anyone to do the work for me, but I need suggestions.

I need to perform a shared element transitions between two controller and I know that the built in changehandlers could wait for views to be fully laid out before executing. What if I want to postpone the transition until an image is fully loaded by Glide?

**Comment by IVIanuu** [comment]
I never tried it but it should be possible to add your image view to the waitForTransitionNames list and set the transitionName when the image is loaded.

**Comment by ghost** [comment]
@IVIanuu it works like a charm. I could close this issue. Thank you very much!
