### ISSUE TITLE
open a new Controller in a componentized architecture project

### ISSUE THREAD

**Issue by tonycheng93** [bluelinelabs/Conductor#485]
How to open a new Controller in a componentized architecture project?

**Comment by PaulWoitaschek** [comment]
I don't understand the question. Can you elaborate which issues you are facing?

**Comment by tonycheng93** [comment]
Thank you for your reply.Below is my project structure diagram.
![componentized](https://user-gold-cdn.xitu.io/2018/7/30/164eb7411becef8e?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)
`Login`, `Live`, and `Pay` are independent of each other。Now i want to push a `LoginController` in `Pay` module,but in `Pay` module,i can't get a instance of `loginController`.

**Comment by ShaishavGandhi** [comment]
There are three options:
1. Rethink whether `Login` and `Pay` modules really should be independent of each other. May be `Login` should be imported in `Pay`. 
2. Put `LoginController` in `Base` module. 
3. Keep the same structure but construct the `LoginController` via reflection. Basically reference the class path and use Java/Kotlin to get a class reference and new instance. Write a test to make sure the class name doesn't change.

In either cases, this is a general modular architecture design problem and not related to Conductor.

**Comment by abyrnes** [comment]
Chances are when you're finally pushing the controller it only matters that it's an instance of `Controller` and not `LoginController`. What I'd recommend is providing an interface in `Base` that is some sort of controller factory:

```kotlin
interface ControllerFactory {
  fun createLoginController(): Controller
}
```
or
```kotlin
interface ControllerFactory {
  enum class Screen { LOGIN }

  fun createController(screen: Screen): Controller
}
```

Something like that. Then your app will have the implementation of this interface and can tie everything together

**Comment by dimsuz** [comment]
We have something like this, a tiny abstraction on top of Conductor's Router, but instead of `enum` we use a `sealed class`. This allows to pass parameters. A general layout is this:

```kotlin
sealed class AppRoute {
  object Screen1 : AppRoute()
  data class Screen2(val param1: String, val param2: Boolean) : AppRoute()
}
```
Then there are "screen keys" which are objects that know how to create `Controller`:
```kotlin
abstract class ScreenKey() : Parcelable {...}

@Parcelize
data class Screen2Key(val param1: String, val param2: Boolean) : ScreenKey() {
  override fun createController(): Controller { 
     /* creates controller by putting `this` which is Parcelable into its args bundle */
  }
}
```

There's a factory which maps Routes to Keys

```kotlin
class ScreenKeysFactory : Function1<AppRoute, ScreenKey> {
  fun invoke(route: AppRoute): ScreenKey {
    return when (route) {
      is Screen1 -> Screen1Key
      is Screen2 -> Screen2Key(route.param1, route.param2)
    }
  }
}
```

And finally a tiny abstraction which we call `Router` which works only with `AppRoute`s, contains methods to push/pop/etc and translates that to Conductor transactions.

All this allows us to use routing in presenters/coordinators without having them to know anything about conductor or whatever view routing library is used.

**Comment by tonycheng93** [comment]
> We have something like this, a tiny abstraction on top of Conductor's Router, but instead of `enum` we use a `sealed class`. This allows to pass parameters. A general layout is this:
> 
> ```kotlin
> sealed class AppRoute {
>   object Screen1 : AppRoute()
>   data class Screen2(val param1: String, val param2: Boolean) : AppRoute()
> }
> ```
> 
> Then there are "screen keys" which are objects that know how to create `Controller`:
> 
> ```kotlin
> abstract class ScreenKey() : Parcelable {...}
> 
> @Parcelize
> data class Screen2Key(val param1: String, val param2: Boolean) : ScreenKey() {
>   override fun createController(): Controller { 
>      /* creates controller by putting `this` which is Parcelable into its args bundle */
>   }
> }
> ```
> 
> There's a factory which maps Routes to Keys
> 
> ```kotlin
> class ScreenKeysFactory : Function1<AppRoute, ScreenKey> {
>   fun invoke(route: AppRoute): ScreenKey {
>     return when (route) {
>       is Screen1 -> Screen1Key
>       is Screen2 -> Screen2Key(route.param1, route.param2)
>     }
>   }
> }
> ```
> 
> And finally a tiny abstraction which we call `Router` which works only with `AppRoute`s, contains methods to push/pop/etc and translates that to Conductor transactions.
> 
> All this allows us to use routing in presenters/coordinators without having them to know anything about conductor or whatever view routing library is used.

@dimsuz thank you very much for your help

**Comment by tonycheng93** [comment]
@dimsuz thank you very much for your help.It would be better if you could provide a small example.

**Comment by dimsuz** [comment]
Maybe I'll do it one day, until you've asked this question here I was not very sure that it would be useful to anyone :)
