### ISSUE TITLE
View retention help

### ISSUE THREAD

**Issue by dbof10** [bluelinelabs/Conductor#487]
I have a GLView. when I push a new `Controller` but I want to keep it and it has to respect to Activity Lifecycle. There're two approach

1. Use `RETAIN_DETACH`
2. Override `removesFromViewOnPush`

I'm not quite sure which one is recommended?

**Comment by IVIanuu** [comment]
removesFromViewOnPush keeps your view attached behind the top view.

 RETAIN_DETACH detaches from the container but will reuse it when the above controller gets popped.

You could use RETAIN_DETACH for heavy views like a map view. And removesFromViewOnPush for dialog controllers and such.
