### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by svenjacobs** [bluelinelabs/Conductor#490]
Please migrate Conductor to the new [AndroidX](https://developer.android.com/jetpack/androidx/) support libraries which are stable as of 21st September.

Thank you!

**Comment by PaulWoitaschek** [comment]
Working on this!

**Comment by PaulWoitaschek** [comment]
Please review #492

**Comment by PaulWoitaschek** [comment]
Sorry but: Are you having severe issues with Github right now too? My last comment and my PR seem to have vanished.

**Comment by ShaishavGandhi** [comment]
Yup, GitHub is super wonky for me right now.

**Comment by svenjacobs** [comment]
Hi Paul,

yes, both the comment and the PR are gone :(

Paul Woitaschek <notifications@github.com> schrieb am Mo., 22. Okt. 2018,
15:19:
