### ISSUE TITLE
Any suggested way to prevent multiple push?

### ISSUE THREAD

**Issue by dariopellegrini** [bluelinelabs/Conductor#491]
Hello.
I have a problem when I call router.pushController with HorizontalChangeHandler.
With horizontal change handler I have an animation. During that animation, users can tap fast on the button which called router.pushController and invoke multiple push instead of one.

Is there any suggested way to deal with that? Something like pushIfNotPushing?
I tried with this:
```
var isNavigating = false
button.onClick {
       router.addChangeListener(object: ControllerChangeHandler.ControllerChangeListener {

                override fun onChangeStarted(to: Controller?, from: Controller?, isPush: Boolean, container: ViewGroup, handler: ControllerChangeHandler) {
                    isNavigating = true
                }

                override fun onChangeCompleted(to: Controller?, from: Controller?, isPush: Boolean, container: ViewGroup, handler: ControllerChangeHandler) {
                    isNavigating = false
                }
            })
  if (!isNavigating) {
                this.pushController( RouterTransaction.with(controller)
                    .pushChangeHandler(VerticalChangeHandler())
                    .popChangeHandler(VerticalChangeHandler())
  }
}
```

And to worked, but with this I need to add a variable in each controller.

**Comment by DrewCarlson** [comment]
Are you using [ChangeHandlerFrameLayout](https://github.com/bluelinelabs/Conductor/blob/5f683281317db368ed00cd01de50fabf8fa6d65d/conductor/src/main/java/com/bluelinelabs/conductor/ChangeHandlerFrameLayout.java#L15)?

**Comment by dariopellegrini** [comment]
@DrewCarlson No I'm not. Should I?

**Comment by dariopellegrini** [comment]
Yes I should. That wasn't a proper issue, only an "advice request". Closing ticket. Solved using ChangeHandlerFrameLayout as router container.
