### ISSUE TITLE
After some use getView returns null

### ISSUE THREAD

**Issue by sedestrian** [bluelinelabs/Conductor#496]
Hi,
I'm having a problem, i have some code that normally functions correctly, after some application usage some callbacks that require the getView method stop working because getView starts returning null, there have been no configuration changes or view recreation, i never left the controller so it doesn't look like it should lose the view, but it does, in those classes i have some code that i can't post here and the code would involve too many classes too, so i can't really give you the example code, but i'd really appreciate if you could tell me in which case the controller could lose the view without being recreated

**Comment by sedestrian** [comment]
Nevermind, i have found the solution, basically being my app a launcher when i pressed back the router tried to handle the backpress, but since it is a launcher it couldn't close so the view rendered remained there, but the router lost the controller

**Comment by EricKuck** [comment]
Cool, glad you got it sorted out. Thanks for the update.
