### ISSUE TITLE
Have no idea how handle recyclerview position with Conductor pattern.

### ISSUE THREAD

**Issue by ValeriusGC** [bluelinelabs/Conductor#501]
When screen has been rotated onSaveViewState/onRestoreViewState have been invoked, and theoreticall i can store position.
But when application go to background and then restored nothing of above are invoked.
Maybe a couple string of working code, aren't?

**Comment by EricKuck** [comment]
`onRestoreViewState` is only called when the view is recreated. Otherwise it continues to have the same state it had when it went to the background. What's the issue you're seeing?

**Comment by ValeriusGC** [comment]
There were mistake in my approach, thanks...
