### ISSUE TITLE
How to reuse controllers in pushController

### ISSUE THREAD

**Issue by stonelai75** [bluelinelabs/Conductor#505]
Suppose I have A controller and B controller. A controller can jump to B controller , vice visa, by using Router.pushController. But each time a new controller of A or B is created. As you can see there will be many duplicates of A class and B class if I keep on pushing.

My question is if there is a way I can search and find the old A or B class in the router.getBackstack and push and display the old controller.

**Comment by EricKuck** [comment]
You could use `setBackstack` to do this for you. Just find the controller you want, rearrange the backstack, and re-set it.
