### ISSUE TITLE
[Question] How to avoid restore bundle info when the app is killed

### ISSUE THREAD

**Issue by nksaroj** [bluelinelabs/Conductor#508]
I have noticed the controller data is being restored even if app is killed/process is dead. But magically it  
restored from savedInstanceState. Can I choose not to retain the data when app is killed?

**Comment by IVIanuu** [comment]
Just pass null as savedInstanceState in Conductor.attachRouter

**Comment by nksaroj** [comment]
Thanks @IVIanuu. But how to know if app is being returned from killed state or being restored from rotation changes?

**Comment by IVIanuu** [comment]
All routers and controllers do survive config changes

**Comment by nksaroj** [comment]
@IVIanuu . Thanks

**Comment by dimsuz** [comment]
Note that there's also a case where you might not want to restore backstack on _activity_ restart (i.e. the app process lives, but activity restarts). For example this could happen on a language change or other config change. 

In this case Conductor will forcibly restore backstack from private static variable when you'll attach router to your root view.

I didn't find a good way to prevent this yet, but I'm thinking that manually resetting backstack right after router attach might work, didn't try though (yet). Although this hack won't prevent constructors of controllers being called.

There are some apps where I'd like to **always** restart with clean back stack: either on process kill or on config change... I wish there was a more clean way for this too.
