### ISSUE TITLE
getTransactionIndexer() Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by chichkanov** [bluelinelabs/Conductor#515]
Hi. I've got several crashes in my production app on the latest conductor version (3.0.0-rc1). I've got no idea why this happening and how to reproduce it.  Can anyone help me to fix this problem?

Crash log:
`com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer (SourceFile:249)
com.bluelinelabs.conductor.Router.performControllerChange (SourceFile:777)
com.bluelinelabs.conductor.Router.performControllerChange (SourceFile:768)
com.bluelinelabs.conductor.Router.pushController (SourceFile:185)
com.chichkanov.hseapp.ext.ControllerExtKt.startScreen (SourceFile:25)
com.chichkanov.hseapp.ext.ControllerExtKt.startScreen$default (SourceFile:16)
com.chichkanov.hseapp.timetable.TimetableScreen$initRecycler$1.invoke (SourceFile:1137)
com.chichkanov.hseapp.timetable.adapter.LessonAdapterDelegate$onBindViewHolder$1.invoke (SourceFile:1044)
com.chichkanov.hseapp.ext.SafeClickHandler.handleClick (SourceFile:41)
com.chichkanov.hseapp.ext.DebounceViewClickListener.onClick (SourceFile:50)
android.view.View.performClick (View.java:6935)`

Device: Galaxy J7(2016)

**Comment by mradzinski** [comment]
Hard to figure out without at least an error message @chichkanov ... It looks like you're trying to push a Controller, but more information is required to know the reason why pushing a Controller crashes your app.

`ControllerHostedRouter` didn't undergo any changes on 3.0.0-rc1 other than imports, so it should be reproducible using a previous version of Conductor. If this began to happen just now then most probably there's a bug in your side other than Conductor's one.

**Comment by chichkanov** [comment]
@mradzinski here is an error message "Unable to retrieve TransactionIndexer from null host controller". It sounds like user trying to push a controller, but previous controller already closed. Testers from my team reproduced this crash when rapidly clicked on start new screen and back btn.

**Comment by sdelaysam** [comment]
@chichkanov  I've seen the same crash.
In my case child router was using view group without `id` and `Controller.restoreChildControllerHosts()` failed to restore host of this router.

**Comment by PaulWoitaschek** [comment]
Did you try rc4?

**Comment by sdelaysam** [comment]
@PaulWoitaschek yes.
but again, my crash was caused by misconfiguration on my side - view had no `id`.
the best framework can do in this case is to crash earlier on attempt to use such view as child router container.

**Comment by PaulWoitaschek** [comment]
I'll look into this.

**Comment by PaulWoitaschek** [comment]
I can't reproduce this. Can you share a minimal reproducible sample where this happens? @sdelaysam

**Comment by sdelaysam** [comment]
@PaulWoitaschek my setup looked like
```
val controller1 = Controller()
val controller2 = Controller()
val controller3 = Controller()
val controller4 = Controller()

router.setRoot(controller1)
controller1.getChildRouter(view1).setRoot(controller2)
controller2.getChildRouter(view2).setRoot(controller3)
controller1.getChildRouter(view1).pushController(controller4)
router.handleBack()
```
where `view2` had no `id`

**Comment by PaulWoitaschek** [comment]
This doesnt reproduce for me:

```kotlin
val VIEW_ONE_ID = ViewCompat.generateViewId()

class TestActivity : Activity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val controller1 = MyController()
    val controller2 = MyController()
    val controller3 = MyController()
    val controller4 = MyController()

    val container = findViewById<ViewGroup>(android.R.id.content)

    val view1 = FrameLayout(this).apply {
      id = VIEW_ONE_ID
      container.addView(this)
    }

    val view2 = FrameLayout(this).apply {
      container.addView(this)
    }

    val router = attachRouter(container, savedInstanceState)
    router.setRoot(controller1.asTransaction())
    controller1.getChildRouter(view1).setRoot(controller2.asTransaction())
    controller2.getChildRouter(view2).setRoot(controller3.asTransaction())
    controller1.getChildRouter(view1).pushController(controller4.asTransaction())
    router.handleBack()

  }
}

class MyController : Controller() {
  override fun onCreateView(
    inflater: LayoutInflater,
    container: ViewGroup,
    savedViewState: Bundle?
  ): View {
    return View(activity!!)
  }
}
```

**Comment by sdelaysam** [comment]
@PaulWoitaschek sorry I missed one detail: backstacks are nested.
Here is complete sample to reproduce.

```
class TestActivity : Activity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val controller1 = MyController()
        val controller2 = MyController()
        val controller3 = MyController()
        val controller4 = MyController()

        // make root router
        val container = findViewById<ViewGroup>(android.R.id.content)
        val router = attachRouter(container, savedInstanceState)
        router.setRoot(controller1.asTransaction())

        // make child router
        val childRouter = controller1.getChildRouter(controller1.view as ViewGroup)
        childRouter.setRoot(controller2.asTransaction().tag("controller2"))

        // make nested child router
        val nestedChildRouter = controller2.getChildRouter(controller2.view as ViewGroup)
        nestedChildRouter.setRoot(controller3.asTransaction().tag("controller3"))

        // detach nested child router
        childRouter.pushController(controller4.asTransaction())

        container.post {
            // reattach nested child router
            // crash on attempt to find the host for controller3
            router.handleBack()
        }
    }
}

class MyController : Controller() {
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup, savedViewState: Bundle?): View {
        return FrameLayout(container.context)
    }
}

```

**Comment by PaulWoitaschek** [comment]
Thanks for reporting. This will fail early now.

**Comment by TikTak123** [comment]
@chichkanov I have same error. But I can't reproduce it. Did you fix this error?
https://github.com/bluelinelabs/Conductor/issues/599
