### ISSUE TITLE
onConfigurationChanged can't call in Controller

### ISSUE THREAD

**Issue by MattC-33** [bluelinelabs/Conductor#522]
Hi,

I would like to know if you have an idea to call the onConfigurationChanged's method in Controller to update a view with a RecyclerView.
Thanks for our help!

N.B : This framework is amazing !

**Comment by manueldidonna** [comment]
If the controller doesn't receive that callback, you could handle it in the same way as the library handles the back button (the event is emitted from the activity to each controller in the stack that implements a particular interface)


``` kotlin
interface OnConfigurationListener {
       fun onConfigurationChange(orientation: Int)
}
```

**Comment by MattC-33** [comment]
Thanks for our help, it works with his method !
