### ISSUE TITLE
How to bring an Controller which is in the bottom of backstack to the top?

### ISSUE THREAD

**Issue by HauLuu** [bluelinelabs/Conductor#523]
Let say I have a back stack which contains:
index 0: Controller A
index 1: Controller B
index 2: Controller C

Is there any change I can bring C to the top of backstack?

**Comment by manueldidonna** [comment]
Router class manages the backstack

```java
final Backstack backstack = new BackStack();
```

Maybe you can get access to that variable to change the backstack order yourself.

**Comment by EricKuck** [comment]
Router has a setBackstack method.
