### ISSUE TITLE
Simulating process death for testing purposes

### ISSUE THREAD

**Issue by DSteve595** [bluelinelabs/Conductor#526]
I'm working on Robolectric/instrumentation tests for controllers, and I've got them working pretty well with a custom rule. Using `ActivityScenario`, I can simulate recreating the activity, and verifying that the controller is doing/showing what I expect. A step further would be to test process death; this isn't supported by Robolectric or AndroidX's testing APIs (at least as far as I'm aware), so I'd like to get as close as possible by simulating an activity being recreated _and_ having to create new instances of its controllers. I think I can get close by messing around with `LifecycleHandler`, but I think it'd be great if something like this was supported, possibly in a `-testing` artifact. I'd love to know what some good approaches for this would be.

**Comment by Zhuinden** [comment]
I don't know an automated way, but doing the steps outlined in https://stackoverflow.com/questions/49046773/singleton-object-becomes-null-after-app-is-resumed/49107399#49107399 do trigger process death scenario.

**Comment by PaulWoitaschek** [comment]
This doesn't really seem to be specific to conductor. Automating the process death testing is an issue that's generally unsolved on android.
