### ISSUE TITLE
minSdkVersion from 16 to 15

### ISSUE THREAD

**Issue by alexodus** [bluelinelabs/Conductor#53]
Please reduce the minSdkLevel to 15 (Android 4.0.X): I've an app in production with minimal sdk level to 15 and I want to use this framework. Thanks

**Comment by sockeqwe** [comment]
Not possible. Conductor internally uses APIs that require API 16

Alessandro Rossi <notifications@github.com> schrieb am Mi., 18. Mai 2016,
22:53:

**Comment by alexodus** [comment]
mmmh....I just recompiled the conductor demo  with minSdkLevel to 15 without problem/warning. Are you sure?

**Comment by EricKuck** [comment]
As mentioned in #18, `startActivityForResult` isn't available in SDK 15.
