### ISSUE TITLE
how to handle context? java.lang.RuntimeException

### ISSUE THREAD

**Issue by raquezha** [bluelinelabs/Conductor#530]
I'm passing context in controller but keeps getting runtimeexception

```
class ControllerTest() : Controller() {
  private lateinit var context: Context
  constructor(context: Context) :this() {
    this.context = context
  }

  override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View {
     // im initialize adapter here and passing the context
  }
}
```

but when I press home and open the app again
I sometimes get this error:

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{net.test.app/net.test.app.activities.AccountsActivity}: cxp: lateinit property context has not been initialized
android.app.ActivityThread.performLaunchActivity

lateinit property context has not been initialized

```

**Comment by raquezha** [comment]
also the java.lang.RuntimeException _rarely_ occurs so I'm stuck and don't know what to do next

but now that I think of it instead of passing context maybe I should pass the adapter instead of context maybe that's a better approach..  anyway It's good to know what's happening here.

**Comment by PaulWoitaschek** [comment]
It happens when conductor creates the controller after a process death by calling the primary constructor through reflection. 
Therefore everything you pass through the constructor should call the primary constructor with a Bundle so the arguments can be restored.

You should not pass the context at all as it will also leak the activity if you pass it. The Controller has a method called getActivity(). Use that if you need the context.

**Comment by raquezha** [comment]
"everything you pass through the constructor should call the primary constructor with a Bundle"

how should I do this?

**Comment by raquezha** [comment]
ohh sorry for the noob question, i get it now! thank you so much for your help

**Comment by PaulWoitaschek** [comment]
Like this: (pseudo code)

```kotlin

private const val NI_SHOPPING_ID = "ni#shoppingId

class ShoppingDetailController(bundle : Bundle) : Controller(bundle) {

  constructor(shoppingId : String) : this(Bundle().apply {
    putString(NI_SHOPPING_ID, shoppingId)  
  })

  private val shoppingId = args.getString(NI_SHOPPING_ID)
}

**Comment by raquezha** [comment]
Nice! thank you I've learned a lot today. I'll surely use that 

`this.Bundle().apply {     } ` from now on. 

Thank you again!
