### ISSUE TITLE
How to handle listener/interface on Controller to Activity?

### ISSUE THREAD

**Issue by raquezha** [bluelinelabs/Conductor#532]
I'm quite stuck... 

I want to do things in activity.. for example I click something inside the controller I want to call a listener that I pass to controller and execute it in  Activity

**Comment by EricKuck** [comment]
This would work the same way it would with Fragments. Something like `((MyListener) getActivity()).doThing()` would be all you needed.

**Comment by raquezha** [comment]
OHMY it work! I'm learning so much. thank you for your reply.

**Comment by raquezha** [comment]
@EricKuck just a follow up question.

will it still work even if the controller is recreated because of process death?

**Comment by EricKuck** [comment]
Yep, it'll work as long as you have access to the activity. Note that at certain points in the lifecycle you may not have that access, so it's good to do a null check first.

**Comment by raquezha** [comment]
I'll love using conductor. I'll continue my study on this. Thanks again!
