### ISSUE TITLE
[Question] Conductor + Coroutines + Clean Architecture

### ISSUE THREAD

**Issue by raquezha** [bluelinelabs/Conductor#534]
Is this possible, can someone help me to achieve this? 

I'm starting to learning clean architecture and I'm quite familiar now with Conductor and I little of Coroutines and my mind is exploding because It's all new to me but I want to learn and determine to achieve this goal. there's plenty of tutorial online but the closest I get is jshvart's Conductor MVP but he uses RxJava on that project.

**Comment by lcszc** [comment]
Hi, @raquezha

Yes, it is possible. Conductor is not tied to RxJava nor Coroutines, you will use it on your view-layer. The data-infrastructure layer doesn't care of what are you using, same for Conductor.

You can think on Conductor as a awesome Fragment, but I don't know if it's the best definition for it.
