### ISSUE TITLE
onCreateOptionMenu not called

### ISSUE THREAD

**Issue by kevelbreh** [bluelinelabs/Conductor#54]
When pushing a new controller, onCreateOptionsMenu is not being called on the pushed controller.

If i were to use the tested controller as the root controller on an activity, onCreateOptionsMenu is called as expected.

**Comment by leonardo2204** [comment]
Are you calling `setHasOptionsMenu()` in your new controller ?

**Comment by kevelbreh** [comment]
This is correct. I call this in the constructor.

I have a button click on my root controller which pushes the problematic controller.  The problematic controller has `setOptionsMenu `called. The overridden methods `onCreateOptionsMenu`, `onPrepareOptionsMenu `and `onOptionsItemSelected `don't seem to get invoked.  

The controller (extending `RxController`) does pop my view into place and respond to normal lifecycle events.

**Comment by leonardo2204** [comment]
Which version of the lib are you using ? Post some code, please.

**Comment by kevelbreh** [comment]
Using version's 1.1.6

[Here is a gist with a basic activity and 2 controllers.](https://gist.github.com/kevelbreh/adbd946bda2f710d86c46dda889f124f) None of the menu methods are getting invoked. Also when pressing back the default back button, the top controller gets popped but it's view still lingers (When you have the activity + home + sub controller).  Pressing back again then finishes the activity as expected.

**Comment by EricKuck** [comment]
It looks like the reason nothing was working for you was because you were inflating your views incorrectly. Like Fragments, you should inflate your view with `inflater.inflate(R.layout.my_layout, container, false)` rather than just `inflater.inflate(R.layout.my_layout, container)`. When you don't use false, the view that gets returned is the parent view.
