### ISSUE TITLE
[Question] How to set the Backstack of a ChildRouter that doesn't exist yet

### ISSUE THREAD

**Issue by wilwade** [bluelinelabs/Conductor#540]
So working on a sort of quick/deep navigation, so trying to use `setBackstack` to make this happen. The complication is that we are nested inside a ChildRouter halfway down.

Top Level Controllers: A, B, C
Child Controllers: C1, C2

Desire:
C.childRouter.setBackstack(C1, C2)
mainRouter.setBackStack(B, C)
Triggers navigation to C2 with backstack of C2 -> C1 -> C -> B

Of course the issue is that the childRouter on `C` does not exist yet. It doesn't get created until the view is attached to `C`.

Additional notes:
I would rather not pass my desired backstack via `C`'s bundle args as I want a single transition to `C2`.

(Conductor v2.1.5)

**Comment by EricKuck** [comment]
Unfortunately I'm not sure there is really a way to do this without passing the desired backstack into `C`. You could still get this app performed in a single transition though, as long as controllers in the child router don't use any types of animations/transitions when they're attached.
