### ISSUE TITLE
Idiomatic access to context in Controller.onCreateView()

### ISSUE THREAD

**Issue by ispbox** [bluelinelabs/Conductor#556]
I'm wondering what way to choose:
1. Use inflater.context (non-nullable, used in some samples)
2. Use container.context (non-nullable, also used in samples)
3. Use this.applicationContext (nullable, recommended in this issue: https://github.com/bluelinelabs/Conductor/issues/530#issuecomment-480525297)

From my point of view it's better to use second option - it is obvious that if we inflate into some container, it should be already ready for inflation and should have context.
What do you think?

**Comment by EricKuck** [comment]
It depends on what you want the context for. Both `inflater` and `container` will give you a themed context that shouldn't be leaked. `applicationContext` is the way to go if you don't need a theme. Otherwise either of the other two are fine.

**Comment by ispbox** [comment]
Thanks for the answer!
My purpose is to use context for Ui generation via Splitties (or, alternatively, via Anko). So first two serve for my needs, as both libs need theme.
