### ISSUE TITLE
Clickable LinearLayout and Backstack

### ISSUE THREAD

**Issue by ispbox** [bluelinelabs/Conductor#558]
It is actually **not an issue of Conductor**, but hopefully it could help someone. 

I have a very simple case: two Controllers, first one has buttons on it, and the second one is empty - it contains LinearLayout. The problem happens when we switch from first controller to second (first goes to backstack), and then tap on LinearLayout.
Actually this could cause OnClick listeners on Buttons from the first Controller! So tap goes through Controllers in backstack!

This is probably by design in Android, but is not really expected behavior and can easily lead to bugs due to user interaction with hidden Controller.

The solution is simple: just make LinearLayout clickable by any way, i.e. by adding android:clickable="true" attribute.

**Comment by PaulWoitaschek** [comment]
How do you push the controller? Normally controllers that are put in the backstack get detached.

**Comment by ispbox** [comment]
Here is my sample code for ControllerA:

```
override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View {
    // Create UI programmatically for ControllerA
    return viewA;
}

private fun navigateToControllerB() {
    val pushHandler = FadeChangeHandler(false)
    val popHandler = FadeChangeHandler()

    router.pushController(RouterTransaction.with(ControllerB())
            .pushChangeHandler(pushHandler)
            .popChangeHandler(popHandler))
}
```

**Comment by ispbox** [comment]
I tried to take a look on what is going on behind ControllerB - just made null background for LinearLayout. And, as expected, I see whole view of ControllerA. So looks like Controllers are not detached.

**Comment by PaulWoitaschek** [comment]
That is because you explicitly opted into not detaching the controller.
`FadeChangeHandler(false)`

Is this by accident?

**Comment by ispbox** [comment]
PaulWoitaschek, thanks a lot for clarification! That's my fault definitely - I just took that from samples, and decided that it is correct to have bi-directional handlers with true/false parameter.

Without (false) everything works as expected!
