### ISSUE TITLE
handleBack() removes root controller transaction from stack

### ISSUE THREAD

**Issue by fonix232** [bluelinelabs/Conductor#566]
In my current solution, I have a main activity I do not want the user to simply close, thus a dialog is displayed. However when the main router is set to not pop last controller (`popsLastView` is false), it will still remove the transaction from the backstack, while keeping the view in the viewtree.

In this solution I have a HomeController, an ExitDialogController, and a DetailController.  In the activity, I handle the back button the following way:

```
override fun onBackPressed() {
        if(!navigation.back()) {
            navigation.showExitDialog()
        }
    }
```

`navigation` is a custom object handling navigation events, which are abstracted from the ViewModel. It's `back()` implementation is the following:

```
back(): Boolean {
        return when {
            isNoInterrupt.value == true || isLoading.value == true -> true
            else -> router.handleBack()
        }
    }
```

`isNoInterrupt` and `isLoading` are two LiveData fields that are not important in this case.

`router.handleBack()` gets called successfully when I'm on the HomeController, and the dialog is displayed. However at that very moment the only transaction in the backstack becomes the ExitDialogController's transaction, losing the HomeController's initial transaction.

Even though the transaction is removed from the backstack, the controller stays in the ViewTree, and all functionality works - up until a new item is pushed to the stack, which will not allow back navigation, and will crash the app eventually.

It is my understanding that is `popsLastView` is set to true, `router.handleBack()` should return false when on the root controller, without popping its transaction. Is that not correct?

**Comment by EricKuck** [comment]
`setPopsLastView` does what the name implies - it sets whether or not the last _view_ will be popped, not whether or not the last transaction will be popped. This is simply to ensure that `Activity`s don't look goofy while they're `finish`ing. You can get what you're looking for by checking the `backstackSize` of the router in `onBackPressed`.
