### ISSUE TITLE
Transition is not smooth

### ISSUE THREAD

**Issue by OlegShelyakin** [bluelinelabs/Conductor#574]
Hi! 

I have encountered a problem related to the change handler when you try to update view between onAttach and changeEnded. In this case, the transition animation is not smooth.

For example. There are controllers: A and B. Controller A goes to B using HorizontalChangeHandler.  I subscribe to a database on non-UI thread in onAttach() method of controller B  and update view once the data came. Accordingly, the data can come before the transition animation finishes or onChangeEnded method calls. And because of that, the view can be touched during animation and this leads to the problem with smoothness.

```
class B : Controller() {

   fun onAttach() {
      database
           .subscribeOn(ui()) 
           .observeOn(mainThread())
           .subscribe({ updateUi(it) }, { showError(it) })
   } 

   // this method can be called befor onChangeEnded will be called
   fun updateUi(list: List<Data>) {
      adapter.submitList(list)
   }
   ...
}

```
Does Conductor have some option to delay animation until target controller says: "I'm ready, animate me"?

**Comment by sgrekov** [comment]
LifecycleListener has "onChangeEnd" callback, I think this what you are looking for.

**Comment by OlegShelyakin** [comment]
> LifecycleListener has "onChangeEnd" callback, I think this what you are looking for.

I need to preload controller data before the animation starts. If I subscribe to the database in onChangeEnd, then a user will see empty view during the animation. This is not what I want. 

I am looking for something like postponeEnterTransition for activity

**Comment by sgrekov** [comment]
Ah, sorry, I thought you want to postpone view update after animation ends.

**Comment by manueldidonna** [comment]
I used to postpone animations with SharedElementTransitionChangeHandler setting the transition name within a callback in the entering controller. Maybe you can adopt a similar mechanism

**Comment by PaulWoitaschek** [comment]
Yes, that should solve the issue.
