### ISSUE TITLE
ViewPager2: Implement ControllerStateAdapter

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#575]
Now that ViewPager2 is final, we need a `ControllerStateAdapter`
(en pair with `androidx.viewpager2.adapter.FragmentStateAdapter`)

**Comment by MkhytarMkhoian** [comment]
I plan to do add support ViewPager2 for Conductor in my project and will share

**Comment by petersnoopy** [comment]
Any updates?

**Comment by Kotlinovsky** [comment]
Updates?

**Comment by EricKuck** [comment]
Work has started on this, but it’s on the backburner until we can get 3.0 shipped. PRs are welcome.

**Comment by EricKuck** [comment]
An alpha version of a ViewPager2 adapter is available in this PR: https://github.com/bluelinelabs/Conductor/pull/594. It's not currently deployed anywhere, but please review if interested.
