### ISSUE TITLE
setRetainInstsance() is been deprecated

### ISSUE THREAD

**Issue by helloseyedjafari** [bluelinelabs/Conductor#577]
Since Android team has decided to deprecate `setRetainInstance()` in fragments and force us to rely on `ViewModel`, Is there any other way we can use to avoid `Controller` death when config changes happen?

[Related android commit message](https://android-review.googlesource.com/c/platform/frameworks/support/+/1159084)

**Comment by MkhytarMkhoian** [comment]
`setRetainInstance()`  still working

**Comment by PaulWoitaschek** [comment]
Conductor is using framework fragments, not androidx fragments so it's unaffected by that change.

**Comment by soniccat** [comment]
@PaulWoitaschek hm, that seems even worse as framework fragments are deprecated about a year ago (API 28)...

**Comment by PaulWoitaschek** [comment]
How is that an issue? The `LifecycleHandler` is only delegating basic lifecycle events and I'm pretty sure it won't get removed in a future android version.

**Comment by soniccat** [comment]
Yes, I agree that it isn't a critical issue as everything will work for years I suppose. But if Google deprecates something we use, in my opinion, it's a good idea to start thinking of how we can replace this logic.

My point was that using a deprecated framework Fragment might be error prone as it might not contain fixes which androidx Fragment has. Also not using the same Fragment code might lead to problems which happens only on a particular API version.
