### ISSUE TITLE
Java8 + Default Methods

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#578]
I'd like to bump this library to java 8 and make use of default implementations.
For example a candidate where I most of the time only need one method to be overwritten is `ControllerChangeListener`.

@EricKuck Would you accept such a PR?

Or should we directly migrate to kotlin?

**Comment by EricKuck** [comment]
Absolutely! Enough of the androidx libs are moving to Java 8, so I think it's fine to bump the requirement here as well.

**Comment by PaulWoitaschek** [comment]
@EricKuck Could you check-in the .idea/codeStyles folder? Its really hard working with this without accidentially reformatting everything.

**Comment by EricKuck** [comment]
I think reformatting to a more standard format is totally fine. Any inconsistencies with standard code formatting is likely accidental.

FWIW I'm also open to migrating to Kotlin. Any thoughts on what would be the best approach going forward?

**Comment by abyrnes** [comment]
@EricKuck For migrating to Kotlin, [japicmp](https://github.com/melix/japicmp-gradle-plugin) seems to be a good way to go for maintaining binary compatibility when migrating. I know they used it on OkHttp when migrating to kotlin

**Comment by PaulWoitaschek** [comment]
@abyrnes I don't think this is necessary. This libary is usually no transitive dependency used by other libaries. So we can do breaking changes between major version bumps.

**Comment by PaulWoitaschek** [comment]
@EricKuck What do you think about incrementally migrating to kotlin? I.e. picking one class after another? Rewriting everything at once is a huge task.

**Comment by EricKuck** [comment]
Yes, I totally agree. We should target Java 8 so that default interface methods still work for Java users and also start introducing Kotlin in 3.0.0.

**Comment by dimsuz** [comment]
Can this be coordinated somehow? I may have some extra time to spare after April 4th, so I could help, but it's important not to mix up with each other.

**Comment by PaulWoitaschek** [comment]
Yes, absolutely. Let's open a ticket when someone starts working on something so we don't overlap each other.
I made a first tackle on the issue, please review :)

**Comment by rinekri** [comment]
Maybe someone can introduce a new label to track the migrating progress? And it will be cool to see a roadmap. Maybe I'll help too.
