### ISSUE TITLE
How do you change the language in your application?

### ISSUE THREAD

**Issue by TikTak123** [bluelinelabs/Conductor#580]
I use the Lingver library to change the language in my application, but sometimes the text in my application changes to the default language text and this happens in some places in the application. When after opening WebView my application always in some places again changes to text in the default language. In addition, I tried using Plugin-Locale-Kotlin to change the language, but the result is the same.

My previous question on this topic:
https://github.com/bluelinelabs/Conductor/issues/579

**Comment by PaulWoitaschek** [comment]
See my comment in #579

**Comment by PaulWoitaschek** [comment]
See my comment in #579
