### ISSUE TITLE
Click on Menu Item don't work with controller and Navigationview

### ISSUE THREAD

**Issue by MattC-33** [bluelinelabs/Conductor#581]
Hi everyone,

I have a problem with an "onClick" event, with NavigationView, Controller and Menu item.
I explain: I have a controller, which is a child of my "root" controller. 
In this, I have a menu item, which can permit me to take a picture. 
Also, I use a NavigationView, so I override it to return at my "root" controller when I click on it (With setDrawerIndicatorEnabled(false), it shows me a "back" button).
Problem: When I click on my menu item, which is the "camera" item, it has the same behavior when I click on my NavigationView (Which is a "back" button), it returns on my "root" controller.
In my opinion, the problem comes to the "setDrawerIndicatorEnabled" function, but I don't find the correct answer.

Any idea?

Thanks for our help !

**Comment by EricKuck** [comment]
I'm sorry for the issue, but this seems like more of a problem with NavigationView and/or Toolbar than Conductor. If you feel strongly that this is a Conductor issue, please feel free to re-open.
