### ISSUE TITLE
Remove several components

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#586]
I'd like to make some breaking changes for the 3.0 train:

## RestoreViewOnCreateController
Remove the RestoreViewOnCreateController and merge the functionallity
into Controller

## Remove the framework TransitionChangeHandler
I think the androidx transitions are the way to go because they fix issues in older android versions and backport newer apis. So I'd like to completely remove the framework version

## Remove RxLifecycle and Autodispose
To reduce the maintenance overhead I'd like to remove as many of these third party supports as reasonable. I think these are very specific use cases and they are kind of trivial anyways so the classes could either copy-pasted if people still need them or someone could create a library that's not part of this project and we'll link it in the readme

## Remove supportActionBar, optionsMenu etc.
I think that the whole supportActionBar, optionsMenuApi etc. is legacy, not needed at all, complicates the library and should be removed completely. At yazio, we use toolbars as regular views which makes the whole handling way simpler. For example:
```kotlin
    binding.toolbar.inflateMenu(menuRes)
    binding.toolbar.setOnMenuItemClickListener {
      when (it.itemId) {
        R.id.end -> {
          showEndPlanDialog(context) {
            viewModel.endPlan()
          }
          true
        }
        R.id.edit -> {
          viewModel.toMyFoodPlanSettings()
          true
        }
        R.id.groceryList -> {
          viewModel.toGroceryList()
          true
        }
        else -> false
      }
    }
```

**Comment by PaulWoitaschek** [comment]
@MkhytarMkhoian 
I see you work on this in a fork. What is the reason for that? Can we bundle our work into the main library?

**Comment by MkhytarMkhoian** [comment]
@PaulWoitaschek 
This fork is the version of the Conductor that our team uses internally 3 years and a week ago we decided to open-source our version. The library has different from the main repo. Besides the main repo not developing for a long time. The second reason is that we need the ability to change code to fit our requirements.

**Comment by PaulWoitaschek** [comment]
Interesting. What are the key differences?

**Comment by PaulWoitaschek** [comment]
Okay, we'll keep the menuItem stuff, and the autodispose and rxlifecycle versions.
The rest is implemented now.

**Comment by MkhytarMkhoian** [comment]
We have implemented ControllerFactory, support for tab menu (but without animation for now)
and working on remove Fragment from dependencies

**Comment by dniHze** [comment]
Well hi! I'm the second maintainer of the fork. So yeah, we are onto deprecating of useless modules too.

So the key changes is the:
* `ControllerFactory`
* `ControllerArgs` - `Parcelable` interface that allows us to store the controller args statically typed. It's used in couple with ControllerFactory to get rid of unnecessary bundling and unbundling into the `Bundle args`.
* The whole `conductor-codegen` thing - annotations and processor, inspired by `AssistedInject` to generate Dagger2 constructor factories for controllers. 

The docs aren't ready for now, but we are actively working on it to unbundle the whole sources from our app repo and to finish it for the release stage.
