### ISSUE TITLE
Add onActivityLowMemory

### ISSUE THREAD

**Issue by lenguyenthanh** [bluelinelabs/Conductor#59]
Some time we need to listen to `onLowMemory` callback in our Controller.
For example when I'm working with [Mapbox](https://www.mapbox.com), it requires to call `onLowMemory`:
````
 @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }
````

If you ok with this feature, I'm happy to do a PR.

**Comment by adi1133** [comment]
You have access to this functionality in the Application class

**Comment by leonardo2204** [comment]
But he needs this callback inside some Controller. 
I think another callback wouldn't hurt.

**Comment by JakeWharton** [comment]
You can propagate information like this using LocalBroadcastManager, an
event bus, RxJava, or manual callbacks that you register. I don't think
this library needs to be responsible for everything when it arguably has
too many callbacks already and other mechanisms exist for passing along
data to controllers.

**Comment by adi1133** [comment]
@leonardo2204 Extra callbacks hurt, I'd like even some removed if possible.

**Comment by lenguyenthanh** [comment]
IMHO, it's more convenient for us if we have this callback (do not need to do some extra steps like event -bus or RxJava). It wouldn't hurt much too, because people can decide to use it or not. Btw it's just my opinion, it's not really important thought.

**Comment by EricKuck** [comment]
This should be easy enough to add to the application layer to not be required at the library layer.
