### ISSUE TITLE
Keep platform Transitions for TransitionChangeHandler

### ISSUE THREAD

**Issue by chris-horner** [bluelinelabs/Conductor#590]
I'd really like to hang on to the platform transitions. Two reasons for this:
1. Anecdotally, I've run into a few issues trying to use androidx transitions and them not playing nicely with overlays.
2. The new [material motion](https://material.io/develop/android/theming/motion/) transitions are based on the platform transitions, not the androidx versions.

This second point is probably the major one. (I can't currently find any example issues I mention in the first point).

My understanding is that currently, androidx transitions _don't_ bring anything new to the table in terms of features or bug fixes. I might be wrong, but they seem to _only_ backport transitions to pre API 21 devices.

With this in mind, could we reinstate `TransitionChangeHandler`? Or at least add them as a separate module alongside the androidx variant?

**Comment by DSteve595** [comment]
>androidx transitions don't bring anything new to the table in terms of features or bug fixes

Similarly to Fragments, these backported transitions have fixes, including workarounds for platform bugs.

`TransitionManager.endTransitions` is 23+, but backported to 21 via AndroidX transitions.

>The new material motion transitions are based on the platform transitions, not the androidx versions.

This is likely because those need to support Activity transitions, which require the framework ones.

If you're repro'ing a bug with AndroidX transitions and not framework transitions, I'd definitely file that.

@EricKuck What do you think?

**Comment by chris-horner** [comment]
> This is likely because those need to support Activity transitions, which require the framework ones.

Sure, but that doesn't obviate the need to use native transitions if you want to utilise the material motion transitions. As it stands, consumers of Conductor will need to implement custom `ChangeHandlers` instead of using what was previously provided.

I understand the desire to push developers in the direction of using the version that contains more bugfixes / features, but we're explicitly losing functionality by making this change. I feel it'd be better to continue the framework / compat split here.

**Comment by DSteve595** [comment]
Makes sense.

I'd personally be in favor of another module containing the framework transitions. It'd be annoying to maintain (since the two are effectively copy-pastes but not code-compatible), but hopefully not too bad.

**Comment by PaulWoitaschek** [comment]
I'll open a PR later bringing them back :-/

**Comment by EricKuck** [comment]
Yikes, I didn’t realize the material motion stuff used platform transitions. Adding them back as a module sounds like the right move to me. Thanks for the catch @chris-horner!

**Comment by dimsuz** [comment]
I really don't like this inconsistency of Google. Most of the time (for other libraries) they say: prefer androidx variants. But this one is suddenly an exception.

Thanks for this issue, I wasn't aware of this too...

**Comment by PaulWoitaschek** [comment]
> I'll open a PR later bringing them back :-/

Sorry I'm kind of busy right now, if someone wants to do this feel free to open a PR :)

**Comment by chris-horner** [comment]
I've got time. I'll get one up later today 🙂
