### ISSUE TITLE
router.setBackstack pushes only first controller 

### ISSUE THREAD

**Issue by TikTak123** [bluelinelabs/Conductor#604]
Before update from com.bluelinelabs:conductor:3.0.0-rc2 everything worked well

**Conductor version:**
implementation 'com.bluelinelabs:conductor:3.0.1-SNAPSHOT'

**Sample code:**
```
router.setBackstack(
            arrayListOf(
                RouterTransaction.with(MainMenuController(Constants.MAIN_TAB)),
                RouterTransaction.with(MyMelodyController(ringtone))
            ),
            HorizontalChangeHandler()
        )
```

**Comment by EricKuck** [comment]
I'm not able to reproduce this issue. Setting a backstack with multiple items works fine for me. Is it possible to get a small demo together for this?

**Comment by TikTak123** [comment]
I use setBackstack in two places

In first place 
after this I see only first controller
```
router.setBackstack(
    arrayListOf(
        RouterTransaction.with(MainMenuController(Constants.MAIN_TAB)),
        RouterTransaction.with(MyMelodyController(ringtone))
    ),
    HorizontalChangeHandler()
)
```

In second place
In this situation everything is OK
```
router.setBackstack(
    arrayListOf(
        RouterTransaction.with(MainMenuController(Constants.MAIN_TAB)),
        RouterTransaction.with(QuizController())
    ),
    HorizontalChangeHandler()
)
```

I will try to write sample app

**Comment by TikTak123** [comment]
I find out why this happen. My coworker added change in code base and he did mistake and for that reason our application works strange and crashes.

**Comment by TikTak123** [comment]
Thank you
