### ISSUE TITLE
Jetpack Compose + Conductor.

### ISSUE THREAD

**Issue by xpnewmedia** [bluelinelabs/Conductor#605]
It's been a little bit since digging back into Android Development.

When I left off Conductor was new and trending, and I used it in a number of projects
with somewhat ease, I get the concept.

Now with Jetpack Compose, which i'm currently wrapping my head around...

Is there room in an Android App's Architecture to include both strategies....or 
Is it one or the other.

TY

**Comment by StephanSchuster** [comment]
I would also be very interested in the communities' opinion if/how Jetpack Compose and Conductor could play together nicely.

**Comment by PaulWoitaschek** [comment]
I implemented the basic support with instant and view state restoration in this branch: 
https://github.com/bluelinelabs/Conductor/tree/compose_support

You can find a ComposeController here:
https://github.com/bluelinelabs/Conductor/blob/compose_support/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/ComposeController.kt

The basic building block is this:
https://github.com/bluelinelabs/Conductor/blob/compose_support/conductor/src/main/java/com/bluelinelabs/conductor/internal/OwnViewTreeLifecycleAndRegistry.kt

The saved state registry depend on you using an AppCompatActivity of a recent version

**Comment by PaulWoitaschek** [comment]
Released as 3.1.0!
