### ISSUE TITLE
Integration with Facebook SDK login

### ISSUE THREAD

**Issue by shchurov** [bluelinelabs/Conductor#61]
Facebook SDK login requires us to provide a reference to an activity or fragment so it will call `startActivityForResult()` internally. It means that we need to pass `LifecycleHandler` fragment reference there in order to get the result to its `onActivityResult()` and dispatch it to controllers. However, I didn't find an easy way to get that reference. Is there any official workaround?

**Comment by sockeqwe** [comment]
Maybe duplicate: #17

**Comment by shchurov** [comment]
@sockeqwe Thanks, you're right
