### ISSUE TITLE
ViewBinding support instead of ButterKnife(Deprecated)

### ISSUE THREAD

**Issue by brcbydr** [bluelinelabs/Conductor#616]
Hi all,

I need to implement view binding with Conductor. Samples are using ButterKnife but it is deprecated because of view binding(https://developer.android.com/topic/libraries/view-binding). What is the best practice for view binding?

Thanks

**Comment by solidogen** [comment]
https://www.reddit.com/r/androiddev/comments/jetvoa/kotlinandroidextensions_plugin_will_be_deprecated/

Synthetics will also be deprecated shortly.

**Comment by EricKuck** [comment]
Conductor is meant to be agnostic of the way you want to design your app. The Butterknife implementation is not supposed to be guidelines of how to best implement your controllers (that said, I'll be replacing those soon). If you want a good example of ViewBinding with Condutor, check out @PaulWoitaschek's open source app Voice: https://github.com/PaulWoitaschek/Voice
