### ISSUE TITLE
Consider making Controller a interface

### ISSUE THREAD

**Issue by ursusursus** [bluelinelabs/Conductor#617]
So we can play nice with multi-module projects

**Comment by EricKuck** [comment]
How would making Controller an interface help with multi-module projects? I've never had a problem going multi-module with Conductor as-is.

**Comment by ursusursus** [comment]
Dependency inversion

The problem is cross-module communication, i.e when module A wants to open a controller from module B. Usual way to do this, if it is say Repository, is to have a interface FooRepository in a foo:contract module, which is then implemented in foo:impl

Others depend on the contract module, and work with FooRepository interface.

Same way would the navigation work. featureA includes featureB:contract, which exposes `interface FooController : (interface) Controller`. Now factory of this could be injected, and used

`router.pushTransaction(Transaction.with(component.fooControllerFactory().create())`

What I have to do now is to inject a (base class) Controller, which then needs to be keyed via annotation/string since its all Controllers. Actual types would be safer `interface FooController: Controller`

then impl would be something like this

`class FooControllerImpl : FooController, BaseController`

**Comment by PaulWoitaschek** [comment]
And why can't your `FooControllerFactory` just be an interface that returns a `Controller`?

**Comment by ursusursus** [comment]
It can, but using Provider<> feature of dagger would be nicer, as not to spam this factory everywhere, so then you logically create a generic factory, and that then needs to be deduplicated via keys

And it would be consistent with already standard cross module communication

**Comment by ursusursus** [comment]
basically this https://speakerdeck.com/vrallev/android-at-scale-at-square?slide=53

**Comment by dimsuz** [comment]
We have an multi-module architecture and no problems in using Controllers as is. I have simply made `Controller` and `Router` an implementation detail. Basically:

There's some module named `:routing` with the following
```kotlin
sealed class Route { Screen1,  Screen2, Screen3 }

interface Router {
  fun push(route: Route)
  fun pop()
  // etc
}

interface ControllerFactory {
  fun create(route: Route): Controller
}

internal class ConductorRouter(factory: ControllerFactory) : Router { 
  // implements an interface using conductor's router
}
```
And then there are a lot of feature modules, which depend on `:routing` module and provide their own `Controller`'s.
Apart from this they know nothing about implementation details, don't know about `Conductor` at all, they are simply using `Route` and `Router` interface to navigate.

Finally, `app` module depends (directly or transitively) on all individual feature modules and contains implementation of `ControllerFactory`:
```kotlin
internal class ControllerFactoryImpl : ControllerFactory
```

We have multiple complex apps using this structure and it works reasonably well. In fact I think I could easily swap router implementation with `FragmentManager` based one and it would work. I hope I'll never need this though.

**Comment by ursusursus** [comment]
I'm not saying it doesnt work, but interfaces would make the designs cleaner, and my life easier, and there is not reason why it should not also be a interface, other than doing the work.

I don't want to be forced into random FragmentFactory subtypes as Fragments force me, and or maybe in this time needless abstractions, or various workarounds the fact its a concrete class, and I can only extend 1 of those, we can do better

Also, those abstractions usually encode knowledge of all the screens available, leaking it to dependant modules, which is not amazing, but to each their own

**Comment by PaulWoitaschek** [comment]
> and there is not reason why it should not also be a interface, other than doing the work.

Well it makes things complicated for the user. A Controller is no interface, it's a class. So every screen would now extend from `ControllerImpl` if we moved all methods into an interface?
Or how would that look to you?

**Comment by ursusursus** [comment]
Guess its too late now

But if say square Workflow is anything to go by, they do have it as interface https://github.com/square/workflow-kotlin/blob/8a9703f0f164b83f8b048c5648ab84e7c5bf1202/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt

**Comment by dimsuz** [comment]
Well, that's totally different API design. They have at least two implementations of `Workrflow` right from the start, and the API was designed around those interfaces. What would be useful to have as multiple implementations of `Controller`? I think the fact that you are needing this might show that you're trying to abstract in a wrong way somehow.

**Comment by ursusursus** [comment]
What do you mean? The interface is there to provide ability to invert dependencies, regardless of how many implementations there are

**Comment by dimsuz** [comment]
I mean that good and extensible API design doesn't mean that every top-level class must be made into an interface.

**Comment by EricKuck** [comment]
This feels like something that could be done better on your end than in the library itself.

`interface ControllerInterface`

`class BaseController : Controller(), ControllerInterface`

Then use `ControllerInterface` as the interface you’ve been looking for.

**Comment by ursusursus** [comment]
Not really since I cannot stick `ControllerImterface`` into a router transaction

**Comment by PaulWoitaschek** [comment]
Can you provide a code example where the current class solution isn't working for you and where the interface based approach would work?

**Comment by PaulWoitaschek** [comment]
I'm closing this now. If you have additional feedback or think this should not be closed, ping me :)
