### ISSUE TITLE
Is JVM testing possible?

### ISSUE THREAD

**Issue by ursusursus** [bluelinelabs/Conductor#621]
Hi, I have a complex registration flow, 

Is it basically possible to test router state in jvm unit tests? Or do I have to use the android ones

**Comment by PaulWoitaschek** [comment]
As the router has a dependency on the android framework you can't do plain jvm tests. But it should work to use Robolectric (yet I wouldn't recommend it as it fakes real world things so a real android device / emulator will more correctly ensure that your test is correct.
