### ISSUE TITLE
Hide/show bottom navigation issue

### ISSUE THREAD

**Issue by swapnilsinha17** [bluelinelabs/Conductor#624]
I have a main activity in my app, which has a bottom navigation.I wants to show bottom nav on main controller not on the child controller.How i gonna do it.
Please Help!

**Comment by EricKuck** [comment]
This isn't really an issue with the library. The first thing that comes to mind would be to have the bottom nav hosted in the main controller, then push child controllers over the top of that. There are lots of ways you could do this though.
