### ISSUE TITLE
[Question] MDC Motion Transitions

### ISSUE THREAD

**Issue by mradzinski** [bluelinelabs/Conductor#637]
Hi there. Is it currently possible to use MDC Motion transitions such as `MaterialContainerTransform` with Conductor? I've already looked into the `androidx-transitions` module but couldn't seem to find a way of doing it.

**Comment by PaulWoitaschek** [comment]
Yes, just return a `MaterialContainerTransform` in the `TransitionChangeHandler` and you should be good to go.
