### ISSUE TITLE
what is the status of conductor-support

### ISSUE THREAD

**Issue by NoaD** [bluelinelabs/Conductor#638]
I have a dependency in my app on `com.bluelinelabs:conductor-support`, I see that it has a different version number than `com.bluelinelabs:conductor`
I also see that `RouterPagerAdapter` history
https://github.com/bluelinelabs/Conductor/commits/010117603ce890edd1194bf0c1d35d92be854600/conductor-modules/viewpager/src/main/java/com/bluelinelabs/conductor/viewpager/RouterPagerAdapter.java

Does this mean that the support dependency isn't needed any more?

**Comment by EricKuck** [comment]
The module has been renamed to `conductor-viewpager`. Keeping the `support` name didn't make sense because it's now based on androidx.
