### ISSUE TITLE
Biometric Authentication usage

### ISSUE THREAD

**Issue by ebp-trifork** [bluelinelabs/Conductor#641]
While setting up Biometric Authentication using [this tutorial](https://developer.android.com/training/sign-in/biometric-auth#display-login-prompt), I reach the point where `BiometricPromp` class requires `Fragment` or `FragmentActivity`.

How can I do this from a `Controller`? Is there any workaround?

**Comment by solidogen** [comment]
Controller has activity property which you can cast to FragmentActivity (which AppCompatActivity derives from, make sure to use it as your Activity base)

**Comment by ebp-trifork** [comment]
Okay, thanks for the recommendation. That solves the problem.
