### ISSUE TITLE
Unable to use YoutubePlayerView or YouTubePlayerSupportFragment

### ISSUE THREAD

**Issue by avneeshkumar1** [bluelinelabs/Conductor#642]
Hi All,
 i am not able to integrate YouTubePlayerView inside Controller.
any idea how to integrate this.

**Comment by EricKuck** [comment]
What's the issue exactly? And is it specific to Conductor at all?

**Comment by PaulWoitaschek** [comment]
No I dont think this is conductor specific at all.
Read the documentation, it should get you covered :) 
https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayerView
