### ISSUE TITLE
How do I get the viewLifecycleOwner when using Controller

### ISSUE THREAD

**Issue by johnjeremih** [bluelinelabs/Conductor#647]
I'm trying to use the MVVM architecture, but I cannot get the "viewLifecycleOwner" when using the View model. How can I get viewLifecycleOwner using Controller?

`viewModel.employee!!.observe(viewLifecycleOwner,{ mAdapter.notifyDataSetChanged() })`

**Comment by EricKuck** [comment]
Sounds like you just need to add the conductor-archlifecycle module, which provides a ControllerLifecycleOwner.
