### ISSUE TITLE
do not load controller when switch theme

### ISSUE THREAD

**Issue by iranandroid** [bluelinelabs/Conductor#654]
Hi every one
I use this library in my application,  but when change UI to dark theme current controller not loaded and just fire activity onCreateView method.

how to save state current controller when switch between dark mode and light mode?

**Comment by EricKuck** [comment]
I'm not sure I understand the question. Are you saying the Activity isn't being recreated?

**Comment by iranandroid** [comment]
> I'm not sure I understand the question. Are you saying the Activity isn't being recreated?

Hi @EricKuck 
when switch dark/light mode, Activity recreated but  current controller not load and activity show empty view(because not load contoller)
