### ISSUE TITLE
Add getString() method to Controller

### ISSUE THREAD

**Issue by jpetitto** [bluelinelabs/Conductor#66]
Thoughts on adding a `getString` method to the `Controller` class? This convenience is offered by both `Activity` and `Fragment` in the Android framework and prevents having to reference `Resources` first.

I'd be happy to make this contribution if it gets the go ahead.

Note: there is also a second, overloaded method for handling string formatting as well.

**Comment by JakeWharton** [comment]
This doesn't seem like a good idea.

**Comment by jpetitto** [comment]
Can you elaborate?

**Comment by JakeWharton** [comment]
Resources have nothing to do with view composition and backstacks.

**Comment by EricKuck** [comment]
This should be easy enough to add to the application layer to not be required at the library layer.
