### ISSUE TITLE
Navigating from fragment to conductor and vice versa

### ISSUE THREAD

**Issue by johnjeremih** [bluelinelabs/Conductor#667]
I have a question; I would like to know how to navigate from a Fragment to a Conductor and then navigate back from a conductor to a fragment. I thought about using intents and startActivity, but how can I specify which conductor?

**Comment by EricKuck** [comment]
This isn't a supported use case. You'd likely have to host your fragments within controllers and use conductor's backstack or vice versa if you wanted to mix and match.
