### ISSUE TITLE
Conductor uses Fragments ? 

### ISSUE THREAD

**Issue by adnbsr** [bluelinelabs/Conductor#67]
Conductor uses Fragment internally as seen [here](https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/internal/LifecycleHandler.java), so why is it defined as fragmentless library?

**Comment by JakeWharton** [comment]
Because your application code never uses them.

**Comment by EricKuck** [comment]
No one has ever defined it as a fragmentless library. The fragment is used to maintain state and get callbacks from the host activity and nothing more. You never have to use them yourself.
