### ISSUE TITLE
Android 14 a partly 13 will break back navigation !

### ISSUE THREAD

**Issue by ursusursus** [bluelinelabs/Conductor#671]
We need to start working on the new behavior, otherwise whole library will be broken on those targeting 13 and for all on 14+

Activity.onBackPressed won't be called anymore. Library will need to tell framework ahead of time if it will take 'back' over

https://developer.android.com/about/versions/13/features/predictive-back-gesture#migrate-androidx

**Comment by EricKuck** [comment]
The best way to handle this is being evaluated now. Support will definitely be added.

**Comment by ursusursus** [comment]
Android 14 is in preview now, is there any update please?

**Comment by EricKuck** [comment]
Work on this is being done on the [v4](https://github.com/bluelinelabs/Conductor/tree/v4) branch. Hasn't been tested in production yet, but it's been very stable so far in dev.

**Comment by EricKuck** [comment]
This is now available in the newly published 4.0-preview-1 release. It's been tested in prod and appears to be very stable. It is only named preview because of potential API changes ahead of a formal 4.0 release.
