### ISSUE TITLE
Missing Github releases for versions >2.1.5

### ISSUE THREAD

**Issue by xxfast** [bluelinelabs/Conductor#679]
Is the creation of Github releases automated? If so, that might've been broken

**Comment by johnjohndoe** [comment]
Not as convenient as user facing release notes but still:

- https://github.com/bluelinelabs/Conductor/compare/2.1.5...3.1.8

**Comment by EricKuck** [comment]
Thanks for the heads up. This was never automated, I just didn't continue making releases. Will restart.

**Comment by johnjohndoe** [comment]
Release notes would be convenient. Meanwhile:

- https://github.com/bluelinelabs/Conductor/compare/3.1.8...3.1.9

**Comment by johnjohndoe** [comment]
Are you planning to add release notes for the missing ones?

**Comment by PaulWoitaschek** [comment]
I just added release notes for all releases since 2.1.4
