### ISSUE TITLE
Best practice for getting result from a Controller

### ISSUE THREAD

**Issue by lenguyenthanh** [bluelinelabs/Conductor#68]
Hi, Sometime a Controller needs to getting data from another Controller (like onActivityResult). What is best practice for this case. 

I now need to use static data for it. But want to know ideas from you guys.

**Comment by EricKuck** [comment]
There's lots of ways to do this. If you check the demo app's `TargetDisplayController` and `TargetTitleEntryController`, you'll see an example of a way to do this that's pretty similar to `onActivityResult`.

**Comment by lenguyenthanh** [comment]
Thanks for your quick reply, I forgot it example. Sorry about that.
