### ISSUE TITLE
Cannot extend FadeChangeHandler, being final in 4.0.0-preview-2

### ISSUE THREAD

**Issue by mingdong-recolor** [bluelinelabs/Conductor#687]
Visibility changed in 4.0.0-preview-2, FadeChangeHandler(together with few others, like VerticalChangeHandler etc) can not be extended any more. But I did not see anything from the change logs that reflects the change.

**Comment by EricKuck** [comment]
This wasn't ever really meant to be subclassed. Could you instead extend `AnimatorChangeHandler` and add your own fade animation?
