### ISSUE TITLE
Cannot get top controller after configuration change

### ISSUE THREAD

**Issue by cbodin** [bluelinelabs/Conductor#69]
When the controllers are restored after a configuration change, i cannot seem to find a way to get the top controller from the Router.

Something like the following would be a good convenience method:
```java
public Controller getTopController() {
    if (mBackStack.isEmpty()) {
        return null;
    }

    return mBackStack.peek().controller;
}
```

Issue #56 would also solve the problem.

**Comment by EricKuck** [comment]
#56 has been implemented in the v2 branch, so this will be coming shortly. I'm curious why you'd need to access the top controller though?

**Comment by cbodin** [comment]
Okay, great!
I've created a BaseController with a method which returns the desired status bar color. In my `ControllerChangeListener#onChangeStarted` method, i'm fetching that color and updating the decor view's systemUiVisibility flags.
When the activity is recreated, all flags are cleared and i need access to the top controller for setting the correct color again.

**Comment by EricKuck** [comment]
Check out https://github.com/bluelinelabs/Conductor/blob/v2/README.md for the docs on the new v2 release candidate. Feel free to suggest any changes before before we officially go to v2!
