### ISSUE TITLE
[help requested] Master/detail views

### ISSUE THREAD

**Issue by 3flex** [bluelinelabs/Conductor#70]
I'm trying to setup a master/detail view using two routers in a single activity and not having much luck.

If I haven't misunderstood, [this](https://github.com/bluelinelabs/Conductor/issues/24#issuecomment-210246139) and [this](https://github.com/bluelinelabs/Conductor/issues/27#issuecomment-213842062) suggests I should be able to use two routers in a single activity, with one for the master/list view and one for the detail view.

Is this the best way to go about it? Or would a single router & a parent controller be best, along with two child controllers?

I have tried adding two routers to a single activity. This seems to work, but on screen rotation one of the views doesn't get restored and onCreateView is never called. If I remove one of the routers the views are restored after rotation.

Thanks for your help!

I'm trying to set up the routers like this (the two ViewGroups are not nested in the layout):

```java
public class MainActivity extends Activity {

    private Router mRouter1;
    private Router mRouter2;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        ViewGroup containerMaster = (ViewGroup)findViewById(R.id.controller_container_master)
        ViewGroup containerDetail = (ViewGroup)findViewById(R.id.controller_container_detail)

        mRouter1 = Conductor.attachRouter(this, containerMaster, savedInstanceState);
        mRouter2 = Conductor.attachRouter(this, containerDetail, savedInstanceState);
        if (!mRouter1.hasRootController()) {
            mRouter1.setRoot(new MasterController());
        }
        if (!mRouter2.hasRootController()) {
            mRouter2.setRoot(new DetailController());
        }
    }
}
```

**Comment by EricKuck** [comment]
Master/detail didn't have great support in v1 of this lib. I just pushed a release candidate for v2, which greatly improves master/detail support, and even includes a demo for this use case. Check it out at https://github.com/bluelinelabs/Conductor/tree/v2 and let me know if you have any other questions or suggestions.
