### ISSUE TITLE
[Discussion] Remove all Lifecycle methods from Controllers in V2

### ISSUE THREAD

**Issue by sockeqwe** [bluelinelabs/Conductor#73]
I know not everybody will agree on that (and thats completely fine) I just wanted  to start a little discussion about removing all Lifecycle methods from controller class. At first glance this sounds crazy, but let me explain you what I mean:
Usually (same is valid for Activities and Fragments) you extend from the baseclass like `Controller` and then you override all required lifecycle methods.
With removing lifecycle methods I mean to remove them from Controller class entirely, so that there are no methods to override anymore.
Still sounds crazy, I know. So how do you programm then?
Well, Conductor offers `LifecycleListerner`. So instead of having one giant controller where you put a lot of code and responsibilities in, you plug in in multiple LifecycleListeners implementing the thing you need. Think about having such a LifecycleListener implementation for your controllers UI, one for Tracking, one for debugging (i.e. leakcanary) and so on ... then in you controller you only have to register those plugin s (LifecycleListeners).

Not only that by doing so you will get better single responsibility, but you are forced to build reusable components i.e. `TrackingLifecycleListener` can be reused in every controller without having to extend from a single `TrackingController` base class.

> Favor composition over inheritance

So I'm not sure if a library / framework should push such an ideology to their users, but at least I would like to discuss about such gamechanging ideas. What do you think?

**Comment by adi1133** [comment]
If you want to really favor composition over inheritance, the lifecycle should be provided by a final class and the Controller should be an interface.

**Comment by EricKuck** [comment]
I love the concept of pluggable implementations like this! I haven't been using it this way (mostly cause I never thought to), but am going to play around with it on a few other projects. 

I think the big question here is whether or not this is something we want to force developers to do. As you mention, this is a big shift from the way people are used to doing things with Fragments and Activities, which may end up with more people choosing to stay away from Conductor altogether. I wonder if there's a more gentle way to encourage good practices like this without raising the bar of entry?

**Comment by sockeqwe** [comment]
I think you are right.
Actually you could follow this pattern right now, but yes forcing them to do may raises the bar of entry.

So I guess it is fine to leave Controller and examples as they are right now, but maybe an additional section in the README explaining that with the listeners you could build a plugin system following the *Composition over Inheritance Pattern* could also demonstrate this "good practice" somehow.

**Comment by hannesstruss** [comment]
I agree, it's very nice and important to have the option of separating and plugging in lifecycle-related components!

I also think what constitutes the controller itself, the view creation, view state saving and view modification should in most cases not be extracted into another class. I would not want to have to extract a LoginViewCreationLifecycleListener for every LoginController. I'd either end up with big anonymous inner classes in the controller's constructors or lots of  separate classes, having to switch back and forth during development [Ravioli-Code-Style](http://c2.com/cgi/wiki?RavioliCode).

For me there's a difference between things that are related to a controller's lifecycle and the controller itself. The latter probably shouldn't be more reusable than it has to be - most often not at all.
