### ISSUE TITLE
AnimatorChangeHandler overlay

### ISSUE THREAD

**Issue by shchurov** [bluelinelabs/Conductor#75]
We do a lot of custom animations in our app and found the concept of `ChangeHandler` extremely helpful. 
However recently we've encountered a problem with `AnimatorChangeHandler`, here's what happens:

1. There's `ControllerA` on the screen
2. Push `ContollerB` and start `ChangeHandler` push animation
3. In the same time `ControllerB` performs some request and throws an error immediately (e.g. no internet connection)
4. As a part of that error handling we want to return to the previous screen, so `Router.popCurrentController()` is called and it starts `ChangeHandler` pop animation
5. Since push animation hasn't been completed by this moment, 2 `AnimatorChangeHandler`s overlay and it leads to a weird issue when in the end there're no attached views on the screen

I debugged it and here's what happens to those views:

1. Push `ChangeHandler` adds `ControllerA` view
2. Pop `ChangeHandler` removes `ControllerA` view
3. Push `ChangeHandler` removes `ControllerB` view

Is there any general strategy on how to handle this situation?

**Comment by EricKuck** [comment]
I'm not sure if you've tried out the v2 branch of this project yet, but I just committed a fix that's been working for me with both `AnimatorChangeHandler`s and `TransitionChangeHandler`s if you want to check it out.

**Comment by shchurov** [comment]
@EricKuck Indeed it works with that fix on v2, many thanks!
