### ISSUE TITLE
Expose Controller on RouterTransaction

### ISSUE THREAD

**Issue by hannesstruss** [bluelinelabs/Conductor#76]
Refs https://github.com/bluelinelabs/Conductor/issues/56#issuecomment-227441656

Just to make sure this isn't lost since I can't reopen the other issue:
> Thanks for implementing! Currently, access to the controller in RouterTransaction is package private though. Can we add RouterTransaction#getController()?
> 
> Actually, the complete public interface of RouterTransaction only offers methods to create new RouterTransactions based on the current one. Not sure if any other getters should be added.

**Comment by EricKuck** [comment]
Good call. Just added this for v2, which I'm hoping to make official within the next few days.

**Comment by hannesstruss** [comment]
Thanks!
