### ISSUE TITLE
V2: Views of nested ViewPager not restored when resuming

### ISSUE THREAD

**Issue by hannesstruss** [bluelinelabs/Conductor#78]
Given this hierarchy:

```
+- Root Controller -------------------+
| +- TabsController ----------------+ |
| | +- Multiple Tab Controllers --+ | |
| | |                             | | |
| | |     Tab1|Tab2|Tab3          | | |
| | +-----------------------------+ | |
| +---------------------------------+ |
+-------------------------------------+
```

When pushing a controller to the router of the Root Controller and popping that controller again, the pages of the `TabsController` are not fully restored (not just the state, but the views – the actual pages are missing, and the ViewPager swiping breaks).

Possible cause:
In `TabController#rebindIfNeeded()`, `transaction.controller.getNeedsAttach()` returns false. This might be because the `TabsController` is detached before the `TabController`s, so that `needsAttach` is not set to true in `TabController#prepareForHostDetach`. Not sure yet how a fix could look like.

Screencast: https://www.youtube.com/watch?v=Stq01cjjV_Y
Sample Code: https://github.com/hannesstruss/Conductor/tree/hs/view-pager-init/viewpagerinitdemo
Tested with 2.0.0-rc4 and current v2 branch on Nexus 5x with latest N Preview

**Comment by hannesstruss** [comment]
(The multi-level nesting is significant, the issue doesn't occur when `TabsController` is the root)

**Comment by EricKuck** [comment]
Thanks so much for all the detail. Reproducible issues are the best issues!

**Comment by leonardo2204** [comment]
I was struggling with this very same problem, but I wasn't sure if I didn't understand properly how to use the child Router. Gonna wait to see if there is some problem !
Thanks !

**Comment by hannesstruss** [comment]
Confirmed this works on v2 now, thanks for fixing!
