### ISSUE TITLE
V2: Backstack empties too early

### ISSUE THREAD

**Issue by hannesstruss** [bluelinelabs/Conductor#79]
Given a two-level-deep nesting of controllers ([Example code](https://github.com/hannesstruss/Conductor/tree/hs/child-router-backstack/viewpagerinitdemo)), performing these steps results in the Activity finishing:

1. Push three grand-child controllers (in ☝️ example: press button in the middle of the screen)
2. Rotate device 90deg
3. Press back once
4. Push one grand-child controller
5. Press back once

##### What is happening:
The Activity finished

##### What I expected to be happening:
The previous grand-child controllers being displayed

##### Possible cause:
In step 4, and all successive child router pushes, `onChildControllerPushed` is not called -> the new controller doesn't end up in `childBackstack` -> no controller has `isAttached() == true` in `handleBack` -> `handleBack` returns false and the Activity exits.

I found this comment in `monitorChildRouter`: `//TODO: is this even triggered on restoration?` – Can confirm, it isn't called ;) I guess that's what causes the call to `onChildControllerPushed` to not happen.

FWIW, I did the initialization of the first child as follows (both child- and grand-child level);

```
@Override
  protected void onChangeEnded(@NonNull ControllerChangeHandler changeHandler,
                               @NonNull ControllerChangeType changeType) {
    super.onChangeEnded(changeHandler, changeType);
    if (changeType == ControllerChangeType.PUSH_ENTER) {
      Router childRouter = getChildRouter(container, null);
      if (!childRouter.hasRootController()) {
        childRouter.pushController(RouterTransaction.with(new TabController(0)));
      }
    }
  }
```

**Comment by EricKuck** [comment]
Kept meaning to investigate that TODO and hadn't gotten around to it yet. Thanks for finding the case where it happened! Should be fixed now.
