### ISSUE TITLE
Is there a reason for the inflate/bind view creation method distinction?

### ISSUE THREAD

**Issue by JakeWharton** [bluelinelabs/Conductor#8]
I would like to convince you to combine them!

* They are always called in succession and have the same collective responsibility: going from no view to usable views. 
* The inflate/bind split is usually seen in places where views are re-used and thus re-binding needs to occur without a respective inflate. This is _never_ true for a controller since the mapping is 1:1.
* The split isn't conducive to databinding or other mechanisms where inflating and binding are a single step.
* You can still achieve the inflate/bind split at the application layer with a custom base class that marks the single `inflate` method `final` and delegates to two `abstract` methods for each responsibility. And potentially it only delegates to one method if you are using ButterKnife for all binding in that application-level base class.

**Comment by JakeWharton** [comment]
Bonus: simplified lifecycle diagram.

**Comment by EricKuck** [comment]
Excellent points. Thanks for the suggestion.

The real reason for the inflate/bind split is that while this library was internal to our company, the inflate method didn't exist. Instead it was just a getter for the controller's layout resource id. Right before open sourcing it I realized that there are lots of valid reasons someone might not want to provide a layout res id (for example, Anko), and the API changed without reevaluating the lifecycle.

So, barring any new revelations, `bindView` will be deprecated in the next version.

**Comment by EricKuck** [comment]
This is now fixed in 1.1.0. Thanks again for the input.
