### ISSUE TITLE
[Feature] Support for AsyncLayoutInflater

### ISSUE THREAD

**Issue by lupajz** [bluelinelabs/Conductor#81]
With release of support v24 there is a [AsyncLayoutInflater ](https://developer.android.com/reference/android/support/v4/view/AsyncLayoutInflater.html) helper class. Is there a way how to take advantage of async inflation instead of inflation on UI ?

**Comment by hzsweers** [comment]
it really boils down to use case. I would say that's outside the scope of the library and an implementation detail for the developer to make use of. You can inflate a stub and asynchronously inflate whatever else you need after

**Comment by ZakTaccardi** [comment]
Support for `AsyncLayoutInflator` would be really helpful.

Problem:

1. User clicks navigation drawer menu option.
2. Drawer close animation stutters while view is being inflated.

`AsyncLayoutInflator` allows us to fix this problem!

**Comment by PaulWoitaschek** [comment]
Why not just add an empty framelayout and populate the layout with the `AsyncLayoutInflater`?

**Comment by Zhuinden** [comment]
AsyncLayoutInflater is not an `AppCompatLayoutInflater` so it's theming is all screwy pre-v21.
