### ISSUE TITLE
Emptying backstack of child router

### ISSUE THREAD

**Issue by shchurov** [bluelinelabs/Conductor#82]
We use child controllers for dialogs, it provides us a nice way to control push/pop animations. However after update to v2 there's no easy way to show pop animation. `popCurrentController()` doesn't remove the view if it's the top controller of the router, debug led me to these lines `Router:561`:
```
// We're emptying out the backstack. Views get weird if you transition them out, so just no-op it. The hosting
// Activity should be handling this by finishing or at least hiding this view.
```

In my opinion it's not relevant to nested controllers, there should be a way to show pop animation for them.

**Comment by EricKuck** [comment]
There actually is a way to do this, although it's not documented super
well. Just call `setPopsLastView(true)` on the router and it'll animate out.

**Comment by shchurov** [comment]
@EricKuck You're right, it works! Many thanks!
