### ISSUE TITLE
Existing views in the router container

### ISSUE THREAD

**Issue by adi1133** [bluelinelabs/Conductor#91]
Is it allowed to have an existing child view inside the ViewGroup used as a router container? This worked in conductor v1 but is not working in v2, is this an explicit change ?

Right now I see that conductor discards the other child views on initial activity creation, but doesn't on recreation. This is caused by `removeAllExceptTopAndUnowned()` from `setRoot()` not being called upon activity recreation.

If other child views are not allowed, I suggest throwing an exception instead of removing the views. Also some migration documentation is welcome.
I can provide a PR.

**Comment by EricKuck** [comment]
Host ViewGroups should be used exclusively for a router. It wasn't really supposed to work in v1 either.

`setRoot()` clears everything out of the container so it can be sure that only the root controller is visible. It was done this way to fix #46. Throwing and exception wouldn't be very good, as the views could just be leftover from conductor itself and would be out of the control of the developer.

**Comment by adi1133** [comment]
RIght not the container is not cleared when the activity is recreated, is this working as intended ?

**Comment by EricKuck** [comment]
The view is cleared when calls that are designed to clear the view are made. `setRoot` is designed to clear the view in that it removes whatever was there and replaces it with a new root controller. The other call that does this is `setBackstack`, as that is also designed to take whatever is on screen and replace it with an entirely new backstack that was passed in. If one of these two calls aren't made, no action will be taken on other views, as it's expected that only router-owned views will be present.

**Comment by adi1133** [comment]
I have included a sample repo  [here](https://github.com/adi1133/Conductor/tree/clearview) to better showcase the issue.

I am suggesting that the views be cleared on `attachRouter()` instead of `setRoot()` and to update the javadoc of `attachRouter()`.

**Comment by EricKuck** [comment]
`setRoot` is the correct place to do this, as, when setting the root controller, you'll want everything cleared out. Perhaps what's needed is more clear documentation that host `ViewGroups` should exclusively be used for controllers?

**Comment by adi1133** [comment]
Documentation is a great choice. I am still unsure why setRoot is the proper place to do this but I trust your judgement. :+1
