### ISSUE TITLE
[Feature] Expose invalidateOptionsMenu()

### ISSUE THREAD

**Issue by leonardo2204** [bluelinelabs/Conductor#92]
Is it possible to expose the `invalidateOptionsMenu()` callback ?
I have a scenario where I need to implement a Undo-Redo button according to a DrawingView, so every time the user draws something on the screen I need to check if he can Undo this action. Depending on the stack (every time the TOUCH_UP event happens I add the drawn line to a stack) the Undo button is enabled or disabled, but I couldn't find a way to invalidate the optionsMenu.
I tried doing `setHasOptionMenu(true)` but I saw that one of the validations is `this.hasOptionsMenu != hasOptionsMenu` which turns the entire sentence to false never invalidating my Menu.

Thanks !

**Comment by EricKuck** [comment]
You should just be able to call `invalidateOptionsMenu()` on the activity, right? What's the benefit in exposing it in this lib?

**Comment by leonardo2204** [comment]
@EricKuck Sure, thanks !
