### ISSUE TITLE
Target Controller doesn't work between router boundaries

### ISSUE THREAD

**Issue by sockeqwe** [bluelinelabs/Conductor#97]
Example: 
I have a `ParentController` and add a `ChildController` (in a child Router).

If I set `ChildController.setTarget(ParentController)` then the `ChildController.targetId` is set correctly, but at the end `ChildController.getTargetController()` returns `null`.

Why?
Because `getTargetController()` internally calls `getControllerWithInstanceId()` but only on his own router (and child routers).

```java
class Controller {
 ...
   public final Controller getTargetController() {
        return targetInstanceId != null ? router.getControllerWithInstanceId(targetInstanceId) : null;
   }
   ... 
}
```

```java
class Router {

  final Controller findController(String instanceId) {
    if (this.instanceId.equals(instanceId)) {
      return this;
    }

    for (Router router : childRouters) {
      Controller matchingChild = router.getControllerWithInstanceId(instanceId);
      if (matchingChild != null) {
        return matchingChild;
      }
    }
    return null;
  }
  
  ...
}
```

See 
https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/Controller.java#L315

and 

https://github.com/bluelinelabs/Conductor/blob/develop/conductor/src/main/java/com/bluelinelabs/conductor/Router.java#L250

That means, that it will check `ChildRouter.getRouter()` backstack and `ChildRouter.getChildRouter()` backstack for Controllers with the given id. So it only makes a depth search. However, in my case the target is the parent and the current implementation doesn't take that into account. In general, Conductor can't find a target controller which is not living the same router or child router.

A possible fix could also search the parent hierarchy up like this:

```java
class Controller {
 ...
 public final Controller getTargetController() {
    if (targetInstanceId != null) {
      Controller found = router.getControllerWithInstanceId(targetInstanceId);
      if (found != null) {
        return found;
      }
      return getParentControllerWithInstanceId(targetInstanceId);
    }
    return null;
  }

  private Controller getParentControllerWithInstanceId(String instanceId) {
    if (parentController != null) {
      if (instanceId.equals(parentController.getInstanceId())) {
        return parentController;
      } else {
        return parentController.getParentControllerWithInstanceId(instanceId);
      }
    }
    return null;
   ... 
}
```

But then it only takes parent and grandparents etc. into account. It should also check for controllers in the parents router and parents child router. Unfortunately, this could end in cycles. 

So the question is, is it worth to look for such a "complete" solution or is it from your point of view working as intended right now?

The "real world" problem I stumbled upon is if I have a ParentController with a ViewPager. The ViewPager displays ChildControllers. For each ChildController in the ViewPager I set the ParentController as target (i.e. to communicate back that a button has been clicked etc.). Again, `ChildController.getTargetController()` will only scan his router downwards and is not able to find `ParentController`.  Obviously I could just use `ChildController.parentController` instead of `ChildController.getTargetController()` but I wanted to hear your thoughts on that. Also worth thinking about scenarios where such a `ChildController` instance  is used in a ViewPager and as a usual Controller somewhere else in the app where from my point of view it isn't guaranteed `ChildController.parentController` is working as it is working in a ViewPager.

**Comment by EricKuck** [comment]
This is a good catch and it's definitely worth doing a complete solution. It should not only be searching downwards like it currently is. Parent/child relationships are likely to be very common, as are sibling relationships (maybe mater/detail, for example).

**Comment by sockeqwe** [comment]
I have some time around mid August to work on that, but feel free to fix it sooner if you have a free time slot 😄

**Comment by EricKuck** [comment]
Lol sounds about like my schedule. I'll find some time to get a fix in sometime this week.

**Comment by EricKuck** [comment]
Should be good on the latest snapshot, but please reopen if there are still issues!

**Comment by sockeqwe** [comment]
Thanks! Unfortunately, it doesn't seems to be fixed for ViewPagers (each
page is a child with the parent as target). I will heck that again tomorrow
...

Eric Kuck <notifications@github.com> schrieb am Mi., 20. Juli 2016, 22:41:

**Comment by lenguyenthanh** [comment]
I have similar problem with @sockeqwe, it looks like: I have a controller `A` which do thing, a controller `B` is a parent for Controller `A` (`B` just has toolbar and add `A` as a child). A controller `C` which want to receive data from `A`. So that what I want is: set C as a target Controller for A. 

As I see on the commit, it was fixed my issue.

**Comment by sockeqwe** [comment]
@EricKuck the latest available snapshot that was deployed is from 12th of July. 

```
conductor-2.0.2-20160712.183726-1.aar	Tue Jul 12 18:37:26 UTC 2016	67431	
```

https://travis-ci.org/bluelinelabs/Conductor/branches
<img width="1057" alt="bildschirmfoto 2016-07-21 um 11 59 31" src="https://cloud.githubusercontent.com/assets/583598/17019003/a2d4e022-4f3a-11e6-9353-3dd98810c88c.png">

**Comment by EricKuck** [comment]
I have no idea why, but it looks like Travis stopped picking up commits. It's building now. Thanks for the heads up!
