### ISSUE TITLE
onDetach() not called for Controllers in pager adapter when parent router navigates.

### ISSUE THREAD

**Issue by chris-horner** [bluelinelabs/Conductor#98]
I've been working on an app that houses a few `Controllers` for tabs. I attempted to push another `Controller` onto the root router, and noticed that `onDestroy()` wasn't called for my "tabbed" controllers.

I've narrowed it down to `ControllerPagerAdapter` invoking
```java
host.removeChildRouter(router);
```
in `destroyItem()`.

This means that `onDetach()` is called just fine as the user pages through the tabs, but for some reason prevents it from being invoked as the host `Controller` is navigated away from. I've managed to solve this by adding a check of
```java
if (host.isAttached()) {
  host.removeChildRouter(router);
}
```
to `destroyItem()`, meaning that `removeChildRouter()` will only be called as the user pages through items. Happy to submit a PR with this minor change, but I'm wondering if it's the correct approach? I'm not sure why preventing `removeChildRouter()` from being invoked fixes the issue.

**Comment by chris-horner** [comment]
I've done some more digging, and have found the problem to be with calling `viewPager.setAdapter(null)` in `onDestroyView()` of `PagerController`. This makes sense, as you want to clear all references to the view.

This invokes `destroyItem()`, which invokes `removeChildRouter()` which invokes `childRouter.destroy()`. It's this call that seems to be preventing `onDetach()` from being called on the child routers.

**Comment by EricKuck** [comment]
This should be working now in the latest snapshot. Feel free to reopen if you see any other issues.
