### ISSUE TITLE
"Controller::onDestroy" is not being called when a configuration change happens

### ISSUE THREAD

**Issue by AranHase** [bluelinelabs/Conductor#99]
Is this the expected behavior? I think it can be a bit misleading because the "onDestroy" is always called in the Activity, but never in the controllers.

If this is the expected behavior, then it should be explained in the docs.

Steps to reproduce:

1. Open the Conductor's RxLifecycle Demo
2. Rotate device
3. Check logcat
4. See no "onDestroy() called" on it

**Comment by EricKuck** [comment]
Why would `onDestroy` be called when the controller isn't destroyed? I'm not sure where the confusion lies, as controllers are meant to survive configuration changes. This is documented in the lifecycle diagram.

**Comment by AranHase** [comment]
Awesome, thank you for your reply. I think that is what I was not "getting".

I opened this issue because some of my routers are being recreated on configuration changes (not just the view, but the entire thing). But I can't replicate in the demo, so it is probably something I'm doing wrong and will continue my investigation here. Sorry to take your time.

**Comment by EricKuck** [comment]
Ah, gotcha. Your routers and controllers should only be recreated if Android kills your process and recreates it later. If you see this happening under other conditions, please open an issue for it!
